In [1]:
import csv
import os
import pandas as pd
import numpy as np

In [2]:
players_data_to_load = "Resources/players"
week7_data_to_load = "Resources/week7.csv"
plays_data_to_load = "Resources/plays.csv"
pff_data_to_load = "Resources/pffScoutingData.csv"
games_data_to_load = "Resources/games.csv"

In [3]:
players_df = pd.read_csv(players_data_to_load)
players_df

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName
0,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady
1,28963,6-5,240,1982-03-02,"Miami, O.",QB,Ben Roethlisberger
2,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters
3,29851,6-2,225,1983-12-02,California,QB,Aaron Rodgers
4,30078,6-2,228,1982-11-24,Harvard,QB,Ryan Fitzpatrick
...,...,...,...,...,...,...,...
1674,53991,6-1,320,NaN,NaN,DT,Forrest Merrill
1675,53994,6-5,300,NaN,NaN,C,Ryan McCollum
1676,53999,6-4,312,NaN,NaN,DT,Jack Heflin
1677,54006,6-6,330,NaN,NaN,T,Jake Curhan
1678,54038,6-6,245,NaN,NaN,QB,Feleipe Franks

In [4]:
week7_df = pd.read_csv(week7_data_to_load)
week7_df

,gameId,playId,nflId,frameId,time,jerseyNumber,team,playDirection,x,y,s,a,dis,o,dir,event
0,2021102100,56,35459.0,1,2021-10-22T00:23:17.300,22.0,DEN,left,75.42,20.77,0.97,1.03,0.09,60.75,64.69,None
1,2021102100,56,35459.0,2,2021-10-22T00:23:17.400,22.0,DEN,left,75.51,20.82,1.09,0.97,0.11,63.06,60.90,None
2,2021102100,56,35459.0,3,2021-10-22T00:23:17.500,22.0,DEN,left,75.61,20.88,1.23,0.79,0.12,63.06,61.13,None
3,2021102100,56,35459.0,4,2021-10-22T00:23:17.600,22.0,DEN,left,75.73,20.94,1.30,0.57,0.13,62.35,60.85,None
4,2021102100,56,35459.0,5,2021-10-22T00:23:17.700,22.0,DEN,left,75.84,21.01,1.33,0.37,0.13,60.65,60.99,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
906287,2021102500,3998,NaN,71,2021-10-26T03:17:05.900,NaN,football,left,112.93,14.52,22.04,0.44,2.62,NaN,NaN,pass_forward
906288,2021102500,3998,NaN,72,2021-10-26T03:17:06.000,NaN,football,left,111.34,16.07,21.95,1.40,2.22,NaN,NaN,None
906289,2021102500,3998,NaN,73,2021-10-26T03:17:06.100,NaN,football,left,109.74,17.60,21.81,2.02,2.21,NaN,NaN,None
906290,2021102500,3998,NaN,74,2021-10-26T03:17:06.200,NaN,football,left,108.17,19.12,21.66,2.39,2.19,NaN,NaN,None
906291,2021102500,3998,NaN,75,2021-10-26T03:17:06.300,NaN,football,left,106.62,20.63,21.53,2.68,2.17,NaN,NaN,None

In [5]:
week7_players = players_df.merge(week7_df, how='left')
week7_players

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
0,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021102e+09,158.0,1.0,...,TB,left,43.51,24.13,0.11,0.08,0.02,285.84,192.53,None
1,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021102e+09,158.0,2.0,...,TB,left,43.51,24.12,0.10,0.08,0.01,285.84,192.22,None
2,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021102e+09,158.0,3.0,...,TB,left,43.54,24.14,0.06,0.05,0.03,290.98,171.42,None
3,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021102e+09,158.0,4.0,...,TB,left,43.61,24.15,0.08,0.06,0.07,297.66,121.53,None
4,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021102e+09,158.0,5.0,...,TB,left,43.66,24.13,0.11,0.09,0.06,296.28,116.12,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
867588,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021102e+09,3998.0,72.0,...,SEA,left,109.87,21.95,2.82,1.38,0.29,268.97,241.24,None
867589,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021102e+09,3998.0,73.0,...,SEA,left,109.61,21.84,2.81,1.57,0.28,264.88,246.09,None
867590,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021102e+09,3998.0,74.0,...,SEA,left,109.33,21.75,2.84,1.80,0.29,272.01,252.77,None
867591,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021102e+09,3998.0,75.0,...,SEA,left,109.04,21.70,2.85,2.01,0.29,274.50,259.06,None
867592,54038,6-6,245,NaN,NaN,QB,Feleipe Franks,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Centers

In [6]:
week7_players_C = week7_players[week7_players['officialPosition'] == 'C']
week7_players_C.head()

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
14603,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021102e+09,62.0,1.0,...,SF,left,88.95,30.11,0.16,0.14,0.03,246.86,9.10,None
14604,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021102e+09,62.0,2.0,...,SF,left,88.95,30.10,0.10,0.17,0.01,249.10,15.14,None
14605,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021102e+09,62.0,3.0,...,SF,left,88.94,30.07,0.01,0.17,0.03,251.79,53.31,None
14606,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021102e+09,62.0,4.0,...,SF,left,88.92,30.07,0.04,0.33,0.02,252.53,242.02,None
14607,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021102e+09,62.0,5.0,...,SF,left,88.91,30.07,0.10,0.42,0.02,253.50,243.37,None

In [7]:
week7_players_C = week7_players_C[week7_players_C['event'] != 'None']
week7_players_C

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
14608,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021102e+09,62.0,6.0,...,SF,left,88.92,30.08,0.06,0.21,0.01,256.87,229.04,ball_snap
14609,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021102e+09,62.0,7.0,...,SF,left,88.93,30.10,0.10,0.40,0.03,261.32,18.40,autoevent_ballsnap
14623,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021102e+09,62.0,21.0,...,SF,left,89.28,33.97,4.33,0.71,0.45,34.01,5.94,play_action
14642,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021102e+09,62.0,40.0,...,SF,left,90.03,41.33,2.87,2.03,0.30,239.68,7.61,pass_forward
14650,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021102e+09,141.0,3.0,...,SF,left,70.81,23.68,0.05,0.06,0.00,268.66,22.88,man_in_motion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
816334,53492,6-5,316,NaN,NaN,C,Creed Humphrey,2.021102e+09,4201.0,40.0,...,KC,left,26.38,28.80,1.52,0.68,0.15,236.62,265.92,pass_outcome_caught
825479,53516,6-3,310,NaN,NaN,C,Kendrick Green,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
833881,53543,6-3,300,NaN,NaN,C,Drew Dalman,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
851166,53619,6-3,330,NaN,NaN,C,Trey Hill,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
867515,53994,6-5,300,NaN,NaN,C,Ryan McCollum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
week7_players_C = week7_players_C.sort_values('a', ascending = False)
week7_players_C

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
240620,43307,6-4,309,1993-05-30,Alabama,C,Ryan Kelly,2.021102e+09,3714.0,38.0,...,IND,left,43.83,25.74,2.37,4.46,0.26,168.90,79.59,pass_forward
710105,52486,6-4,290,1997-11-17,Temple,C,Matt Hennessy,2.021102e+09,2755.0,36.0,...,ATL,right,51.42,20.09,2.80,3.86,0.30,193.10,233.76,pass_forward
313932,43695,6-3,313,1993-02-17,Duke,C,Matt Skura,2.021102e+09,3617.0,30.0,...,NYG,right,73.84,28.70,2.55,3.59,0.27,250.62,295.93,pass_forward
394189,45012,6-4,312,1993-08-23,Wyoming,C,Chase Roullier,2.021102e+09,1202.0,39.0,...,WAS,right,30.19,22.87,1.32,3.58,0.14,45.85,299.09,run
154048,41630,6-3,317,1992-05-31,Central Florida,C,Justin McCray,2.021102e+09,2172.0,38.0,...,HOU,left,88.29,18.46,1.17,3.44,0.12,30.41,36.68,pass_forward
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813818,53491,6-5,312,NaN,NaN,C,Josh Myers,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
825479,53516,6-3,310,NaN,NaN,C,Kendrick Green,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
833881,53543,6-3,300,NaN,NaN,C,Drew Dalman,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
851166,53619,6-3,330,NaN,NaN,C,Trey Hill,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
867515,53994,6-5,300,NaN,NaN,C,Ryan McCollum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
week7_players_C = week7_players_C.dropna()

In [10]:
cleaned_C= week7_players_C[['nflId', 'height', 'weight', 'displayName', 'gameId', 'playId', 'frameId', 'team', 's', 'a', 'dis', 'event']]
cleaned_C

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,dis,event
240620,43307,6-4,309,Ryan Kelly,2.021102e+09,3714.0,38.0,IND,2.37,4.46,0.26,pass_forward
710105,52486,6-4,290,Matt Hennessy,2.021102e+09,2755.0,36.0,ATL,2.80,3.86,0.30,pass_forward
313932,43695,6-3,313,Matt Skura,2.021102e+09,3617.0,30.0,NYG,2.55,3.59,0.27,pass_forward
394189,45012,6-4,312,Chase Roullier,2.021102e+09,1202.0,39.0,WAS,1.32,3.58,0.14,run
154048,41630,6-3,317,Justin McCray,2.021102e+09,2172.0,38.0,HOU,1.17,3.44,0.12,pass_forward
...,...,...,...,...,...,...,...,...,...,...,...,...
288229,43433,6-4,306,Connor McGovern,2.021102e+09,3822.0,7.0,NYJ,0.00,0.00,0.00,autoevent_ballsnap
94910,40070,6-4,307,J.C. Tretter,2.021102e+09,1794.0,6.0,CLE,0.00,0.00,0.01,ball_snap
145659,41436,6-3,300,Matt Paradis,2.021102e+09,3967.0,6.0,CAR,0.00,0.00,0.01,autoevent_ballsnap
312854,43695,6-3,313,Matt Skura,2.021102e+09,1065.0,7.0,NYG,0.00,0.00,0.01,ball_snap
312853,43695,6-3,313,Matt Skura,2.021102e+09,1065.0,6.0,NYG,0.00,0.00,0.02,autoevent_ballsnap

## Guards

In [11]:
week7_players_G = week7_players[week7_players['officialPosition'] == 'G']
week7_players_G

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
20572,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021102e+09,64.0,1.0,...,TEN,right,33.21,31.28,0.00,0.00,0.00,107.41,133.59,None
20573,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021102e+09,64.0,2.0,...,TEN,right,33.21,31.28,0.00,0.00,0.00,107.41,128.17,None
20574,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021102e+09,64.0,3.0,...,TEN,right,33.21,31.28,0.00,0.00,0.00,108.16,142.73,None
20575,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021102e+09,64.0,4.0,...,TEN,right,33.21,31.28,0.01,0.15,0.00,108.16,144.24,None
20576,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021102e+09,64.0,5.0,...,TEN,right,33.22,31.28,0.06,0.48,0.01,109.12,143.73,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
858908,53655,6-6,325,NaN,NaN,G,Trey Smith,2.021102e+09,4201.0,38.0,...,KC,left,28.87,32.56,0.66,1.18,0.07,286.19,95.85,None
858909,53655,6-6,325,NaN,NaN,G,Trey Smith,2.021102e+09,4201.0,39.0,...,KC,left,28.92,32.56,0.50,1.19,0.05,281.06,91.20,pass_arrived
858910,53655,6-6,325,NaN,NaN,G,Trey Smith,2.021102e+09,4201.0,40.0,...,KC,left,28.96,32.56,0.38,1.08,0.04,278.65,92.25,pass_outcome_caught
861534,53861,6-5,330,NaN,NaN,G,Robert Jones,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
866031,53954,6-5,319,NaN,NaN,G,Tommy Kraemer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
week7_players_G = week7_players_G[week7_players_G['event'] != 'None']
week7_players_G

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
20577,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021102e+09,64.0,6.0,...,TEN,right,33.23,31.26,0.24,1.28,0.02,109.98,155.67,autoevent_ballsnap
20578,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021102e+09,64.0,7.0,...,TEN,right,33.25,31.19,0.66,2.56,0.07,109.20,157.75,ball_snap
20589,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021102e+09,64.0,18.0,...,TEN,right,34.16,28.65,2.93,1.70,0.30,96.07,172.82,play_action
20605,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021102e+09,64.0,34.0,...,TEN,right,33.69,25.55,0.35,1.33,0.04,104.07,270.92,pass_forward
20606,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021102e+09,64.0,35.0,...,TEN,right,33.66,25.52,0.38,0.57,0.05,105.02,261.15,autoevent_passforward
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
858906,53655,6-6,325,NaN,NaN,G,Trey Smith,2.021102e+09,4201.0,36.0,...,KC,left,28.72,32.57,0.96,1.20,0.10,293.20,94.84,autoevent_passforward
858909,53655,6-6,325,NaN,NaN,G,Trey Smith,2.021102e+09,4201.0,39.0,...,KC,left,28.92,32.56,0.50,1.19,0.05,281.06,91.20,pass_arrived
858910,53655,6-6,325,NaN,NaN,G,Trey Smith,2.021102e+09,4201.0,40.0,...,KC,left,28.96,32.56,0.38,1.08,0.04,278.65,92.25,pass_outcome_caught
861534,53861,6-5,330,NaN,NaN,G,Robert Jones,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
866031,53954,6-5,319,NaN,NaN,G,Tommy Kraemer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
week7_players_G = week7_players_G.sort_values('a', ascending = False)

In [14]:
week7_players_G = week7_players_G.dropna()

In [15]:
cleaned_G = week7_players_G[['nflId', 'height', 'weight', 'displayName', 'gameId', 'playId', 'frameId', 'team', 's', 'a', 'dis', 'event']]
cleaned_G

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,dis,event
720320,52514,6-5,345,Tyre Phillips,2.021102e+09,2055.0,16.0,BAL,1.42,4.35,0.13,play_action
440008,46103,6-2,327,Will Hernandez,2.021102e+09,1148.0,29.0,NYG,2.33,4.03,0.24,autoevent_passforward
612995,47906,6-4,310,Ben Powers,2.021102e+09,3070.0,43.0,BAL,1.43,3.98,0.14,autoevent_passforward
420348,46075,6-5,330,Quenton Nelson,2.021102e+09,1752.0,35.0,IND,2.46,3.98,0.23,pass_forward
653577,48485,6-5,310,Blake Hance,2.021102e+09,2590.0,33.0,CLE,1.77,3.96,0.18,autoevent_passforward
...,...,...,...,...,...,...,...,...,...,...,...,...
741605,52590,6-3,350,Michael Onwenu,2.021102e+09,948.0,6.0,NE,0.00,0.00,0.00,ball_snap
43609,38557,6-4,315,Kevin Zeitler,2.021102e+09,1213.0,3.0,BAL,0.00,0.00,0.01,man_in_motion
269462,43367,6-5,308,Joe Thuney,2.021102e+09,4027.0,6.0,KC,0.00,0.00,0.01,ball_snap
741647,52590,6-3,350,Michael Onwenu,2.021102e+09,970.0,6.0,NE,0.00,0.00,0.01,ball_snap
708206,52483,6-4,305,Jonah Jackson,2.021102e+09,2724.0,7.0,DET,0.00,0.00,0.01,autoevent_ballsnap

## Tackles

In [16]:
week7_players_T = week7_players[week7_players['officialPosition'] == 'T']
week7_players_T

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
1073,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021102e+09,75.0,1.0,...,CHI,right,33.81,32.93,0.26,0.26,0.04,237.98,148.21,None
1074,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021102e+09,75.0,2.0,...,CHI,right,33.87,32.90,0.36,0.26,0.07,230.52,135.42,None
1075,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021102e+09,75.0,3.0,...,CHI,right,33.96,32.85,0.50,0.24,0.09,225.40,127.98,None
1076,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021102e+09,75.0,4.0,...,CHI,right,33.99,32.84,0.45,0.12,0.04,224.73,121.37,None
1077,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021102e+09,75.0,5.0,...,CHI,right,33.91,32.97,0.22,0.60,0.16,221.57,9.63,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
867587,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021102e+09,3998.0,71.0,...,SEA,left,110.12,22.09,2.76,1.25,0.28,270.49,236.45,pass_forward
867588,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021102e+09,3998.0,72.0,...,SEA,left,109.87,21.95,2.82,1.38,0.29,268.97,241.24,None
867589,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021102e+09,3998.0,73.0,...,SEA,left,109.61,21.84,2.81,1.57,0.28,264.88,246.09,None
867590,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021102e+09,3998.0,74.0,...,SEA,left,109.33,21.75,2.84,1.80,0.29,272.01,252.77,None
867591,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021102e+09,3998.0,75.0,...,SEA,left,109.04,21.70,2.85,2.01,0.29,274.50,259.06,None

In [17]:
week7_players_T = week7_players_T[week7_players_T['event'] != 'None']
week7_players_T

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
1078,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021102e+09,75.0,6.0,...,CHI,right,33.90,33.00,0.28,0.60,0.03,220.04,358.38,autoevent_ballsnap
1081,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021102e+09,75.0,9.0,...,CHI,right,33.77,33.36,1.11,0.82,0.11,202.93,337.92,ball_snap
1093,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021102e+09,75.0,21.0,...,CHI,right,33.49,32.06,2.71,1.06,0.27,98.11,185.50,play_action
1110,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021102e+09,75.0,38.0,...,CHI,right,30.20,27.57,3.58,1.99,0.37,324.93,230.78,qb_strip_sack
1121,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021102e+09,104.0,6.0,...,CHI,right,28.20,29.88,0.70,1.35,0.20,52.53,295.01,ball_snap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861535,53868,6-6,315,NaN,NaN,T,Alaric Jackson,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
867522,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021102e+09,3998.0,6.0,...,SEA,left,105.27,26.75,0.25,1.28,0.02,332.17,62.00,autoevent_ballsnap
867524,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021102e+09,3998.0,8.0,...,SEA,left,105.39,26.80,0.81,2.06,0.08,332.17,64.05,ball_snap
867586,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021102e+09,3998.0,70.0,...,SEA,left,110.35,22.25,2.76,1.13,0.28,268.23,233.12,autoevent_passforward
867587,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021102e+09,3998.0,71.0,...,SEA,left,110.12,22.09,2.76,1.25,0.28,270.49,236.45,pass_forward

In [18]:
week7_players_T = week7_players_T.sort_values('a', ascending = False)

In [19]:
week7_players_T = week7_players_T.dropna()

In [20]:
cleaned_T = week7_players_T[['nflId', 'height', 'weight', 'displayName', 'gameId', 'playId', 'frameId', 'team', 's', 'a', 'dis', 'event']]
cleaned_T

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,dis,event
225059,42924,6-6,325,Jesse Davis,2.021102e+09,3689.0,14.0,MIA,1.60,5.22,0.13,play_action
27219,37090,6-8,325,Nate Solder,2.021102e+09,742.0,8.0,NYG,1.47,4.99,0.13,autoevent_ballsnap
223924,42924,6-6,325,Jesse Davis,2.021102e+09,557.0,36.0,MIA,1.56,4.87,0.16,pass_forward
511301,46275,6-7,332,Matt Pryor,2.021102e+09,3621.0,25.0,IND,2.46,4.29,0.27,autoevent_passforward
514581,46302,6-8,344,Jordan Mailata,2.021102e+09,3301.0,35.0,PHI,0.65,4.28,0.06,pass_arrived
...,...,...,...,...,...,...,...,...,...,...,...,...
470136,46152,6-8,345,Orlando Brown,2.021102e+09,3090.0,1.0,KC,0.00,0.00,0.00,line_set
514038,46302,6-8,344,Jordan Mailata,2.021102e+09,2169.0,6.0,PHI,0.00,0.00,0.00,ball_snap
514039,46302,6-8,344,Jordan Mailata,2.021102e+09,2169.0,7.0,PHI,0.00,0.00,0.00,autoevent_ballsnap
87427,40023,6-5,304,Terron Armstead,2.021102e+09,253.0,7.0,NO,0.00,0.00,0.01,ball_snap
500564,46237,6-4,293,Jamarco Jones,2.021102e+09,2348.0,6.0,SEA,0.00,0.00,0.00,ball_snap

## Plays, PFF, & Games data added

In [21]:
plays_df = pd.read_csv(plays_data_to_load)
plays_df

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,defensiveTeam,yardlineSide,yardlineNumber,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,2021090900,97,(13:33) (Shotgun) T.Brady pass incomplete deep...,1,3,2,TB,DAL,TB,33,...,NaN,43.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
1,2021090900,137,(13:18) (Shotgun) D.Prescott pass deep left to...,1,1,10,DAL,TB,DAL,2,...,NaN,108.0,EMPTY,"1 RB, 2 TE, 2 WR",6.0,"4 DL, 4 LB, 3 DB",TRADITIONAL,0,Cover-3,Zone
2,2021090900,187,(12:23) (Shotgun) D.Prescott pass short middle...,1,2,6,DAL,TB,DAL,34,...,NaN,76.0,SHOTGUN,"0 RB, 2 TE, 3 WR",6.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,0,Cover-3,Zone
3,2021090900,282,(9:56) D.Prescott pass incomplete deep left to...,1,1,10,DAL,TB,TB,39,...,NaN,49.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",6.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1,Cover-3,Zone
4,2021090900,349,(9:46) (Shotgun) D.Prescott pass incomplete sh...,1,3,15,DAL,TB,TB,44,...,NaN,54.0,SHOTGUN,"1 RB, 1 TE, 3 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,0,Cover-3,Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8552,2021110100,4310,(1:56) (Shotgun) P.Mahomes sacked at NYG 16 fo...,4,3,8,KC,NYG,NYG,8,...,NaN,18.0,SHOTGUN,"1 RB, 1 TE, 3 WR",4.0,"1 DL, 3 LB, 7 DB",SCRAMBLE,0,Bracket,Other
8553,2021110100,4363,(1:07) (Shotgun) D.Jones pass short right to E...,4,1,10,NYG,KC,NYG,25,...,NaN,35.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"4 DL, 1 LB, 6 DB",SCRAMBLE,0,Cover-2,Zone
8554,2021110100,4392,"(1:01) (No Huddle, Shotgun) D.Jones sacked at ...",4,2,7,NYG,KC,NYG,28,...,NaN,38.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Cover-2,Zone
8555,2021110100,4411,"(:39) (No Huddle, Shotgun) D.Jones pass incomp...",4,3,15,NYG,KC,NYG,20,...,NaN,30.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Cover-2,Zone
8556,2021110100,4433,(:35) (Shotgun) D.Jones sacked at NYG 14 for -...,4,4,15,NYG,KC,NYG,20,...,NaN,30.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Quarters,Zone

In [22]:
pff_df = pd.read_csv(pff_data_to_load)
pff_df

,gameId,playId,nflId,pff_role,pff_positionLinedUp,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,2021090900,97,25511,Pass,QB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021090900,97,35481,Pass Route,TE-L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021090900,97,35634,Pass Route,LWR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021090900,97,39985,Pass Route,HB-R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021090900,97,40151,Pass Block,C,NaN,NaN,NaN,0.0,0.0,0.0,0.0,44955.0,SW,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188249,2021110100,4433,52507,Pass Block,LT,NaN,NaN,NaN,0.0,0.0,1.0,0.0,43338.0,PP,0.0
188250,2021110100,4433,52546,Coverage,SCBoR,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188251,2021110100,4433,52573,Pass Route,SLoWR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188252,2021110100,4433,52585,Pass Rush,LEO,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188253,2021110100,4433,53449,Pass Route,LWR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
games_df = pd.read_csv(games_data_to_load)
games_df

,gameId,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,2021090900,2021,1,09/09/2021,20:20:00,TB,DAL
1,2021091200,2021,1,09/12/2021,13:00:00,ATL,PHI
2,2021091201,2021,1,09/12/2021,13:00:00,BUF,PIT
3,2021091202,2021,1,09/12/2021,13:00:00,CAR,NYJ
4,2021091203,2021,1,09/12/2021,13:00:00,CIN,MIN
...,...,...,...,...,...,...,...
117,2021103109,2021,8,10/31/2021,16:05:00,SEA,JAX
118,2021103110,2021,8,10/31/2021,16:25:00,DEN,WAS
119,2021103111,2021,8,10/31/2021,16:25:00,NO,TB
120,2021103112,2021,8,10/31/2021,20:20:00,MIN,DAL
121,2021110100,2021,8,11/01/2021,20:15:00,KC,NYG

# Merging all data & Cleaning

## Center

In [24]:
w7_C = cleaned_C.merge(plays_df, how="left")
w7_C.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,43307,6-4,309,Ryan Kelly,2.021102e+09,3714.0,38.0,IND,2.37,4.46,...,NaN,38.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-3,Zone
1,52486,6-4,290,Matt Hennessy,2.021102e+09,2755.0,36.0,ATL,2.80,3.86,...,NaN,60.0,SHOTGUN,"1 RB, 2 TE, 2 WR",5.0,"2 DL, 2 LB, 7 DB",TRADITIONAL,0,Cover-1,Man
2,43695,6-3,313,Matt Skura,2.021102e+09,3617.0,30.0,NYG,2.55,3.59,...,NaN,80.0,SHOTGUN,"1 RB, 2 TE, 2 WR",6.0,"3 DL, 3 LB, 5 DB",DESIGNED_ROLLOUT_LEFT,0,Cover-3,Zone
3,45012,6-4,312,Chase Roullier,2.021102e+09,1202.0,39.0,WAS,1.32,3.58,...,NaN,38.0,I_FORM,"1 RB, 2 TE, 2 WR",6.0,"3 DL, 4 LB, 4 DB",SCRAMBLE,1,Cover-3,Zone
4,41630,6-3,317,Justin McCray,2.021102e+09,2172.0,38.0,HOU,1.17,3.44,...,NaN,85.0,I_FORM,"1 RB, 2 TE, 2 WR",7.0,"3 DL, 4 LB, 4 DB",DESIGNED_ROLLOUT_RIGHT,1,Cover-3,Zone

In [25]:
w7_C.drop(columns=[['possessionTeam','pff_passCoverage','pff_passCoverageType']], inplace=True, errors='ignore')

In [26]:
w7_C = w7_C.merge(pff_df, how='left')
w7_C.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,43307,6-4,309,Ryan Kelly,2.021102e+09,3714.0,38.0,IND,2.37,4.46,...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,42360.0,PP,0.0
1,52486,6-4,290,Matt Hennessy,2.021102e+09,2755.0,36.0,ATL,2.80,3.86,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,45274.0,PT,0.0
2,43695,6-3,313,Matt Skura,2.021102e+09,3617.0,30.0,NYG,2.55,3.59,...,NaN,NaN,NaN,0.0,1.0,0.0,0.0,47799.0,PR,0.0
3,45012,6-4,312,Chase Roullier,2.021102e+09,1202.0,39.0,WAS,1.32,3.58,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,43316.0,PA,0.0
4,41630,6-3,317,Justin McCray,2.021102e+09,2172.0,38.0,HOU,1.17,3.44,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,52522.0,PA,0.0

In [27]:
w7_C = w7_C.merge(games_df, how='left')
w7_C.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,43307,6-4,309,Ryan Kelly,2.021102e+09,3714.0,38.0,IND,2.37,4.46,...,0.0,42360.0,PP,0.0,2021,7,10/24/2021,20:20:00,SF,IND
1,52486,6-4,290,Matt Hennessy,2.021102e+09,2755.0,36.0,ATL,2.80,3.86,...,0.0,45274.0,PT,0.0,2021,7,10/24/2021,13:00:00,MIA,ATL
2,43695,6-3,313,Matt Skura,2.021102e+09,3617.0,30.0,NYG,2.55,3.59,...,0.0,47799.0,PR,0.0,2021,7,10/24/2021,13:00:00,NYG,CAR
3,45012,6-4,312,Chase Roullier,2.021102e+09,1202.0,39.0,WAS,1.32,3.58,...,0.0,43316.0,PA,0.0,2021,7,10/24/2021,13:00:00,GB,WAS
4,41630,6-3,317,Justin McCray,2.021102e+09,2172.0,38.0,HOU,1.17,3.44,...,0.0,52522.0,PA,0.0,2021,7,10/24/2021,16:25:00,ARI,HOU

In [28]:
w7_C.drop(columns=['homeTeamAbbr', 'visitorTeamAbbr','gameDate', 'gameTimeEastern', 'season'], inplace=True, errors='ignore')
w7_C

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,43307,6-4,309,Ryan Kelly,2.021102e+09,3714.0,38.0,IND,2.37,4.46,...,NaN,NaN,1.0,0.0,0.0,0.0,42360.0,PP,0.0,7
1,52486,6-4,290,Matt Hennessy,2.021102e+09,2755.0,36.0,ATL,2.80,3.86,...,NaN,NaN,0.0,0.0,0.0,0.0,45274.0,PT,0.0,7
2,43695,6-3,313,Matt Skura,2.021102e+09,3617.0,30.0,NYG,2.55,3.59,...,NaN,NaN,0.0,1.0,0.0,0.0,47799.0,PR,0.0,7
3,45012,6-4,312,Chase Roullier,2.021102e+09,1202.0,39.0,WAS,1.32,3.58,...,NaN,NaN,0.0,0.0,1.0,0.0,43316.0,PA,0.0,7
4,41630,6-3,317,Justin McCray,2.021102e+09,2172.0,38.0,HOU,1.17,3.44,...,NaN,NaN,0.0,0.0,0.0,0.0,52522.0,PA,0.0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2865,43433,6-4,306,Connor McGovern,2.021102e+09,3822.0,7.0,NYJ,0.00,0.00,...,NaN,NaN,0.0,0.0,0.0,0.0,42433.0,PT,0.0,7
2866,40070,6-4,307,J.C. Tretter,2.021102e+09,1794.0,6.0,CLE,0.00,0.00,...,NaN,NaN,0.0,0.0,0.0,0.0,48089.0,PP,0.0,7
2867,41436,6-3,300,Matt Paradis,2.021102e+09,3967.0,6.0,CAR,0.00,0.00,...,NaN,NaN,0.0,0.0,0.0,0.0,43332.0,PP,0.0,7
2868,43695,6-3,313,Matt Skura,2.021102e+09,1065.0,7.0,NYG,0.00,0.00,...,NaN,NaN,0.0,0.0,0.0,0.0,52446.0,PP,0.0,7
2869,43695,6-3,313,Matt Skura,2.021102e+09,1065.0,6.0,NYG,0.00,0.00,...,NaN,NaN,0.0,0.0,0.0,0.0,52446.0,PP,0.0,7

In [29]:
w7_C.to_csv('Resources/center_w7.csv', sep=',', index=False)

In [30]:
w7_C_df = pd.read_csv('Resources/center_w7.csv')
w7_C_df.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,43307,6-4,309,Ryan Kelly,2.021102e+09,3714.0,38.0,IND,2.37,4.46,...,NaN,NaN,1.0,0.0,0.0,0.0,42360.0,PP,0.0,7
1,52486,6-4,290,Matt Hennessy,2.021102e+09,2755.0,36.0,ATL,2.80,3.86,...,NaN,NaN,0.0,0.0,0.0,0.0,45274.0,PT,0.0,7
2,43695,6-3,313,Matt Skura,2.021102e+09,3617.0,30.0,NYG,2.55,3.59,...,NaN,NaN,0.0,1.0,0.0,0.0,47799.0,PR,0.0,7
3,45012,6-4,312,Chase Roullier,2.021102e+09,1202.0,39.0,WAS,1.32,3.58,...,NaN,NaN,0.0,0.0,1.0,0.0,43316.0,PA,0.0,7
4,41630,6-3,317,Justin McCray,2.021102e+09,2172.0,38.0,HOU,1.17,3.44,...,NaN,NaN,0.0,0.0,0.0,0.0,52522.0,PA,0.0,7

## Guard

In [31]:
w7_G = cleaned_G.merge(plays_df, how="left")
w7_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,52514,6-5,345,Tyre Phillips,2.021102e+09,2055.0,16.0,BAL,1.42,4.35,...,NaN,36.0,PISTOL,"2 RB, 0 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,1,Cover-6,Zone
1,46103,6-2,327,Will Hernandez,2.021102e+09,1148.0,29.0,NYG,2.33,4.03,...,NaN,79.0,SHOTGUN,"1 RB, 1 TE, 3 WR",7.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
2,47906,6-4,310,Ben Powers,2.021102e+09,3070.0,43.0,BAL,1.43,3.98,...,NaN,81.0,I_FORM,"2 RB, 2 TE, 1 WR",7.0,"5 DL, 2 LB, 4 DB",TRADITIONAL,1,Cover-3,Zone
3,46075,6-5,330,Quenton Nelson,2.021102e+09,1752.0,35.0,IND,2.46,3.98,...,NaN,30.0,SHOTGUN,"2 RB, 1 TE, 2 WR",7.0,"4 DL, 2 LB, 5 DB",NaN,1,Cover-1,Man
4,48485,6-5,310,Blake Hance,2.021102e+09,2590.0,33.0,CLE,1.77,3.96,...,NaN,16.0,EMPTY,"1 RB, 3 TE, 1 WR",6.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,0,Cover-0,Man

In [32]:
w7_G.drop(columns=[['possessionTeam','pff_passCoverage','pff_passCoverageType']], inplace=True, errors='ignore')
w7_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,52514,6-5,345,Tyre Phillips,2.021102e+09,2055.0,16.0,BAL,1.42,4.35,...,NaN,36.0,PISTOL,"2 RB, 0 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,1,Cover-6,Zone
1,46103,6-2,327,Will Hernandez,2.021102e+09,1148.0,29.0,NYG,2.33,4.03,...,NaN,79.0,SHOTGUN,"1 RB, 1 TE, 3 WR",7.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
2,47906,6-4,310,Ben Powers,2.021102e+09,3070.0,43.0,BAL,1.43,3.98,...,NaN,81.0,I_FORM,"2 RB, 2 TE, 1 WR",7.0,"5 DL, 2 LB, 4 DB",TRADITIONAL,1,Cover-3,Zone
3,46075,6-5,330,Quenton Nelson,2.021102e+09,1752.0,35.0,IND,2.46,3.98,...,NaN,30.0,SHOTGUN,"2 RB, 1 TE, 2 WR",7.0,"4 DL, 2 LB, 5 DB",NaN,1,Cover-1,Man
4,48485,6-5,310,Blake Hance,2.021102e+09,2590.0,33.0,CLE,1.77,3.96,...,NaN,16.0,EMPTY,"1 RB, 3 TE, 1 WR",6.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,0,Cover-0,Man

In [33]:
w7_G = w7_G.merge(pff_df, how='left')
w7_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,52514,6-5,345,Tyre Phillips,2.021102e+09,2055.0,16.0,BAL,1.42,4.35,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,43455.0,CL,0.0
1,46103,6-2,327,Will Hernandez,2.021102e+09,1148.0,29.0,NYG,2.33,4.03,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,52415.0,PP,0.0
2,47906,6-4,310,Ben Powers,2.021102e+09,3070.0,43.0,BAL,1.43,3.98,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,46146.0,UP,0.0
3,46075,6-5,330,Quenton Nelson,2.021102e+09,1752.0,35.0,IND,2.46,3.98,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,46197.0,PA,0.0
4,48485,6-5,310,Blake Hance,2.021102e+09,2590.0,33.0,CLE,1.77,3.96,...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,48089.0,PP,0.0

In [34]:
w7_G = w7_G.merge(games_df, how='left')
w7_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,52514,6-5,345,Tyre Phillips,2.021102e+09,2055.0,16.0,BAL,1.42,4.35,...,0.0,43455.0,CL,0.0,2021,7,10/24/2021,13:00:00,BAL,CIN
1,46103,6-2,327,Will Hernandez,2.021102e+09,1148.0,29.0,NYG,2.33,4.03,...,0.0,52415.0,PP,0.0,2021,7,10/24/2021,13:00:00,NYG,CAR
2,47906,6-4,310,Ben Powers,2.021102e+09,3070.0,43.0,BAL,1.43,3.98,...,0.0,46146.0,UP,0.0,2021,7,10/24/2021,13:00:00,BAL,CIN
3,46075,6-5,330,Quenton Nelson,2.021102e+09,1752.0,35.0,IND,2.46,3.98,...,0.0,46197.0,PA,0.0,2021,7,10/24/2021,20:20:00,SF,IND
4,48485,6-5,310,Blake Hance,2.021102e+09,2590.0,33.0,CLE,1.77,3.96,...,0.0,48089.0,PP,0.0,2021,7,10/21/2021,20:20:00,CLE,DEN

In [35]:
w7_G.drop(columns=['homeTeamAbbr', 'visitorTeamAbbr','gameDate', 'gameTimeEastern', 'season'], inplace=True, errors='ignore')
w7_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,52514,6-5,345,Tyre Phillips,2.021102e+09,2055.0,16.0,BAL,1.42,4.35,...,NaN,NaN,0.0,0.0,0.0,0.0,43455.0,CL,0.0,7
1,46103,6-2,327,Will Hernandez,2.021102e+09,1148.0,29.0,NYG,2.33,4.03,...,NaN,NaN,0.0,0.0,0.0,0.0,52415.0,PP,0.0,7
2,47906,6-4,310,Ben Powers,2.021102e+09,3070.0,43.0,BAL,1.43,3.98,...,NaN,NaN,0.0,0.0,0.0,0.0,46146.0,UP,0.0,7
3,46075,6-5,330,Quenton Nelson,2.021102e+09,1752.0,35.0,IND,2.46,3.98,...,NaN,NaN,0.0,0.0,0.0,0.0,46197.0,PA,0.0,7
4,48485,6-5,310,Blake Hance,2.021102e+09,2590.0,33.0,CLE,1.77,3.96,...,NaN,NaN,1.0,0.0,0.0,0.0,48089.0,PP,0.0,7

In [36]:
w7_G.to_csv('Resources/guard_w7.csv', sep=',', index=False)

In [37]:
w7_G_df = pd.read_csv('Resources/guard_w7.csv')
w7_G_df.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,52514,6-5,345,Tyre Phillips,2.021102e+09,2055.0,16.0,BAL,1.42,4.35,...,NaN,NaN,0.0,0.0,0.0,0.0,43455.0,CL,0.0,7
1,46103,6-2,327,Will Hernandez,2.021102e+09,1148.0,29.0,NYG,2.33,4.03,...,NaN,NaN,0.0,0.0,0.0,0.0,52415.0,PP,0.0,7
2,47906,6-4,310,Ben Powers,2.021102e+09,3070.0,43.0,BAL,1.43,3.98,...,NaN,NaN,0.0,0.0,0.0,0.0,46146.0,UP,0.0,7
3,46075,6-5,330,Quenton Nelson,2.021102e+09,1752.0,35.0,IND,2.46,3.98,...,NaN,NaN,0.0,0.0,0.0,0.0,46197.0,PA,0.0,7
4,48485,6-5,310,Blake Hance,2.021102e+09,2590.0,33.0,CLE,1.77,3.96,...,NaN,NaN,1.0,0.0,0.0,0.0,48089.0,PP,0.0,7

## Tackle

In [38]:
w7_T = cleaned_T.merge(plays_df, how="left")
w7_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,42924,6-6,325,Jesse Davis,2.021102e+09,3689.0,14.0,MIA,1.60,5.22,...,NaN,66.0,NaN,"1 RB, 2 TE, 2 WR",NaN,"2 DL, 4 LB, 5 DB",NaN,1,Cover-3,Zone
1,37090,6-8,325,Nate Solder,2.021102e+09,742.0,8.0,NYG,1.47,4.99,...,NaN,22.0,SINGLEBACK,"1 RB, 1 TE, 3 WR",6.0,"3 DL, 3 LB, 5 DB",DESIGNED_ROLLOUT_RIGHT,1,Red Zone,Other
2,42924,6-6,325,Jesse Davis,2.021102e+09,557.0,36.0,MIA,1.56,4.87,...,NaN,37.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,1,Cover-2,Zone
3,46275,6-7,332,Matt Pryor,2.021102e+09,3621.0,25.0,IND,2.46,4.29,...,NaN,44.0,WILDCAT,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
4,46302,6-8,344,Jordan Mailata,2.021102e+09,3301.0,35.0,PHI,0.65,4.28,...,NaN,35.0,SHOTGUN,"1 RB, 1 TE, 3 WR",4.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Cover-3,Zone

In [39]:
w7_T.drop(columns=['possessionTeam','pff_passCoverage','pff_passCoverageType'], inplace=True, errors='ignore')
w7_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId2,foulName3,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction
0,42924,6-6,325,Jesse Davis,2.021102e+09,3689.0,14.0,MIA,1.60,5.22,...,NaN,NaN,NaN,66.0,NaN,"1 RB, 2 TE, 2 WR",NaN,"2 DL, 4 LB, 5 DB",NaN,1
1,37090,6-8,325,Nate Solder,2.021102e+09,742.0,8.0,NYG,1.47,4.99,...,NaN,NaN,NaN,22.0,SINGLEBACK,"1 RB, 1 TE, 3 WR",6.0,"3 DL, 3 LB, 5 DB",DESIGNED_ROLLOUT_RIGHT,1
2,42924,6-6,325,Jesse Davis,2.021102e+09,557.0,36.0,MIA,1.56,4.87,...,NaN,NaN,NaN,37.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,1
3,46275,6-7,332,Matt Pryor,2.021102e+09,3621.0,25.0,IND,2.46,4.29,...,NaN,NaN,NaN,44.0,WILDCAT,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0
4,46302,6-8,344,Jordan Mailata,2.021102e+09,3301.0,35.0,PHI,0.65,4.28,...,NaN,NaN,NaN,35.0,SHOTGUN,"1 RB, 1 TE, 3 WR",4.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0

In [40]:
w7_T = w7_T.merge(pff_df, how='left')
w7_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,42924,6-6,325,Jesse Davis,2.021102e+09,3689.0,14.0,MIA,1.60,5.22,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,42497.0,PP,0.0
1,37090,6-8,325,Nate Solder,2.021102e+09,742.0,8.0,NYG,1.47,4.99,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,52415.0,PA,0.0
2,42924,6-6,325,Jesse Davis,2.021102e+09,557.0,36.0,MIA,1.56,4.87,...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,46416.0,PA,0.0
3,46275,6-7,332,Matt Pryor,2.021102e+09,3621.0,25.0,IND,2.46,4.29,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,41249.0,PP,0.0
4,46302,6-8,344,Jordan Mailata,2.021102e+09,3301.0,35.0,PHI,0.65,4.28,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,47787.0,PP,0.0

In [41]:
w7_T = w7_T.merge(games_df, how='left')
w7_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,42924,6-6,325,Jesse Davis,2.021102e+09,3689.0,14.0,MIA,1.60,5.22,...,0.0,42497.0,PP,0.0,2021,7,10/24/2021,13:00:00,MIA,ATL
1,37090,6-8,325,Nate Solder,2.021102e+09,742.0,8.0,NYG,1.47,4.99,...,0.0,52415.0,PA,0.0,2021,7,10/24/2021,13:00:00,NYG,CAR
2,42924,6-6,325,Jesse Davis,2.021102e+09,557.0,36.0,MIA,1.56,4.87,...,0.0,46416.0,PA,0.0,2021,7,10/24/2021,13:00:00,MIA,ATL
3,46275,6-7,332,Matt Pryor,2.021102e+09,3621.0,25.0,IND,2.46,4.29,...,0.0,41249.0,PP,0.0,2021,7,10/24/2021,20:20:00,SF,IND
4,46302,6-8,344,Jordan Mailata,2.021102e+09,3301.0,35.0,PHI,0.65,4.28,...,0.0,47787.0,PP,0.0,2021,7,10/24/2021,16:05:00,LV,PHI

In [42]:
w7_T.drop(columns=['homeTeamAbbr', 'visitorTeamAbbr','gameDate', 'gameTimeEastern', 'season'], inplace=True, errors='ignore')
w7_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,42924,6-6,325,Jesse Davis,2.021102e+09,3689.0,14.0,MIA,1.60,5.22,...,NaN,NaN,0.0,0.0,0.0,0.0,42497.0,PP,0.0,7
1,37090,6-8,325,Nate Solder,2.021102e+09,742.0,8.0,NYG,1.47,4.99,...,NaN,NaN,0.0,0.0,0.0,0.0,52415.0,PA,0.0,7
2,42924,6-6,325,Jesse Davis,2.021102e+09,557.0,36.0,MIA,1.56,4.87,...,NaN,NaN,1.0,0.0,0.0,0.0,46416.0,PA,0.0,7
3,46275,6-7,332,Matt Pryor,2.021102e+09,3621.0,25.0,IND,2.46,4.29,...,NaN,NaN,0.0,0.0,0.0,0.0,41249.0,PP,0.0,7
4,46302,6-8,344,Jordan Mailata,2.021102e+09,3301.0,35.0,PHI,0.65,4.28,...,NaN,NaN,0.0,0.0,0.0,0.0,47787.0,PP,0.0,7

In [44]:
w7_T.to_csv('Resources/tackle_w7.csv', sep=',', index=False)

In [45]:
w7_T_df = pd.read_csv('Resources/tackle_w7.csv')
w7_T_df.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,42924,6-6,325,Jesse Davis,2.021102e+09,3689.0,14.0,MIA,1.60,5.22,...,NaN,NaN,0.0,0.0,0.0,0.0,42497.0,PP,0.0,7
1,37090,6-8,325,Nate Solder,2.021102e+09,742.0,8.0,NYG,1.47,4.99,...,NaN,NaN,0.0,0.0,0.0,0.0,52415.0,PA,0.0,7
2,42924,6-6,325,Jesse Davis,2.021102e+09,557.0,36.0,MIA,1.56,4.87,...,NaN,NaN,1.0,0.0,0.0,0.0,46416.0,PA,0.0,7
3,46275,6-7,332,Matt Pryor,2.021102e+09,3621.0,25.0,IND,2.46,4.29,...,NaN,NaN,0.0,0.0,0.0,0.0,41249.0,PP,0.0,7
4,46302,6-8,344,Jordan Mailata,2.021102e+09,3301.0,35.0,PHI,0.65,4.28,...,NaN,NaN,0.0,0.0,0.0,0.0,47787.0,PP,0.0,7