In [1]:
import csv
import os
import pandas as pd
import numpy as np

In [2]:
players_data_to_load = "Resources/players.csv"
week8_data_to_load = "Resources/week8.csv"
plays_data_to_load = "Resources/plays.csv"
pff_data_to_load = "Resources/pffScoutingData.csv"
games_data_to_load = "Resources/games.csv"

In [3]:
players_df = pd.read_csv(players_data_to_load)
players_df

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName
0,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady
1,28963,6-5,240,1982-03-02,"Miami, O.",QB,Ben Roethlisberger
2,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters
3,29851,6-2,225,1983-12-02,California,QB,Aaron Rodgers
4,30078,6-2,228,1982-11-24,Harvard,QB,Ryan Fitzpatrick
...,...,...,...,...,...,...,...
1674,53991,6-1,320,NaN,NaN,DT,Forrest Merrill
1675,53994,6-5,300,NaN,NaN,C,Ryan McCollum
1676,53999,6-4,312,NaN,NaN,DT,Jack Heflin
1677,54006,6-6,330,NaN,NaN,T,Jake Curhan
1678,54038,6-6,245,NaN,NaN,QB,Feleipe Franks

In [4]:
week8_df = pd.read_csv(week8_data_to_load)
week8_df

,gameId,playId,nflId,frameId,time,jerseyNumber,team,playDirection,x,y,s,a,dis,o,dir,event
0,2021102800,189,37077.0,1,2021-10-29T00:27:23.000,18.0,ARI,right,21.38,6.94,0.00,0.00,0.00,43.74,223.19,None
1,2021102800,189,37077.0,2,2021-10-29T00:27:23.100,18.0,ARI,right,21.38,6.94,0.00,0.00,0.00,44.67,243.81,None
2,2021102800,189,37077.0,3,2021-10-29T00:27:23.200,18.0,ARI,right,21.38,6.95,0.00,0.00,0.00,45.69,303.24,None
3,2021102800,189,37077.0,4,2021-10-29T00:27:23.300,18.0,ARI,right,21.38,6.94,0.00,0.00,0.00,46.44,285.89,None
4,2021102800,189,37077.0,5,2021-10-29T00:27:23.400,18.0,ARI,right,21.38,6.95,0.00,0.00,0.01,47.99,341.60,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
978944,2021110100,4433,NaN,54,2021-11-02T03:20:26.500,NaN,football,right,24.17,27.89,2.47,2.28,0.25,NaN,NaN,None
978945,2021110100,4433,NaN,55,2021-11-02T03:20:26.600,NaN,football,right,24.36,28.03,2.36,2.16,0.24,NaN,NaN,None
978946,2021110100,4433,NaN,56,2021-11-02T03:20:26.700,NaN,football,right,24.55,28.17,2.25,1.45,0.23,NaN,NaN,None
978947,2021110100,4433,NaN,57,2021-11-02T03:20:26.800,NaN,football,right,24.73,28.31,2.28,0.72,0.23,NaN,NaN,None
978948,2021110100,4433,NaN,58,2021-11-02T03:20:26.900,NaN,football,right,24.91,28.45,2.32,0.54,0.23,NaN,NaN,None

In [5]:
week8_players = players_df.merge(week8_df, how='left')
week8_players

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
0,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021103e+09,75.0,1.0,...,TB,right,28.85,24.15,0.00,0.00,0.00,92.16,336.03,None
1,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021103e+09,75.0,2.0,...,TB,right,28.86,24.14,0.00,0.00,0.01,92.16,343.20,None
2,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021103e+09,75.0,3.0,...,TB,right,28.86,24.14,0.00,0.00,0.01,92.99,353.61,None
3,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021103e+09,75.0,4.0,...,TB,right,28.86,24.14,0.00,0.00,0.00,93.89,1.88,None
4,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021103e+09,75.0,5.0,...,TB,right,28.86,24.14,0.00,0.00,0.00,93.89,2.75,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
936973,54038,6-6,245,NaN,NaN,QB,Feleipe Franks,2.021103e+09,2573.0,26.0,...,ATL,left,74.29,41.14,6.56,2.59,0.66,267.91,342.86,pass_forward
936974,54038,6-6,245,NaN,NaN,QB,Feleipe Franks,2.021103e+09,2573.0,27.0,...,ATL,left,74.08,41.75,6.42,2.79,0.65,265.58,339.82,None
936975,54038,6-6,245,NaN,NaN,QB,Feleipe Franks,2.021103e+09,2573.0,28.0,...,ATL,left,73.83,42.34,6.34,3.08,0.64,265.58,336.06,autoevent_passinterrupted
936976,54038,6-6,245,NaN,NaN,QB,Feleipe Franks,2.021103e+09,2573.0,29.0,...,ATL,left,73.56,42.90,6.21,3.42,0.63,262.93,332.31,None
936977,54038,6-6,245,NaN,NaN,QB,Feleipe Franks,2.021103e+09,2573.0,30.0,...,ATL,left,73.25,43.44,6.14,3.34,0.62,258.23,329.15,None

## Centers

In [6]:
week8_players_C = week8_players[week8_players['officialPosition'] == 'C']
week8_players_C.head()

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
11580,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021103e+09,62.0,1.0,...,SF,right,42.41,23.68,0.05,0.28,0.00,78.60,344.58,None
11581,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021103e+09,62.0,2.0,...,SF,right,42.40,23.68,0.07,0.24,0.01,78.60,346.70,None
11582,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021103e+09,62.0,3.0,...,SF,right,42.39,23.69,0.11,0.27,0.01,78.60,322.42,None
11583,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021103e+09,62.0,4.0,...,SF,right,42.38,23.70,0.18,0.33,0.02,78.60,310.95,None
11584,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021103e+09,62.0,5.0,...,SF,right,42.34,23.72,0.32,0.59,0.04,81.83,297.74,None

In [7]:
week8_players_C = week8_players_C[week8_players_C['event'] != 'None']
week8_players_C

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
11585,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021103e+09,62.0,6.0,...,SF,right,42.29,23.73,0.42,0.65,0.05,84.01,289.21,ball_snap
11586,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021103e+09,62.0,7.0,...,SF,right,42.24,23.74,0.52,0.65,0.05,86.40,284.23,autoevent_ballsnap
11603,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021103e+09,62.0,24.0,...,SF,right,39.26,23.40,2.41,1.01,0.25,108.76,270.66,pass_forward
11604,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021103e+09,62.0,25.0,...,SF,right,39.01,23.42,2.43,1.10,0.26,107.88,274.53,autoevent_passforward
11614,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021103e+09,84.0,6.0,...,SF,right,42.44,23.84,0.19,1.13,0.02,75.36,279.20,ball_snap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
936733,53994,6-5,300,NaN,NaN,C,Ryan McCollum,2.021103e+09,3699.0,6.0,...,DET,left,89.64,23.80,0.06,0.36,0.02,246.75,111.50,ball_snap
936778,53994,6-5,300,NaN,NaN,C,Ryan McCollum,2.021103e+09,3699.0,51.0,...,DET,left,92.27,25.42,0.87,2.55,0.09,254.49,229.27,run
936789,53994,6-5,300,NaN,NaN,C,Ryan McCollum,2.021103e+09,3737.0,6.0,...,DET,left,83.74,24.03,0.25,0.85,0.03,245.50,83.16,ball_snap
936822,53994,6-5,300,NaN,NaN,C,Ryan McCollum,2.021103e+09,3737.0,39.0,...,DET,left,89.27,24.19,0.80,1.64,0.08,303.00,23.91,autoevent_passforward
936824,53994,6-5,300,NaN,NaN,C,Ryan McCollum,2.021103e+09,3737.0,41.0,...,DET,left,89.27,24.38,0.96,1.60,0.10,305.62,349.75,autoevent_passinterrupted

In [8]:
week8_players_C = week8_players_C.sort_values('a', ascending = False)
week8_players_C

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
12211,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021103e+09,1852.0,24.0,...,SF,left,89.48,25.59,2.50,3.82,0.26,238.00,95.48,autoevent_passforward
12212,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021103e+09,1852.0,25.0,...,SF,left,89.72,25.54,2.43,3.62,0.25,228.16,105.28,pass_forward
805780,52554,6-3,320,1997-11-20,Wisconsin,C,Tyler Biadasz,2.021103e+09,1113.0,38.0,...,DAL,left,96.54,30.36,1.79,3.46,0.18,51.70,65.28,pass_forward
775056,52486,6-4,290,1997-11-17,Temple,C,Matt Hennessy,2.021103e+09,923.0,7.0,...,ATL,left,47.39,27.11,0.75,3.42,0.06,223.46,174.42,ball_snap
326237,43433,6-4,306,1993-04-27,Missouri,C,Connor McGovern,2.021103e+09,3869.0,37.0,...,NYJ,left,28.49,26.99,1.16,3.41,0.11,258.87,314.63,autoevent_passforward
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
706763,48512,6-4,300,1997-02-14,Penn State,C,Ryan Bates,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
834338,52894,6-4,315,1998-03-23,Missouri,C,Trystan Colon,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839737,53063,6-3,270,1997-10-28,Texas State,C,Aaron Brewer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
883774,53491,6-5,312,NaN,NaN,C,Josh Myers,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
905816,53543,6-3,300,NaN,NaN,C,Drew Dalman,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
week8_players_C = week8_players_C.dropna()

In [10]:
cleaned_C= week8_players_C[['nflId', 'height', 'weight', 'displayName', 'gameId', 'playId', 'frameId', 'team', 's', 'a', 'dis', 'event']]
cleaned_C

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,dis,event
12211,34472,6-4,311,Alex Mack,2.021103e+09,1852.0,24.0,SF,2.50,3.82,0.26,autoevent_passforward
12212,34472,6-4,311,Alex Mack,2.021103e+09,1852.0,25.0,SF,2.43,3.62,0.25,pass_forward
805780,52554,6-3,320,Tyler Biadasz,2.021103e+09,1113.0,38.0,DAL,1.79,3.46,0.18,pass_forward
775056,52486,6-4,290,Matt Hennessy,2.021103e+09,923.0,7.0,ATL,0.75,3.42,0.06,ball_snap
326237,43433,6-4,306,Connor McGovern,2.021103e+09,3869.0,37.0,NYJ,1.16,3.41,0.11,autoevent_passforward
...,...,...,...,...,...,...,...,...,...,...,...,...
114868,40151,6-4,319,Ryan Jensen,2.021103e+09,408.0,6.0,TB,0.00,0.00,0.01,ball_snap
612464,47801,6-3,305,Garrett Bradbury,2.021103e+09,4317.0,46.0,MIN,0.00,0.00,0.00,line_set
805748,52554,6-3,320,Tyler Biadasz,2.021103e+09,1113.0,6.0,DAL,0.00,0.00,0.01,autoevent_ballsnap
115196,40151,6-4,319,Ryan Jensen,2.021103e+09,1372.0,6.0,TB,0.00,0.00,0.04,ball_snap
107947,40070,6-4,307,J.C. Tretter,2.021103e+09,3594.0,7.0,CLE,0.00,0.00,0.01,ball_snap

## Guards

In [11]:
week8_players_G = week8_players[week8_players['officialPosition'] == 'G']
week8_players_G

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
23023,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021103e+09,434.0,1.0,...,TEN,right,36.83,31.49,0.04,0.12,0.00,97.21,6.60,None
23024,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021103e+09,434.0,2.0,...,TEN,right,36.84,31.49,0.09,0.27,0.02,98.48,86.00,None
23025,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021103e+09,434.0,3.0,...,TEN,right,36.86,31.49,0.16,0.36,0.02,96.35,92.18,None
23026,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021103e+09,434.0,4.0,...,TEN,right,36.89,31.49,0.27,0.48,0.03,94.96,83.47,None
23027,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021103e+09,434.0,5.0,...,TEN,right,36.94,31.51,0.44,0.62,0.05,88.27,78.57,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
936350,53954,6-5,319,NaN,NaN,G,Tommy Kraemer,2.021103e+09,3737.0,40.0,...,DET,left,92.23,26.36,1.29,3.23,0.13,248.27,29.77,None
936351,53954,6-5,319,NaN,NaN,G,Tommy Kraemer,2.021103e+09,3737.0,41.0,...,DET,left,92.26,26.51,1.47,3.16,0.15,259.84,10.99,autoevent_passinterrupted
936352,53954,6-5,319,NaN,NaN,G,Tommy Kraemer,2.021103e+09,3737.0,42.0,...,DET,left,92.24,26.69,1.80,2.99,0.19,268.49,355.89,None
936353,53954,6-5,319,NaN,NaN,G,Tommy Kraemer,2.021103e+09,3737.0,43.0,...,DET,left,92.19,26.90,2.13,3.01,0.21,273.84,345.28,None
936354,53954,6-5,319,NaN,NaN,G,Tommy Kraemer,2.021103e+09,3737.0,44.0,...,DET,left,92.11,27.13,2.46,2.82,0.24,279.98,338.63,None

In [12]:
week8_players_G = week8_players_G[week8_players_G['event'] != 'None']
week8_players_G

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
23028,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021103e+09,434.0,6.0,...,TEN,right,37.01,31.54,0.61,0.74,0.07,88.27,69.57,ball_snap
23044,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021103e+09,434.0,22.0,...,TEN,right,36.91,31.84,0.98,0.51,0.10,91.66,232.37,play_action
23059,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021103e+09,434.0,37.0,...,TEN,right,36.01,30.03,2.66,1.72,0.28,167.26,207.12,pass_forward
23070,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021103e+09,584.0,6.0,...,TEN,right,37.51,25.38,0.15,0.19,0.02,62.68,286.01,ball_snap
23071,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021103e+09,584.0,7.0,...,TEN,right,37.49,25.39,0.17,0.25,0.02,63.27,296.09,autoevent_ballsnap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
936260,53954,6-5,319,NaN,NaN,G,Tommy Kraemer,2.021103e+09,3699.0,6.0,...,DET,left,89.86,25.32,0.09,0.50,0.01,258.35,140.35,ball_snap
936305,53954,6-5,319,NaN,NaN,G,Tommy Kraemer,2.021103e+09,3699.0,51.0,...,DET,left,94.43,25.10,2.10,0.25,0.21,264.12,249.15,run
936316,53954,6-5,319,NaN,NaN,G,Tommy Kraemer,2.021103e+09,3737.0,6.0,...,DET,left,84.22,25.40,0.08,0.41,0.01,255.94,75.82,ball_snap
936349,53954,6-5,319,NaN,NaN,G,Tommy Kraemer,2.021103e+09,3737.0,39.0,...,DET,left,92.15,26.25,1.27,3.42,0.14,241.05,48.43,autoevent_passforward
936351,53954,6-5,319,NaN,NaN,G,Tommy Kraemer,2.021103e+09,3737.0,41.0,...,DET,left,92.26,26.51,1.47,3.16,0.15,259.84,10.99,autoevent_passinterrupted

In [13]:
week8_players_G = week8_players_G.sort_values('a', ascending = False)

In [14]:
week8_players_G = week8_players_G.dropna()

In [15]:
cleaned_G = week8_players_G[['nflId', 'height', 'weight', 'displayName', 'gameId', 'playId', 'frameId', 'team', 's', 'a', 'dis', 'event']]
cleaned_G

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,dis,event
132647,41242,6-4,315,Zack Martin,2.021103e+09,2860.0,6.0,DAL,0.98,4.57,0.08,ball_snap
23221,35472,6-5,325,Rodger Saffold,2.021103e+09,907.0,33.0,TEN,0.73,4.36,0.09,pass_arrived
635303,47838,6-6,325,Max Scharping,2.021103e+09,2596.0,13.0,HOU,1.57,4.10,0.14,fumble
607886,47797,6-4,307,Chris Lindstrom,2.021103e+09,923.0,7.0,ATL,0.76,4.03,0.06,ball_snap
472887,46075,6-5,330,Quenton Nelson,2.021103e+09,4603.0,29.0,IND,1.84,3.97,0.20,play_action
...,...,...,...,...,...,...,...,...,...,...,...,...
150525,41310,6-3,336,Gabe Jackson,2.021103e+09,1766.0,6.0,SEA,0.00,0.00,0.00,ball_snap
772649,52480,6-7,310,Josh Jones,2.021103e+09,3862.0,6.0,ARI,0.00,0.00,0.00,autoevent_ballsnap
634837,47838,6-6,325,Max Scharping,2.021103e+09,1547.0,6.0,HOU,0.00,0.00,0.01,ball_snap
772650,52480,6-7,310,Josh Jones,2.021103e+09,3862.0,7.0,ARI,0.00,0.00,0.00,ball_snap
672456,47952,6-6,308,David Edwards,2.021103e+09,142.0,6.0,LA,0.00,0.00,0.01,autoevent_ballsnap

## Tackles

In [16]:
week8_players_T = week8_players[week8_players['officialPosition'] == 'T']
week8_players_T

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
2535,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021103e+09,377.0,1.0,...,CHI,left,74.56,26.78,0.22,0.32,0.02,278.71,123.36,None
2536,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021103e+09,377.0,2.0,...,CHI,left,74.59,26.76,0.25,0.24,0.03,284.09,120.57,None
2537,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021103e+09,377.0,3.0,...,CHI,left,74.59,26.75,0.20,0.07,0.02,292.48,133.33,None
2538,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021103e+09,377.0,4.0,...,CHI,left,74.58,26.74,0.13,0.36,0.01,300.22,162.39,None
2539,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021103e+09,377.0,5.0,...,CHI,left,74.57,26.74,0.07,0.59,0.01,310.32,217.58,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
933821,53868,6-6,315,NaN,NaN,T,Alaric Jackson,2.021103e+09,3393.0,27.0,...,LA,right,16.38,21.12,3.53,1.56,0.36,131.28,297.54,None
933822,53868,6-6,315,NaN,NaN,T,Alaric Jackson,2.021103e+09,3393.0,28.0,...,LA,right,16.08,21.29,3.35,2.06,0.34,133.61,300.03,None
933823,53868,6-6,315,NaN,NaN,T,Alaric Jackson,2.021103e+09,3393.0,29.0,...,LA,right,15.81,21.47,3.14,2.39,0.32,141.70,302.69,None
933824,53868,6-6,315,NaN,NaN,T,Alaric Jackson,2.021103e+09,3393.0,30.0,...,LA,right,15.56,21.63,2.87,2.61,0.30,146.12,304.37,None
936829,54006,6-6,330,NaN,NaN,T,Jake Curhan,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
week8_players_T = week8_players_T[week8_players_T['event'] != 'None']
week8_players_T

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
2540,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021103e+09,377.0,6.0,...,CHI,left,74.56,26.76,0.19,0.86,0.03,309.26,305.95,ball_snap
2554,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021103e+09,377.0,20.0,...,CHI,left,73.73,30.26,4.58,0.67,0.48,348.27,353.84,play_action
2584,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021103e+09,377.0,50.0,...,CHI,left,73.41,36.43,1.24,0.39,0.13,199.51,199.56,run
2595,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021103e+09,398.0,6.0,...,CHI,left,70.98,20.51,0.25,0.13,0.04,331.04,141.03,ball_snap
2623,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021103e+09,398.0,34.0,...,CHI,left,76.93,21.67,2.12,1.73,0.22,219.72,53.11,pass_forward
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
933751,53868,6-6,315,NaN,NaN,T,Alaric Jackson,2.021103e+09,3029.0,7.0,...,LA,right,22.67,20.67,0.35,1.86,0.03,70.43,216.73,autoevent_ballsnap
933789,53868,6-6,315,NaN,NaN,T,Alaric Jackson,2.021103e+09,3029.0,45.0,...,LA,right,15.97,24.71,1.45,2.30,0.15,325.05,312.07,qb_sack
933800,53868,6-6,315,NaN,NaN,T,Alaric Jackson,2.021103e+09,3393.0,6.0,...,LA,right,20.54,20.56,0.19,1.09,0.02,68.78,225.00,ball_snap
933819,53868,6-6,315,NaN,NaN,T,Alaric Jackson,2.021103e+09,3393.0,25.0,...,LA,right,17.03,20.80,3.69,0.97,0.37,128.82,294.86,pass_forward
936829,54006,6-6,330,NaN,NaN,T,Jake Curhan,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
week8_players_T = week8_players_T.sort_values('a', ascending = False)

In [19]:
week8_players_T = week8_players_T.dropna()

In [20]:
cleaned_T = week8_players_T[['nflId', 'height', 'weight', 'displayName', 'gameId', 'playId', 'frameId', 'team', 's', 'a', 'dis', 'event']]
cleaned_T

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,dis,event
835781,52938,6-6,310,Terence Steele,2.021103e+09,2860.0,6.0,DAL,0.75,5.29,0.06,ball_snap
523893,46152,6-8,345,Orlando Brown,2.021110e+09,797.0,45.0,KC,0.39,4.81,0.04,pass_forward
100922,40023,6-5,304,Terron Armstead,2.021103e+09,2098.0,14.0,NO,1.14,4.67,0.10,play_action
147920,41296,6-5,310,Billy Turner,2.021103e+09,368.0,19.0,GB,2.34,4.64,0.24,play_action
523892,46152,6-8,345,Orlando Brown,2.021110e+09,797.0,44.0,KC,0.55,4.59,0.06,autoevent_passforward
...,...,...,...,...,...,...,...,...,...,...,...,...
328999,43447,6-5,324,Brandon Shell,2.021103e+09,1808.0,7.0,SEA,0.00,0.00,0.01,autoevent_ballsnap
328998,43447,6-5,324,Brandon Shell,2.021103e+09,1808.0,6.0,SEA,0.00,0.00,0.02,ball_snap
328954,43447,6-5,324,Brandon Shell,2.021103e+09,1766.0,6.0,SEA,0.00,0.00,0.00,ball_snap
727275,52426,6-6,310,Austin Jackson,2.021103e+09,184.0,6.0,MIA,0.00,0.00,0.01,ball_snap
229002,42445,6-6,330,Daryl Williams,2.021103e+09,2813.0,5.0,BUF,0.00,0.00,0.01,man_in_motion

## Plays, PFF, & Games data added

In [21]:
plays_df = pd.read_csv(plays_data_to_load)
plays_df

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,defensiveTeam,yardlineSide,yardlineNumber,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,2021090900,97,(13:33) (Shotgun) T.Brady pass incomplete deep...,1,3,2,TB,DAL,TB,33,...,NaN,43.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
1,2021090900,137,(13:18) (Shotgun) D.Prescott pass deep left to...,1,1,10,DAL,TB,DAL,2,...,NaN,108.0,EMPTY,"1 RB, 2 TE, 2 WR",6.0,"4 DL, 4 LB, 3 DB",TRADITIONAL,0,Cover-3,Zone
2,2021090900,187,(12:23) (Shotgun) D.Prescott pass short middle...,1,2,6,DAL,TB,DAL,34,...,NaN,76.0,SHOTGUN,"0 RB, 2 TE, 3 WR",6.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,0,Cover-3,Zone
3,2021090900,282,(9:56) D.Prescott pass incomplete deep left to...,1,1,10,DAL,TB,TB,39,...,NaN,49.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",6.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1,Cover-3,Zone
4,2021090900,349,(9:46) (Shotgun) D.Prescott pass incomplete sh...,1,3,15,DAL,TB,TB,44,...,NaN,54.0,SHOTGUN,"1 RB, 1 TE, 3 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,0,Cover-3,Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8552,2021110100,4310,(1:56) (Shotgun) P.Mahomes sacked at NYG 16 fo...,4,3,8,KC,NYG,NYG,8,...,NaN,18.0,SHOTGUN,"1 RB, 1 TE, 3 WR",4.0,"1 DL, 3 LB, 7 DB",SCRAMBLE,0,Bracket,Other
8553,2021110100,4363,(1:07) (Shotgun) D.Jones pass short right to E...,4,1,10,NYG,KC,NYG,25,...,NaN,35.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"4 DL, 1 LB, 6 DB",SCRAMBLE,0,Cover-2,Zone
8554,2021110100,4392,"(1:01) (No Huddle, Shotgun) D.Jones sacked at ...",4,2,7,NYG,KC,NYG,28,...,NaN,38.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Cover-2,Zone
8555,2021110100,4411,"(:39) (No Huddle, Shotgun) D.Jones pass incomp...",4,3,15,NYG,KC,NYG,20,...,NaN,30.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Cover-2,Zone
8556,2021110100,4433,(:35) (Shotgun) D.Jones sacked at NYG 14 for -...,4,4,15,NYG,KC,NYG,20,...,NaN,30.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Quarters,Zone

In [22]:
pff_df = pd.read_csv(pff_data_to_load)
pff_df

,gameId,playId,nflId,pff_role,pff_positionLinedUp,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,2021090900,97,25511,Pass,QB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021090900,97,35481,Pass Route,TE-L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021090900,97,35634,Pass Route,LWR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021090900,97,39985,Pass Route,HB-R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021090900,97,40151,Pass Block,C,NaN,NaN,NaN,0.0,0.0,0.0,0.0,44955.0,SW,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188249,2021110100,4433,52507,Pass Block,LT,NaN,NaN,NaN,0.0,0.0,1.0,0.0,43338.0,PP,0.0
188250,2021110100,4433,52546,Coverage,SCBoR,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188251,2021110100,4433,52573,Pass Route,SLoWR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188252,2021110100,4433,52585,Pass Rush,LEO,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188253,2021110100,4433,53449,Pass Route,LWR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
games_df = pd.read_csv(games_data_to_load)
games_df

,gameId,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,2021090900,2021,1,09/09/2021,20:20:00,TB,DAL
1,2021091200,2021,1,09/12/2021,13:00:00,ATL,PHI
2,2021091201,2021,1,09/12/2021,13:00:00,BUF,PIT
3,2021091202,2021,1,09/12/2021,13:00:00,CAR,NYJ
4,2021091203,2021,1,09/12/2021,13:00:00,CIN,MIN
...,...,...,...,...,...,...,...
117,2021103109,2021,8,10/31/2021,16:05:00,SEA,JAX
118,2021103110,2021,8,10/31/2021,16:25:00,DEN,WAS
119,2021103111,2021,8,10/31/2021,16:25:00,NO,TB
120,2021103112,2021,8,10/31/2021,20:20:00,MIN,DAL
121,2021110100,2021,8,11/01/2021,20:15:00,KC,NYG

# Merging all data & Cleaning

## Center

In [24]:
w8_C = cleaned_C.merge(plays_df, how="left")
w8_C.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,34472,6-4,311,Alex Mack,2.021103e+09,1852.0,24.0,SF,2.50,3.82,...,NaN,85.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",TRADITIONAL,0,Cover-3,Zone
1,34472,6-4,311,Alex Mack,2.021103e+09,1852.0,25.0,SF,2.43,3.62,...,NaN,85.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",TRADITIONAL,0,Cover-3,Zone
2,52554,6-3,320,Tyler Biadasz,2.021103e+09,1113.0,38.0,DAL,1.79,3.46,...,NaN,88.0,SHOTGUN,"1 RB, 1 TE, 3 WR",7.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Quarters,Zone
3,52486,6-4,290,Matt Hennessy,2.021103e+09,923.0,7.0,ATL,0.75,3.42,...,NaN,47.0,SINGLEBACK,"2 RB, 2 TE, 1 WR",7.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,1,Cover-3,Zone
4,43433,6-4,306,Connor McGovern,2.021103e+09,3869.0,37.0,NYJ,1.16,3.41,...,NaN,23.0,EMPTY,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-3,Zone

In [25]:
w8_C.drop(columns=[['possessionTeam','pff_passCoverage','pff_passCoverageType']], inplace=True, errors='ignore')

In [26]:
w8_C = w8_C.merge(pff_df, how='left')
w8_C.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,34472,6-4,311,Alex Mack,2.021103e+09,1852.0,24.0,SF,2.50,3.82,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,46214.0,PP,0.0
1,34472,6-4,311,Alex Mack,2.021103e+09,1852.0,25.0,SF,2.43,3.62,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,46214.0,PP,0.0
2,52554,6-3,320,Tyler Biadasz,2.021103e+09,1113.0,38.0,DAL,1.79,3.46,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,47973.0,SW,0.0
3,52486,6-4,290,Matt Hennessy,2.021103e+09,923.0,7.0,ATL,0.75,3.42,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,52415.0,PA,0.0
4,43433,6-4,306,Connor McGovern,2.021103e+09,3869.0,37.0,NYJ,1.16,3.41,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,44915.0,PP,0.0

In [27]:
w8_C = w8_C.merge(games_df, how='left')
w8_C.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,34472,6-4,311,Alex Mack,2.021103e+09,1852.0,24.0,SF,2.50,3.82,...,0.0,46214.0,PP,0.0,2021,8,10/31/2021,13:00:00,CHI,SF
1,34472,6-4,311,Alex Mack,2.021103e+09,1852.0,25.0,SF,2.43,3.62,...,0.0,46214.0,PP,0.0,2021,8,10/31/2021,13:00:00,CHI,SF
2,52554,6-3,320,Tyler Biadasz,2.021103e+09,1113.0,38.0,DAL,1.79,3.46,...,0.0,47973.0,SW,0.0,2021,8,10/31/2021,20:20:00,MIN,DAL
3,52486,6-4,290,Matt Hennessy,2.021103e+09,923.0,7.0,ATL,0.75,3.42,...,0.0,52415.0,PA,0.0,2021,8,10/31/2021,13:00:00,ATL,CAR
4,43433,6-4,306,Connor McGovern,2.021103e+09,3869.0,37.0,NYJ,1.16,3.41,...,0.0,44915.0,PP,0.0,2021,8,10/31/2021,13:00:00,NYJ,CIN

In [28]:
w8_C.drop(columns=['homeTeamAbbr', 'visitorTeamAbbr','gameDate', 'gameTimeEastern', 'season'], inplace=True, errors='ignore')
w8_C

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,34472,6-4,311,Alex Mack,2.021103e+09,1852.0,24.0,SF,2.50,3.82,...,NaN,NaN,0.0,0.0,0.0,0.0,46214.0,PP,0.0,8
1,34472,6-4,311,Alex Mack,2.021103e+09,1852.0,25.0,SF,2.43,3.62,...,NaN,NaN,0.0,0.0,0.0,0.0,46214.0,PP,0.0,8
2,52554,6-3,320,Tyler Biadasz,2.021103e+09,1113.0,38.0,DAL,1.79,3.46,...,NaN,NaN,0.0,0.0,1.0,0.0,47973.0,SW,0.0,8
3,52486,6-4,290,Matt Hennessy,2.021103e+09,923.0,7.0,ATL,0.75,3.42,...,NaN,NaN,0.0,0.0,0.0,0.0,52415.0,PA,0.0,8
4,43433,6-4,306,Connor McGovern,2.021103e+09,3869.0,37.0,NYJ,1.16,3.41,...,NaN,NaN,0.0,0.0,0.0,0.0,44915.0,PP,0.0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3051,40151,6-4,319,Ryan Jensen,2.021103e+09,408.0,6.0,TB,0.00,0.00,...,NaN,NaN,0.0,0.0,0.0,0.0,43409.0,PP,0.0,8
3052,47801,6-3,305,Garrett Bradbury,2.021103e+09,4317.0,46.0,MIN,0.00,0.00,...,NaN,NaN,0.0,0.0,0.0,0.0,44892.0,PP,0.0,8
3053,52554,6-3,320,Tyler Biadasz,2.021103e+09,1113.0,6.0,DAL,0.00,0.00,...,NaN,NaN,0.0,0.0,1.0,0.0,47973.0,SW,0.0,8
3054,40151,6-4,319,Ryan Jensen,2.021103e+09,1372.0,6.0,TB,0.00,0.00,...,NaN,NaN,1.0,0.0,0.0,0.0,42553.0,PP,0.0,8
3055,40070,6-4,307,J.C. Tretter,2.021103e+09,3594.0,7.0,CLE,0.00,0.00,...,NaN,NaN,0.0,0.0,0.0,0.0,37104.0,PP,0.0,8

In [29]:
w8_C.to_csv('Resources/center_w8.csv', sep=',', index=False)

In [30]:
w8_C_df = pd.read_csv('Resources/center_w8.csv')
w8_C_df.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,34472,6-4,311,Alex Mack,2.021103e+09,1852.0,24.0,SF,2.50,3.82,...,NaN,NaN,0.0,0.0,0.0,0.0,46214.0,PP,0.0,8
1,34472,6-4,311,Alex Mack,2.021103e+09,1852.0,25.0,SF,2.43,3.62,...,NaN,NaN,0.0,0.0,0.0,0.0,46214.0,PP,0.0,8
2,52554,6-3,320,Tyler Biadasz,2.021103e+09,1113.0,38.0,DAL,1.79,3.46,...,NaN,NaN,0.0,0.0,1.0,0.0,47973.0,SW,0.0,8
3,52486,6-4,290,Matt Hennessy,2.021103e+09,923.0,7.0,ATL,0.75,3.42,...,NaN,NaN,0.0,0.0,0.0,0.0,52415.0,PA,0.0,8
4,43433,6-4,306,Connor McGovern,2.021103e+09,3869.0,37.0,NYJ,1.16,3.41,...,NaN,NaN,0.0,0.0,0.0,0.0,44915.0,PP,0.0,8

## Guard

In [31]:
w8_G = cleaned_G.merge(plays_df, how="left")
w8_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,41242,6-4,315,Zack Martin,2.021103e+09,2860.0,6.0,DAL,0.98,4.57,...,NaN,82.0,SINGLEBACK,"1 RB, 1 TE, 3 WR",7.0,"4 DL, 2 LB, 5 DB",NaN,1,Cover-1,Man
1,35472,6-5,325,Rodger Saffold,2.021103e+09,907.0,33.0,TEN,0.73,4.36,...,NaN,67.0,EMPTY,"1 RB, 1 TE, 3 WR",5.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
2,47838,6-6,325,Max Scharping,2.021103e+09,2596.0,13.0,HOU,1.57,4.10,...,NaN,29.0,SHOTGUN,"2 RB, 0 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",SCRAMBLE,0,Cover-3,Zone
3,47797,6-4,307,Chris Lindstrom,2.021103e+09,923.0,7.0,ATL,0.76,4.03,...,NaN,47.0,SINGLEBACK,"2 RB, 2 TE, 1 WR",7.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,1,Cover-3,Zone
4,46075,6-5,330,Quenton Nelson,2.021103e+09,4603.0,29.0,IND,1.84,3.97,...,NaN,95.0,SINGLEBACK,"1 RB, 1 TE, 3 WR",6.0,"3 DL, 3 LB, 5 DB",DESIGNED_ROLLOUT_RIGHT,1,Cover-3,Zone

In [32]:
w8_G.drop(columns=[['possessionTeam','pff_passCoverage','pff_passCoverageType']], inplace=True, errors='ignore')
w8_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,41242,6-4,315,Zack Martin,2.021103e+09,2860.0,6.0,DAL,0.98,4.57,...,NaN,82.0,SINGLEBACK,"1 RB, 1 TE, 3 WR",7.0,"4 DL, 2 LB, 5 DB",NaN,1,Cover-1,Man
1,35472,6-5,325,Rodger Saffold,2.021103e+09,907.0,33.0,TEN,0.73,4.36,...,NaN,67.0,EMPTY,"1 RB, 1 TE, 3 WR",5.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
2,47838,6-6,325,Max Scharping,2.021103e+09,2596.0,13.0,HOU,1.57,4.10,...,NaN,29.0,SHOTGUN,"2 RB, 0 TE, 3 WR",6.0,"2 DL, 3 LB, 6 DB",SCRAMBLE,0,Cover-3,Zone
3,47797,6-4,307,Chris Lindstrom,2.021103e+09,923.0,7.0,ATL,0.76,4.03,...,NaN,47.0,SINGLEBACK,"2 RB, 2 TE, 1 WR",7.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,1,Cover-3,Zone
4,46075,6-5,330,Quenton Nelson,2.021103e+09,4603.0,29.0,IND,1.84,3.97,...,NaN,95.0,SINGLEBACK,"1 RB, 1 TE, 3 WR",6.0,"3 DL, 3 LB, 5 DB",DESIGNED_ROLLOUT_RIGHT,1,Cover-3,Zone

In [33]:
w8_G = w8_G.merge(pff_df, how='left')
w8_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,41242,6-4,315,Zack Martin,2.021103e+09,2860.0,6.0,DAL,0.98,4.57,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,44867.0,PT,0.0
1,35472,6-5,325,Rodger Saffold,2.021103e+09,907.0,33.0,TEN,0.73,4.36,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,47892.0,PP,0.0
2,47838,6-6,325,Max Scharping,2.021103e+09,2596.0,13.0,HOU,1.57,4.10,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,47917.0,PP,0.0
3,47797,6-4,307,Chris Lindstrom,2.021103e+09,923.0,7.0,ATL,0.76,4.03,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,52592.0,PA,0.0
4,46075,6-5,330,Quenton Nelson,2.021103e+09,4603.0,29.0,IND,1.84,3.97,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,46110.0,CL,0.0

In [34]:
w8_G = w8_G.merge(games_df, how='left')
w8_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,41242,6-4,315,Zack Martin,2.021103e+09,2860.0,6.0,DAL,0.98,4.57,...,0.0,44867.0,PT,0.0,2021,8,10/31/2021,20:20:00,MIN,DAL
1,35472,6-5,325,Rodger Saffold,2.021103e+09,907.0,33.0,TEN,0.73,4.36,...,0.0,47892.0,PP,0.0,2021,8,10/31/2021,13:00:00,IND,TEN
2,47838,6-6,325,Max Scharping,2.021103e+09,2596.0,13.0,HOU,1.57,4.10,...,0.0,47917.0,PP,0.0,2021,8,10/31/2021,13:00:00,HOU,LA
3,47797,6-4,307,Chris Lindstrom,2.021103e+09,923.0,7.0,ATL,0.76,4.03,...,0.0,52592.0,PA,0.0,2021,8,10/31/2021,13:00:00,ATL,CAR
4,46075,6-5,330,Quenton Nelson,2.021103e+09,4603.0,29.0,IND,1.84,3.97,...,0.0,46110.0,CL,0.0,2021,8,10/31/2021,13:00:00,IND,TEN

In [35]:
w8_G.drop(columns=['homeTeamAbbr', 'visitorTeamAbbr','gameDate', 'gameTimeEastern', 'season'], inplace=True, errors='ignore')
w8_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,41242,6-4,315,Zack Martin,2.021103e+09,2860.0,6.0,DAL,0.98,4.57,...,NaN,NaN,0.0,0.0,0.0,0.0,44867.0,PT,0.0,8
1,35472,6-5,325,Rodger Saffold,2.021103e+09,907.0,33.0,TEN,0.73,4.36,...,NaN,NaN,0.0,0.0,0.0,0.0,47892.0,PP,0.0,8
2,47838,6-6,325,Max Scharping,2.021103e+09,2596.0,13.0,HOU,1.57,4.10,...,NaN,NaN,0.0,0.0,0.0,0.0,47917.0,PP,0.0,8
3,47797,6-4,307,Chris Lindstrom,2.021103e+09,923.0,7.0,ATL,0.76,4.03,...,NaN,NaN,0.0,0.0,0.0,0.0,52592.0,PA,0.0,8
4,46075,6-5,330,Quenton Nelson,2.021103e+09,4603.0,29.0,IND,1.84,3.97,...,NaN,NaN,0.0,0.0,0.0,0.0,46110.0,CL,0.0,8

In [36]:
w8_G.to_csv('Resources/guard_w8.csv', sep=',', index=False)

In [37]:
w8_G_df = pd.read_csv('Resources/guard_w8.csv')
w8_G_df.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,41242,6-4,315,Zack Martin,2.021103e+09,2860.0,6.0,DAL,0.98,4.57,...,NaN,NaN,0.0,0.0,0.0,0.0,44867.0,PT,0.0,8
1,35472,6-5,325,Rodger Saffold,2.021103e+09,907.0,33.0,TEN,0.73,4.36,...,NaN,NaN,0.0,0.0,0.0,0.0,47892.0,PP,0.0,8
2,47838,6-6,325,Max Scharping,2.021103e+09,2596.0,13.0,HOU,1.57,4.10,...,NaN,NaN,0.0,0.0,0.0,0.0,47917.0,PP,0.0,8
3,47797,6-4,307,Chris Lindstrom,2.021103e+09,923.0,7.0,ATL,0.76,4.03,...,NaN,NaN,0.0,0.0,0.0,0.0,52592.0,PA,0.0,8
4,46075,6-5,330,Quenton Nelson,2.021103e+09,4603.0,29.0,IND,1.84,3.97,...,NaN,NaN,0.0,0.0,0.0,0.0,46110.0,CL,0.0,8

## Tackle

In [38]:
w8_T = cleaned_T.merge(plays_df, how="left")
w8_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,52938,6-6,310,Terence Steele,2.021103e+09,2860.0,6.0,DAL,0.75,5.29,...,NaN,82.0,SINGLEBACK,"1 RB, 1 TE, 3 WR",7.0,"4 DL, 2 LB, 5 DB",NaN,1,Cover-1,Man
1,46152,6-8,345,Orlando Brown,2.021110e+09,797.0,45.0,KC,0.39,4.81,...,NaN,45.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"2 DL, 3 LB, 6 DB",TRADITIONAL,0,Cover-3,Zone
2,40023,6-5,304,Terron Armstead,2.021103e+09,2098.0,14.0,NO,1.14,4.67,...,NaN,109.0,I_FORM,"6 OL, 2 RB, 2 TE, 0 WR",9.0,"4 DL, 3 LB, 4 DB",DESIGNED_ROLLOUT_LEFT,0,Goal Line,Other
3,41296,6-5,310,Billy Turner,2.021103e+09,368.0,19.0,GB,2.34,4.64,...,NaN,88.0,SINGLEBACK,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,1,Cover-2,Zone
4,46152,6-8,345,Orlando Brown,2.021110e+09,797.0,44.0,KC,0.55,4.59,...,NaN,45.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"2 DL, 3 LB, 6 DB",TRADITIONAL,0,Cover-3,Zone

In [39]:
w8_T.drop(columns=['possessionTeam','pff_passCoverage','pff_passCoverageType'], inplace=True, errors='ignore')
w8_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId2,foulName3,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction
0,52938,6-6,310,Terence Steele,2.021103e+09,2860.0,6.0,DAL,0.75,5.29,...,NaN,NaN,NaN,82.0,SINGLEBACK,"1 RB, 1 TE, 3 WR",7.0,"4 DL, 2 LB, 5 DB",NaN,1
1,46152,6-8,345,Orlando Brown,2.021110e+09,797.0,45.0,KC,0.39,4.81,...,NaN,NaN,NaN,45.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"2 DL, 3 LB, 6 DB",TRADITIONAL,0
2,40023,6-5,304,Terron Armstead,2.021103e+09,2098.0,14.0,NO,1.14,4.67,...,NaN,NaN,NaN,109.0,I_FORM,"6 OL, 2 RB, 2 TE, 0 WR",9.0,"4 DL, 3 LB, 4 DB",DESIGNED_ROLLOUT_LEFT,0
3,41296,6-5,310,Billy Turner,2.021103e+09,368.0,19.0,GB,2.34,4.64,...,NaN,NaN,NaN,88.0,SINGLEBACK,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,1
4,46152,6-8,345,Orlando Brown,2.021110e+09,797.0,44.0,KC,0.55,4.59,...,NaN,NaN,NaN,45.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"2 DL, 3 LB, 6 DB",TRADITIONAL,0

In [40]:
w8_T = w8_T.merge(pff_df, how='left')
w8_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,52938,6-6,310,Terence Steele,2.021103e+09,2860.0,6.0,DAL,0.75,5.29,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,44867.0,PA,0.0
1,46152,6-8,345,Orlando Brown,2.021110e+09,797.0,45.0,KC,0.39,4.81,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,53479.0,PP,0.0
2,40023,6-5,304,Terron Armstead,2.021103e+09,2098.0,14.0,NO,1.14,4.67,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,35441.0,PA,0.0
3,41296,6-5,310,Billy Turner,2.021103e+09,368.0,19.0,GB,2.34,4.64,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,42401.0,PP,0.0
4,46152,6-8,345,Orlando Brown,2.021110e+09,797.0,44.0,KC,0.55,4.59,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,53479.0,PP,0.0

In [41]:
w8_T = w8_T.merge(games_df, how='left')
w8_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,52938,6-6,310,Terence Steele,2.021103e+09,2860.0,6.0,DAL,0.75,5.29,...,0.0,44867.0,PA,0.0,2021,8,10/31/2021,20:20:00,MIN,DAL
1,46152,6-8,345,Orlando Brown,2.021110e+09,797.0,45.0,KC,0.39,4.81,...,0.0,53479.0,PP,0.0,2021,8,11/01/2021,20:15:00,KC,NYG
2,40023,6-5,304,Terron Armstead,2.021103e+09,2098.0,14.0,NO,1.14,4.67,...,0.0,35441.0,PA,0.0,2021,8,10/31/2021,16:25:00,NO,TB
3,41296,6-5,310,Billy Turner,2.021103e+09,368.0,19.0,GB,2.34,4.64,...,0.0,42401.0,PP,0.0,2021,8,10/28/2021,20:20:00,ARI,GB
4,46152,6-8,345,Orlando Brown,2.021110e+09,797.0,44.0,KC,0.55,4.59,...,0.0,53479.0,PP,0.0,2021,8,11/01/2021,20:15:00,KC,NYG

In [42]:
w8_T.drop(columns=['homeTeamAbbr', 'visitorTeamAbbr','gameDate', 'gameTimeEastern', 'season'], inplace=True, errors='ignore')
w8_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,52938,6-6,310,Terence Steele,2.021103e+09,2860.0,6.0,DAL,0.75,5.29,...,NaN,NaN,0.0,0.0,0.0,0.0,44867.0,PA,0.0,8
1,46152,6-8,345,Orlando Brown,2.021110e+09,797.0,45.0,KC,0.39,4.81,...,NaN,NaN,0.0,0.0,0.0,0.0,53479.0,PP,0.0,8
2,40023,6-5,304,Terron Armstead,2.021103e+09,2098.0,14.0,NO,1.14,4.67,...,NaN,NaN,0.0,0.0,0.0,0.0,35441.0,PA,0.0,8
3,41296,6-5,310,Billy Turner,2.021103e+09,368.0,19.0,GB,2.34,4.64,...,NaN,NaN,0.0,0.0,0.0,0.0,42401.0,PP,0.0,8
4,46152,6-8,345,Orlando Brown,2.021110e+09,797.0,44.0,KC,0.55,4.59,...,NaN,NaN,0.0,0.0,0.0,0.0,53479.0,PP,0.0,8

In [43]:
w8_T.to_csv('Resources/tackle_w8.csv', sep=',', index=False)

In [44]:
w8_T_df = pd.read_csv('Resources/tackle_w8.csv')
w8_T_df.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,52938,6-6,310,Terence Steele,2.021103e+09,2860.0,6.0,DAL,0.75,5.29,...,NaN,NaN,0.0,0.0,0.0,0.0,44867.0,PA,0.0,8
1,46152,6-8,345,Orlando Brown,2.021110e+09,797.0,45.0,KC,0.39,4.81,...,NaN,NaN,0.0,0.0,0.0,0.0,53479.0,PP,0.0,8
2,40023,6-5,304,Terron Armstead,2.021103e+09,2098.0,14.0,NO,1.14,4.67,...,NaN,NaN,0.0,0.0,0.0,0.0,35441.0,PA,0.0,8
3,41296,6-5,310,Billy Turner,2.021103e+09,368.0,19.0,GB,2.34,4.64,...,NaN,NaN,0.0,0.0,0.0,0.0,42401.0,PP,0.0,8
4,46152,6-8,345,Orlando Brown,2.021110e+09,797.0,44.0,KC,0.55,4.59,...,NaN,NaN,0.0,0.0,0.0,0.0,53479.0,PP,0.0,8