In [1]:
import csv
import os
import pandas as pd
import numpy as np

In [2]:
players_data_to_load = "Resources/players.csv"
week3_data_to_load = "Resources/week3.csv"
plays_data_to_load = "Resources/plays.csv"
pff_data_to_load = "Resources/pffScoutingData.csv"
games_data_to_load = "Resources/games.csv"

In [3]:
players_df = pd.read_csv(players_data_to_load)
players_df

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName
0,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady
1,28963,6-5,240,1982-03-02,"Miami, O.",QB,Ben Roethlisberger
2,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters
3,29851,6-2,225,1983-12-02,California,QB,Aaron Rodgers
4,30078,6-2,228,1982-11-24,Harvard,QB,Ryan Fitzpatrick
...,...,...,...,...,...,...,...
1674,53991,6-1,320,NaN,NaN,DT,Forrest Merrill
1675,53994,6-5,300,NaN,NaN,C,Ryan McCollum
1676,53999,6-4,312,NaN,NaN,DT,Jack Heflin
1677,54006,6-6,330,NaN,NaN,T,Jake Curhan
1678,54038,6-6,245,NaN,NaN,QB,Feleipe Franks

In [4]:
week3_df = pd.read_csv(week3_data_to_load)
week3_df

,gameId,playId,nflId,frameId,time,jerseyNumber,team,playDirection,x,y,s,a,dis,o,dir,event
0,2021092300,54,41300.0,1,2021-09-24T00:23:08.400,58.0,HOU,right,38.66,28.98,0.00,0.00,0.00,259.88,205.34,None
1,2021092300,54,41300.0,2,2021-09-24T00:23:08.500,58.0,HOU,right,38.66,28.98,0.00,0.00,0.01,259.88,197.10,None
2,2021092300,54,41300.0,3,2021-09-24T00:23:08.600,58.0,HOU,right,38.66,28.97,0.00,0.00,0.00,259.88,192.98,None
3,2021092300,54,41300.0,4,2021-09-24T00:23:08.700,58.0,HOU,right,38.66,28.97,0.02,0.34,0.00,259.88,181.68,None
4,2021092300,54,41300.0,5,2021-09-24T00:23:08.800,58.0,HOU,right,38.66,28.97,0.05,0.37,0.00,260.78,199.16,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1121820,2021092700,4156,NaN,43,2021-09-28T03:24:35.900,NaN,football,left,74.61,29.30,5.11,4.88,0.52,NaN,NaN,None
1121821,2021092700,4156,NaN,44,2021-09-28T03:24:36.000,NaN,football,left,74.35,29.71,4.66,5.33,0.49,NaN,NaN,None
1121822,2021092700,4156,NaN,45,2021-09-28T03:24:36.100,NaN,football,left,74.12,30.09,4.16,4.69,0.44,NaN,NaN,None
1121823,2021092700,4156,NaN,46,2021-09-28T03:24:36.200,NaN,football,left,73.15,30.52,5.15,3.22,1.06,NaN,NaN,None
1121824,2021092700,4156,NaN,47,2021-09-28T03:24:36.300,NaN,football,left,72.35,30.84,5.23,3.34,0.86,NaN,NaN,None

In [5]:
week3_players = players_df.merge(week3_df, how='left')
week3_players

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
0,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021093e+09,75.0,1.0,...,TB,left,88.92,23.45,0.01,0.01,0.01,277.75,160.51,None
1,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021093e+09,75.0,2.0,...,TB,left,88.91,23.44,0.01,0.01,0.02,277.00,172.17,None
2,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021093e+09,75.0,3.0,...,TB,left,88.91,23.44,0.01,0.01,0.00,277.58,174.83,None
3,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021093e+09,75.0,4.0,...,TB,left,88.91,23.44,0.01,0.01,0.00,277.58,178.58,None
4,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021093e+09,75.0,5.0,...,TB,left,88.90,23.43,0.01,0.01,0.01,279.25,180.33,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1073562,54038,6-6,245,NaN,NaN,QB,Feleipe Franks,2.021093e+09,3492.0,42.0,...,ATL,right,102.78,49.05,7.66,1.99,0.77,128.46,58.00,None
1073563,54038,6-6,245,NaN,NaN,QB,Feleipe Franks,2.021093e+09,3492.0,43.0,...,ATL,right,103.42,49.44,7.52,2.21,0.76,132.26,59.57,None
1073564,54038,6-6,245,NaN,NaN,QB,Feleipe Franks,2.021093e+09,3492.0,44.0,...,ATL,right,104.07,49.80,7.39,2.39,0.74,134.71,61.34,None
1073565,54038,6-6,245,NaN,NaN,QB,Feleipe Franks,2.021093e+09,3492.0,45.0,...,ATL,right,104.72,50.15,7.29,2.43,0.74,136.10,63.09,None
1073566,54038,6-6,245,NaN,NaN,QB,Feleipe Franks,2.021093e+09,3492.0,46.0,...,ATL,right,105.37,50.46,7.16,2.47,0.72,139.01,64.82,None

## Centers

In [11]:
week3_players_C = week3_players[week3_players['officialPosition'] == 'C']
week3_players_C.head()

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
15660,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021093e+09,338.0,1.0,...,SF,right,38.70,23.87,0.00,0.00,0.00,84.12,64.35,None
15661,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021093e+09,338.0,2.0,...,SF,right,38.70,23.87,0.00,0.00,0.01,83.21,59.94,man_in_motion
15662,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021093e+09,338.0,3.0,...,SF,right,38.69,23.88,0.00,0.00,0.01,81.91,55.76,None
15663,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021093e+09,338.0,4.0,...,SF,right,38.68,23.88,0.01,0.25,0.01,81.91,303.88,None
15664,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021093e+09,338.0,5.0,...,SF,right,38.67,23.89,0.10,0.90,0.02,81.91,294.98,None

In [12]:
week3_players_C = week3_players_C[week3_players_C['event'] != 'None']
week3_players_C.head()

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
15661,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021093e+09,338.0,2.0,...,SF,right,38.70,23.87,0.00,0.00,0.01,83.21,59.94,man_in_motion
15665,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021093e+09,338.0,6.0,...,SF,right,38.63,23.90,0.36,1.79,0.05,84.18,295.09,autoevent_ballsnap
15666,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021093e+09,338.0,7.0,...,SF,right,38.57,23.93,0.65,2.25,0.06,82.87,294.82,ball_snap
15682,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021093e+09,338.0,23.0,...,SF,right,35.42,24.57,1.83,1.65,0.20,37.34,254.54,autoevent_passforward
15683,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021093e+09,338.0,24.0,...,SF,right,35.24,24.50,1.83,1.49,0.20,38.88,248.98,pass_forward

In [13]:
week3_players_C = week3_players_C.sort_values('a', ascending = False)
week3_players_C.head()

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
53440,37266,6-3,295,1987-11-05,Cincinnati,C,Jason Kelce,2.021093e+09,3482.0,36.0,...,PHI,left,76.86,25.87,1.02,3.87,0.12,312.08,75.62,pass_forward
130840,40151,6-4,319,1991-05-27,Colorado State-Pueblo,C,Ryan Jensen,2.021093e+09,3956.0,6.0,...,TB,right,30.83,23.59,0.83,3.64,0.06,89.62,289.99,ball_snap
53439,37266,6-3,295,1987-11-05,Cincinnati,C,Jason Kelce,2.021093e+09,3482.0,35.0,...,PHI,left,76.75,25.84,1.29,3.56,0.14,300.00,48.41,autoevent_passforward
130334,40151,6-4,319,1991-05-27,Colorado State-Pueblo,C,Ryan Jensen,2.021093e+09,3072.0,36.0,...,TB,left,66.53,29.49,1.43,3.45,0.13,229.23,174.67,pass_forward
296316,42883,6-3,300,1992-07-10,Georgia,C,David Andrews,2.021093e+09,537.0,44.0,...,NE,left,90.23,19.08,0.02,3.43,0.02,76.02,69.31,qb_sack

In [9]:
week3_players_C = week3_players_C.dropna()

In [15]:
cleaned_C= week3_players_C[['nflId', 'height', 'weight', 'displayName', 'gameId', 'playId', 'frameId', 'team', 's', 'a', 'dis', 'event']]
cleaned_C

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,dis,event
53440,37266,6-3,295,Jason Kelce,2.021093e+09,3482.0,36.0,PHI,1.02,3.87,0.12,pass_forward
130840,40151,6-4,319,Ryan Jensen,2.021093e+09,3956.0,6.0,TB,0.83,3.64,0.06,ball_snap
53439,37266,6-3,295,Jason Kelce,2.021093e+09,3482.0,35.0,PHI,1.29,3.56,0.14,autoevent_passforward
130334,40151,6-4,319,Ryan Jensen,2.021093e+09,3072.0,36.0,TB,1.43,3.45,0.13,pass_forward
296316,42883,6-3,300,David Andrews,2.021093e+09,537.0,44.0,NE,0.02,3.43,0.02,qb_sack
...,...,...,...,...,...,...,...,...,...,...,...,...
921617,52564,6-3,310,Keith Ismael,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
966197,53063,6-3,270,Aaron Brewer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048112,53543,6-3,300,Drew Dalman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1062669,53619,6-3,330,Trey Hill,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1072891,53994,6-5,300,Ryan McCollum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Guards

In [18]:
week3_players_G = week3_players[week3_players['officialPosition'] == 'G']
week3_players_G.head()

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
26369,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021093e+09,98.0,1.0,...,TEN,right,33.42,25.30,0.07,0.16,0.01,44.94,268.61,None
26370,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021093e+09,98.0,2.0,...,TEN,right,33.41,25.29,0.10,0.10,0.01,47.73,249.94,None
26371,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021093e+09,98.0,3.0,...,TEN,right,33.41,25.29,0.09,0.03,0.01,47.73,237.61,None
26372,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021093e+09,98.0,4.0,...,TEN,right,33.39,25.29,0.15,0.17,0.02,56.06,274.34,None
26373,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021093e+09,98.0,5.0,...,TEN,right,33.37,25.30,0.16,0.24,0.02,59.68,292.44,None

In [19]:
week3_players_G = week3_players_G[week3_players_G['event'] != 'None']
week3_players_G.head()

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
26374,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021093e+09,98.0,6.0,...,TEN,right,33.36,25.30,0.13,0.06,0.01,58.58,278.01,ball_snap
26398,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021093e+09,98.0,30.0,...,TEN,right,28.48,25.45,2.28,2.11,0.22,351.45,254.00,qb_sack
26409,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021093e+09,267.0,6.0,...,TEN,right,43.99,31.21,0.29,0.29,0.04,26.15,268.94,ball_snap
26442,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021093e+09,267.0,39.0,...,TEN,right,40.56,30.70,1.67,2.67,0.18,64.66,4.07,run
26452,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021093e+09,288.0,5.0,...,TEN,right,61.47,31.29,0.22,0.31,0.04,130.52,159.04,shift

In [20]:
week3_players_G = week3_players_G.sort_values('a', ascending = False)

In [21]:
week3_players_G = week3_players_G.dropna()

In [22]:
cleaned_G = week3_players_G[['nflId', 'height', 'weight', 'displayName', 'gameId', 'playId', 'frameId', 'team', 's', 'a', 'dis', 'event']]
cleaned_G

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,dis,event
396578,43453,6-6,320,Halapoulivaati Vaitai,2.021093e+09,3166.0,57.0,DET,1.30,4.50,0.14,pass_forward
176318,41321,6-3,315,Trai Turner,2.021093e+09,1871.0,72.0,PIT,3.20,3.86,0.32,pass_forward
96418,39965,6-5,311,Justin Pugh,2.021093e+09,223.0,27.0,ARI,1.16,3.80,0.13,pass_forward
176319,41321,6-3,315,Trai Turner,2.021093e+09,1871.0,73.0,PIT,2.89,3.74,0.29,autoevent_passforward
629341,46163,6-6,305,Alex Cappa,2.021093e+09,2842.0,47.0,TB,1.40,3.74,0.14,run
...,...,...,...,...,...,...,...,...,...,...,...,...
628298,46163,6-6,305,Alex Cappa,2.021093e+09,75.0,6.0,TB,0.00,0.00,0.01,ball_snap
628593,46163,6-6,305,Alex Cappa,2.021093e+09,1157.0,6.0,TB,0.00,0.00,0.00,autoevent_ballsnap
628596,46163,6-6,305,Alex Cappa,2.021093e+09,1157.0,9.0,TB,0.00,0.00,0.00,ball_snap
628928,46163,6-6,305,Alex Cappa,2.021093e+09,2011.0,6.0,TB,0.00,0.00,0.00,ball_snap
175584,41321,6-3,315,Trai Turner,2.021093e+09,390.0,6.0,PIT,0.00,0.00,0.01,autoevent_ballsnap

## Tackles

In [24]:
week3_players_T = week3_players[week3_players['officialPosition'] == 'T']
week3_players_T.head()

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
4122,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021093e+09,358.0,1.0,...,CHI,right,72.08,29.16,0.0,0.00,0.02,58.81,120.48,None
4123,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021093e+09,358.0,2.0,...,CHI,right,72.08,29.18,0.0,0.00,0.01,58.81,62.29,None
4124,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021093e+09,358.0,3.0,...,CHI,right,72.08,29.18,0.0,0.00,0.01,58.81,36.30,None
4125,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021093e+09,358.0,4.0,...,CHI,right,72.08,29.18,0.0,0.00,0.00,59.63,41.53,None
4126,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021093e+09,358.0,5.0,...,CHI,right,72.08,29.18,0.0,0.02,0.00,60.92,9.54,None

In [26]:
week3_players_T = week3_players_T[week3_players_T['event'] != 'None']
week3_players_T.head()

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
4127,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021093e+09,358.0,6.0,...,CHI,right,72.07,29.19,0.04,0.34,0.01,59.42,301.60,ball_snap
4128,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021093e+09,358.0,7.0,...,CHI,right,72.05,29.19,0.13,0.63,0.02,60.36,288.55,autoevent_ballsnap
4163,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021093e+09,358.0,42.0,...,CHI,right,63.41,24.32,2.98,3.13,0.31,155.60,195.89,run
4174,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021093e+09,693.0,6.0,...,CHI,right,39.23,32.93,0.08,0.77,0.02,132.58,286.60,ball_snap
4184,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021093e+09,693.0,16.0,...,CHI,right,37.72,33.64,2.30,0.96,0.25,35.52,288.66,play_action

In [27]:
week3_players_T = week3_players_T.sort_values('a', ascending = False)

In [28]:
week3_players_T = week3_players_T.dropna()

In [29]:
cleaned_T = week3_players_T[['nflId', 'height', 'weight', 'displayName', 'gameId', 'playId', 'frameId', 'team', 's', 'a', 'dis', 'event']]
cleaned_T

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,dis,event
835768,52412,6-5,326,Andrew Thomas,2.021093e+09,903.0,19.0,NYG,1.63,4.24,0.16,play_action
195485,41532,6-5,310,James Hurst,2.021093e+09,1026.0,21.0,NO,1.59,4.21,0.17,play_action
563897,46084,6-8,325,Kolton Miller,2.021093e+09,2927.0,41.0,LV,1.86,4.20,0.18,pass_forward
409172,43586,6-5,322,George Fant,2.021093e+09,1003.0,26.0,NYJ,2.71,4.08,0.28,pass_forward
848474,52426,6-6,310,Austin Jackson,2.021093e+09,3549.0,93.0,MIA,5.09,4.08,0.53,pass_forward
...,...,...,...,...,...,...,...,...,...,...,...,...
301573,42924,6-6,325,Jesse Davis,2.021093e+09,2033.0,6.0,MIA,0.00,0.00,0.02,ball_snap
812709,48181,6-7,314,Yosuah Nijman,2.021093e+09,2856.0,6.0,GB,0.00,0.00,0.01,autoevent_ballsnap
263858,42445,6-6,330,Daryl Williams,2.021093e+09,2712.0,6.0,BUF,0.00,0.00,0.01,ball_snap
263388,42445,6-6,330,Daryl Williams,2.021093e+09,1547.0,157.0,BUF,0.00,0.00,0.00,ball_snap
332717,43320,6-5,325,Germain Ifedi,2.021093e+09,1112.0,5.0,CHI,0.00,0.00,0.01,man_in_motion

## Plays, PFF, & Games data added

In [30]:
plays_df = pd.read_csv(plays_data_to_load)
plays_df

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,defensiveTeam,yardlineSide,yardlineNumber,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,2021090900,97,(13:33) (Shotgun) T.Brady pass incomplete deep...,1,3,2,TB,DAL,TB,33,...,NaN,43.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
1,2021090900,137,(13:18) (Shotgun) D.Prescott pass deep left to...,1,1,10,DAL,TB,DAL,2,...,NaN,108.0,EMPTY,"1 RB, 2 TE, 2 WR",6.0,"4 DL, 4 LB, 3 DB",TRADITIONAL,0,Cover-3,Zone
2,2021090900,187,(12:23) (Shotgun) D.Prescott pass short middle...,1,2,6,DAL,TB,DAL,34,...,NaN,76.0,SHOTGUN,"0 RB, 2 TE, 3 WR",6.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,0,Cover-3,Zone
3,2021090900,282,(9:56) D.Prescott pass incomplete deep left to...,1,1,10,DAL,TB,TB,39,...,NaN,49.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",6.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1,Cover-3,Zone
4,2021090900,349,(9:46) (Shotgun) D.Prescott pass incomplete sh...,1,3,15,DAL,TB,TB,44,...,NaN,54.0,SHOTGUN,"1 RB, 1 TE, 3 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,0,Cover-3,Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8552,2021110100,4310,(1:56) (Shotgun) P.Mahomes sacked at NYG 16 fo...,4,3,8,KC,NYG,NYG,8,...,NaN,18.0,SHOTGUN,"1 RB, 1 TE, 3 WR",4.0,"1 DL, 3 LB, 7 DB",SCRAMBLE,0,Bracket,Other
8553,2021110100,4363,(1:07) (Shotgun) D.Jones pass short right to E...,4,1,10,NYG,KC,NYG,25,...,NaN,35.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"4 DL, 1 LB, 6 DB",SCRAMBLE,0,Cover-2,Zone
8554,2021110100,4392,"(1:01) (No Huddle, Shotgun) D.Jones sacked at ...",4,2,7,NYG,KC,NYG,28,...,NaN,38.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Cover-2,Zone
8555,2021110100,4411,"(:39) (No Huddle, Shotgun) D.Jones pass incomp...",4,3,15,NYG,KC,NYG,20,...,NaN,30.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Cover-2,Zone
8556,2021110100,4433,(:35) (Shotgun) D.Jones sacked at NYG 14 for -...,4,4,15,NYG,KC,NYG,20,...,NaN,30.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Quarters,Zone

In [31]:
pff_df = pd.read_csv(pff_data_to_load)
pff_df

,gameId,playId,nflId,pff_role,pff_positionLinedUp,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,2021090900,97,25511,Pass,QB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021090900,97,35481,Pass Route,TE-L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021090900,97,35634,Pass Route,LWR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021090900,97,39985,Pass Route,HB-R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021090900,97,40151,Pass Block,C,NaN,NaN,NaN,0.0,0.0,0.0,0.0,44955.0,SW,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188249,2021110100,4433,52507,Pass Block,LT,NaN,NaN,NaN,0.0,0.0,1.0,0.0,43338.0,PP,0.0
188250,2021110100,4433,52546,Coverage,SCBoR,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188251,2021110100,4433,52573,Pass Route,SLoWR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188252,2021110100,4433,52585,Pass Rush,LEO,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188253,2021110100,4433,53449,Pass Route,LWR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
games_df = pd.read_csv(games_data_to_load)
games_df

,gameId,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,2021090900,2021,1,09/09/2021,20:20:00,TB,DAL
1,2021091200,2021,1,09/12/2021,13:00:00,ATL,PHI
2,2021091201,2021,1,09/12/2021,13:00:00,BUF,PIT
3,2021091202,2021,1,09/12/2021,13:00:00,CAR,NYJ
4,2021091203,2021,1,09/12/2021,13:00:00,CIN,MIN
...,...,...,...,...,...,...,...
117,2021103109,2021,8,10/31/2021,16:05:00,SEA,JAX
118,2021103110,2021,8,10/31/2021,16:25:00,DEN,WAS
119,2021103111,2021,8,10/31/2021,16:25:00,NO,TB
120,2021103112,2021,8,10/31/2021,20:20:00,MIN,DAL
121,2021110100,2021,8,11/01/2021,20:15:00,KC,NYG

# Merging all data & Cleaning

## Center

In [33]:
w3_C = cleaned_C.merge(plays_df, how="left")
w3_C.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,37266,6-3,295,Jason Kelce,2.021093e+09,3482.0,36.0,PHI,1.02,3.87,...,NaN,72.0,SHOTGUN,"1 RB, 1 TE, 3 WR",7.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,0.0,Cover-3,Zone
1,40151,6-4,319,Ryan Jensen,2.021093e+09,3956.0,6.0,TB,0.83,3.64,...,NaN,31.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"2 DL, 3 LB, 6 DB",TRADITIONAL,0.0,Cover-3,Zone
2,37266,6-3,295,Jason Kelce,2.021093e+09,3482.0,35.0,PHI,1.29,3.56,...,NaN,72.0,SHOTGUN,"1 RB, 1 TE, 3 WR",7.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,0.0,Cover-3,Zone
3,40151,6-4,319,Ryan Jensen,2.021093e+09,3072.0,36.0,TB,1.43,3.45,...,NaN,62.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,0.0,Cover-6,Zone
4,42883,6-3,300,David Andrews,2.021093e+09,537.0,44.0,NE,0.02,3.43,...,NaN,85.0,SINGLEBACK,"1 RB, 1 TE, 3 WR",7.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,1.0,Cover-3,Zone

In [34]:
w3_C.drop(columns=[['possessionTeam','pff_passCoverage','pff_passCoverageType']], inplace=True, errors='ignore')

In [35]:
w3_C = w3_C.merge(pff_df, how='left')
w3_C.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,37266,6-3,295,Jason Kelce,2.021093e+09,3482.0,36.0,PHI,1.02,3.87,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,53513.0,PP,0.0
1,40151,6-4,319,Ryan Jensen,2.021093e+09,3956.0,6.0,TB,0.83,3.64,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,41239.0,CL,0.0
2,37266,6-3,295,Jason Kelce,2.021093e+09,3482.0,35.0,PHI,1.29,3.56,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,53513.0,PP,0.0
3,40151,6-4,319,Ryan Jensen,2.021093e+09,3072.0,36.0,TB,1.43,3.45,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,52492.0,PP,0.0
4,42883,6-3,300,David Andrews,2.021093e+09,537.0,44.0,NE,0.02,3.43,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NB,0.0

In [36]:
w3_C = w3_C.merge(games_df, how='left')
w3_C.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,37266,6-3,295,Jason Kelce,2.021093e+09,3482.0,36.0,PHI,1.02,3.87,...,0.0,53513.0,PP,0.0,2021.0,3.0,09/27/2021,20:15:00,DAL,PHI
1,40151,6-4,319,Ryan Jensen,2.021093e+09,3956.0,6.0,TB,0.83,3.64,...,0.0,41239.0,CL,0.0,2021.0,3.0,09/26/2021,16:25:00,LA,TB
2,37266,6-3,295,Jason Kelce,2.021093e+09,3482.0,35.0,PHI,1.29,3.56,...,0.0,53513.0,PP,0.0,2021.0,3.0,09/27/2021,20:15:00,DAL,PHI
3,40151,6-4,319,Ryan Jensen,2.021093e+09,3072.0,36.0,TB,1.43,3.45,...,0.0,52492.0,PP,0.0,2021.0,3.0,09/26/2021,16:25:00,LA,TB
4,42883,6-3,300,David Andrews,2.021093e+09,537.0,44.0,NE,0.02,3.43,...,0.0,NaN,NB,0.0,2021.0,3.0,09/26/2021,13:00:00,NE,NO

In [37]:
w3_C.drop(columns=['homeTeamAbbr', 'visitorTeamAbbr','gameDate', 'gameTimeEastern', 'season'], inplace=True, errors='ignore')
w3_C

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,37266,6-3,295,Jason Kelce,2.021093e+09,3482.0,36.0,PHI,1.02,3.87,...,NaN,NaN,0.0,0.0,0.0,0.0,53513.0,PP,0.0,3.0
1,40151,6-4,319,Ryan Jensen,2.021093e+09,3956.0,6.0,TB,0.83,3.64,...,NaN,NaN,0.0,0.0,0.0,0.0,41239.0,CL,0.0,3.0
2,37266,6-3,295,Jason Kelce,2.021093e+09,3482.0,35.0,PHI,1.29,3.56,...,NaN,NaN,0.0,0.0,0.0,0.0,53513.0,PP,0.0,3.0
3,40151,6-4,319,Ryan Jensen,2.021093e+09,3072.0,36.0,TB,1.43,3.45,...,NaN,NaN,0.0,0.0,0.0,0.0,52492.0,PP,0.0,3.0
4,42883,6-3,300,David Andrews,2.021093e+09,537.0,44.0,NE,0.02,3.43,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NB,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3470,52564,6-3,310,Keith Ismael,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3471,53063,6-3,270,Aaron Brewer,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3472,53543,6-3,300,Drew Dalman,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3473,53619,6-3,330,Trey Hill,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3474,53994,6-5,300,Ryan McCollum,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
w3_C.to_csv('Resources/center_w3.csv', sep=',', index=False)

In [41]:
w3_C_df = pd.read_csv('Resources/center_w3.csv')
w3_C_df.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,37266,6-3,295,Jason Kelce,2.021093e+09,3482.0,36.0,PHI,1.02,3.87,...,NaN,NaN,0.0,0.0,0.0,0.0,53513.0,PP,0.0,3.0
1,40151,6-4,319,Ryan Jensen,2.021093e+09,3956.0,6.0,TB,0.83,3.64,...,NaN,NaN,0.0,0.0,0.0,0.0,41239.0,CL,0.0,3.0
2,37266,6-3,295,Jason Kelce,2.021093e+09,3482.0,35.0,PHI,1.29,3.56,...,NaN,NaN,0.0,0.0,0.0,0.0,53513.0,PP,0.0,3.0
3,40151,6-4,319,Ryan Jensen,2.021093e+09,3072.0,36.0,TB,1.43,3.45,...,NaN,NaN,0.0,0.0,0.0,0.0,52492.0,PP,0.0,3.0
4,42883,6-3,300,David Andrews,2.021093e+09,537.0,44.0,NE,0.02,3.43,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NB,0.0,3.0

## Guard

In [42]:
w3_G = cleaned_G.merge(plays_df, how="left")
w3_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,43453,6-6,320,Halapoulivaati Vaitai,2.021093e+09,3166.0,57.0,DET,1.30,4.50,...,NaN,57.0,EMPTY,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,0,Cover-6,Zone
1,41321,6-3,315,Trai Turner,2.021093e+09,1871.0,72.0,PIT,3.20,3.86,...,NaN,85.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",SCRAMBLE,0,Cover-6,Zone
2,39965,6-5,311,Justin Pugh,2.021093e+09,223.0,27.0,ARI,1.16,3.80,...,NaN,99.0,SHOTGUN,"1 RB, 2 TE, 2 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,0,Cover-3,Zone
3,41321,6-3,315,Trai Turner,2.021093e+09,1871.0,73.0,PIT,2.89,3.74,...,NaN,85.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",SCRAMBLE,0,Cover-6,Zone
4,46163,6-6,305,Alex Cappa,2.021093e+09,2842.0,47.0,TB,1.40,3.74,...,NaN,74.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"2 DL, 4 LB, 5 DB",SCRAMBLE,0,Cover-1,Man

In [43]:
w3_G.drop(columns=[['possessionTeam','pff_passCoverage','pff_passCoverageType']], inplace=True, errors='ignore')
w3_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,43453,6-6,320,Halapoulivaati Vaitai,2.021093e+09,3166.0,57.0,DET,1.30,4.50,...,NaN,57.0,EMPTY,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,0,Cover-6,Zone
1,41321,6-3,315,Trai Turner,2.021093e+09,1871.0,72.0,PIT,3.20,3.86,...,NaN,85.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",SCRAMBLE,0,Cover-6,Zone
2,39965,6-5,311,Justin Pugh,2.021093e+09,223.0,27.0,ARI,1.16,3.80,...,NaN,99.0,SHOTGUN,"1 RB, 2 TE, 2 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,0,Cover-3,Zone
3,41321,6-3,315,Trai Turner,2.021093e+09,1871.0,73.0,PIT,2.89,3.74,...,NaN,85.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",SCRAMBLE,0,Cover-6,Zone
4,46163,6-6,305,Alex Cappa,2.021093e+09,2842.0,47.0,TB,1.40,3.74,...,NaN,74.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"2 DL, 4 LB, 5 DB",SCRAMBLE,0,Cover-1,Man

In [44]:
w3_G = w3_G.merge(pff_df, how='left')
w3_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,43453,6-6,320,Halapoulivaati Vaitai,2.021093e+09,3166.0,57.0,DET,1.30,4.50,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,33131.0,SW,0.0
1,41321,6-3,315,Trai Turner,2.021093e+09,1871.0,72.0,PIT,3.20,3.86,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,53540.0,SW,0.0
2,39965,6-5,311,Justin Pugh,2.021093e+09,223.0,27.0,ARI,1.16,3.80,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,52481.0,PT,0.0
3,41321,6-3,315,Trai Turner,2.021093e+09,1871.0,73.0,PIT,2.89,3.74,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,53540.0,SW,0.0
4,46163,6-6,305,Alex Cappa,2.021093e+09,2842.0,47.0,TB,1.40,3.74,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,47917.0,PP,0.0

In [45]:
w3_G = w3_G.merge(games_df, how='left')
w3_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,43453,6-6,320,Halapoulivaati Vaitai,2.021093e+09,3166.0,57.0,DET,1.30,4.50,...,0.0,33131.0,SW,0.0,2021,3,09/26/2021,13:00:00,DET,BAL
1,41321,6-3,315,Trai Turner,2.021093e+09,1871.0,72.0,PIT,3.20,3.86,...,0.0,53540.0,SW,0.0,2021,3,09/26/2021,13:00:00,PIT,CIN
2,39965,6-5,311,Justin Pugh,2.021093e+09,223.0,27.0,ARI,1.16,3.80,...,0.0,52481.0,PT,0.0,2021,3,09/26/2021,13:00:00,JAX,ARI
3,41321,6-3,315,Trai Turner,2.021093e+09,1871.0,73.0,PIT,2.89,3.74,...,0.0,53540.0,SW,0.0,2021,3,09/26/2021,13:00:00,PIT,CIN
4,46163,6-6,305,Alex Cappa,2.021093e+09,2842.0,47.0,TB,1.40,3.74,...,0.0,47917.0,PP,0.0,2021,3,09/26/2021,16:25:00,LA,TB

In [46]:
w3_G.drop(columns=['homeTeamAbbr', 'visitorTeamAbbr','gameDate', 'gameTimeEastern', 'season'], inplace=True, errors='ignore')
w3_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,43453,6-6,320,Halapoulivaati Vaitai,2.021093e+09,3166.0,57.0,DET,1.30,4.50,...,NaN,NaN,0.0,0.0,1.0,0.0,33131.0,SW,0.0,3
1,41321,6-3,315,Trai Turner,2.021093e+09,1871.0,72.0,PIT,3.20,3.86,...,NaN,NaN,0.0,0.0,0.0,0.0,53540.0,SW,0.0,3
2,39965,6-5,311,Justin Pugh,2.021093e+09,223.0,27.0,ARI,1.16,3.80,...,NaN,NaN,0.0,0.0,0.0,0.0,52481.0,PT,0.0,3
3,41321,6-3,315,Trai Turner,2.021093e+09,1871.0,73.0,PIT,2.89,3.74,...,NaN,NaN,0.0,0.0,0.0,0.0,53540.0,SW,0.0,3
4,46163,6-6,305,Alex Cappa,2.021093e+09,2842.0,47.0,TB,1.40,3.74,...,NaN,NaN,0.0,0.0,1.0,0.0,47917.0,PP,0.0,3

In [47]:
w3_G.to_csv('Resources/guard_w3.csv', sep=',', index=False)

In [48]:
w3_G_df = pd.read_csv('Resources/guard_w3.csv')
w3_G_df.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,43453,6-6,320,Halapoulivaati Vaitai,2.021093e+09,3166.0,57.0,DET,1.30,4.50,...,NaN,NaN,0.0,0.0,1.0,0.0,33131.0,SW,0.0,3
1,41321,6-3,315,Trai Turner,2.021093e+09,1871.0,72.0,PIT,3.20,3.86,...,NaN,NaN,0.0,0.0,0.0,0.0,53540.0,SW,0.0,3
2,39965,6-5,311,Justin Pugh,2.021093e+09,223.0,27.0,ARI,1.16,3.80,...,NaN,NaN,0.0,0.0,0.0,0.0,52481.0,PT,0.0,3
3,41321,6-3,315,Trai Turner,2.021093e+09,1871.0,73.0,PIT,2.89,3.74,...,NaN,NaN,0.0,0.0,0.0,0.0,53540.0,SW,0.0,3
4,46163,6-6,305,Alex Cappa,2.021093e+09,2842.0,47.0,TB,1.40,3.74,...,NaN,NaN,0.0,0.0,1.0,0.0,47917.0,PP,0.0,3

## Tackle

In [49]:
w3_T = cleaned_T.merge(plays_df, how="left")
w3_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,52412,6-5,326,Andrew Thomas,2.021093e+09,903.0,19.0,NYG,1.63,4.24,...,NaN,24.0,SINGLEBACK,"1 RB, 3 TE, 1 WR",8.0,"3 DL, 4 LB, 4 DB",SCRAMBLE_ROLLOUT_RIGHT,1,Cover-6,Zone
1,41532,6-5,310,James Hurst,2.021093e+09,1026.0,21.0,NO,1.59,4.21,...,NaN,90.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",8.0,"3 DL, 3 LB, 5 DB",DESIGNED_ROLLOUT_RIGHT,1,Cover-1,Man
2,46084,6-8,325,Kolton Miller,2.021093e+09,2927.0,41.0,LV,1.86,4.20,...,NaN,52.0,SHOTGUN,"1 RB, 2 TE, 2 WR",7.0,"3 DL, 2 LB, 6 DB",TRADITIONAL,0,Cover-3,Zone
3,43586,6-5,322,George Fant,2.021093e+09,1003.0,26.0,NYJ,2.71,4.08,...,NaN,58.0,EMPTY,"1 RB, 1 TE, 3 WR",5.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
4,52426,6-6,310,Austin Jackson,2.021093e+09,3549.0,93.0,MIA,5.09,4.08,...,NaN,77.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"4 DL, 2 LB, 5 DB",NaN,0,Cover-1,Man

In [50]:
w3_T.drop(columns=['possessionTeam','pff_passCoverage','pff_passCoverageType'], inplace=True, errors='ignore')
w3_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId2,foulName3,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction
0,52412,6-5,326,Andrew Thomas,2.021093e+09,903.0,19.0,NYG,1.63,4.24,...,NaN,NaN,NaN,24.0,SINGLEBACK,"1 RB, 3 TE, 1 WR",8.0,"3 DL, 4 LB, 4 DB",SCRAMBLE_ROLLOUT_RIGHT,1
1,41532,6-5,310,James Hurst,2.021093e+09,1026.0,21.0,NO,1.59,4.21,...,NaN,NaN,NaN,90.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",8.0,"3 DL, 3 LB, 5 DB",DESIGNED_ROLLOUT_RIGHT,1
2,46084,6-8,325,Kolton Miller,2.021093e+09,2927.0,41.0,LV,1.86,4.20,...,NaN,NaN,NaN,52.0,SHOTGUN,"1 RB, 2 TE, 2 WR",7.0,"3 DL, 2 LB, 6 DB",TRADITIONAL,0
3,43586,6-5,322,George Fant,2.021093e+09,1003.0,26.0,NYJ,2.71,4.08,...,NaN,NaN,NaN,58.0,EMPTY,"1 RB, 1 TE, 3 WR",5.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,0
4,52426,6-6,310,Austin Jackson,2.021093e+09,3549.0,93.0,MIA,5.09,4.08,...,NaN,NaN,NaN,77.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"4 DL, 2 LB, 5 DB",NaN,0

In [51]:
w3_T = w3_T.merge(pff_df, how='left')
w3_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,52412,6-5,326,Andrew Thomas,2.021093e+09,903.0,19.0,NYG,1.63,4.24,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,43361.0,PA,0.0
1,41532,6-5,310,James Hurst,2.021093e+09,1026.0,21.0,NO,1.59,4.21,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,43435.0,PA,0.0
2,46084,6-8,325,Kolton Miller,2.021093e+09,2927.0,41.0,LV,1.86,4.20,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,47934.0,PP,0.0
3,43586,6-5,322,George Fant,2.021093e+09,1003.0,26.0,NYJ,2.71,4.08,...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,47016.0,PT,0.0
4,52426,6-6,310,Austin Jackson,2.021093e+09,3549.0,93.0,MIA,5.09,4.08,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,43358.0,PP,0.0

In [52]:
w3_T = w3_T.merge(games_df, how='left')
w3_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,52412,6-5,326,Andrew Thomas,2.021093e+09,903.0,19.0,NYG,1.63,4.24,...,0.0,43361.0,PA,0.0,2021,3,09/26/2021,13:00:00,NYG,ATL
1,41532,6-5,310,James Hurst,2.021093e+09,1026.0,21.0,NO,1.59,4.21,...,0.0,43435.0,PA,0.0,2021,3,09/26/2021,13:00:00,NE,NO
2,46084,6-8,325,Kolton Miller,2.021093e+09,2927.0,41.0,LV,1.86,4.20,...,0.0,47934.0,PP,0.0,2021,3,09/26/2021,16:05:00,LV,MIA
3,43586,6-5,322,George Fant,2.021093e+09,1003.0,26.0,NYJ,2.71,4.08,...,0.0,47016.0,PT,0.0,2021,3,09/26/2021,16:05:00,DEN,NYJ
4,52426,6-6,310,Austin Jackson,2.021093e+09,3549.0,93.0,MIA,5.09,4.08,...,0.0,43358.0,PP,0.0,2021,3,09/26/2021,16:05:00,LV,MIA

In [53]:
w3_T.drop(columns=['homeTeamAbbr', 'visitorTeamAbbr','gameDate', 'gameTimeEastern', 'season'], inplace=True, errors='ignore')
w3_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,52412,6-5,326,Andrew Thomas,2.021093e+09,903.0,19.0,NYG,1.63,4.24,...,NaN,NaN,0.0,0.0,0.0,0.0,43361.0,PA,0.0,3
1,41532,6-5,310,James Hurst,2.021093e+09,1026.0,21.0,NO,1.59,4.21,...,NaN,NaN,0.0,0.0,0.0,0.0,43435.0,PA,0.0,3
2,46084,6-8,325,Kolton Miller,2.021093e+09,2927.0,41.0,LV,1.86,4.20,...,NaN,NaN,0.0,0.0,0.0,0.0,47934.0,PP,0.0,3
3,43586,6-5,322,George Fant,2.021093e+09,1003.0,26.0,NYJ,2.71,4.08,...,NaN,NaN,1.0,0.0,0.0,0.0,47016.0,PT,0.0,3
4,52426,6-6,310,Austin Jackson,2.021093e+09,3549.0,93.0,MIA,5.09,4.08,...,NaN,NaN,0.0,0.0,0.0,0.0,43358.0,PP,0.0,3

In [54]:
w3_T.to_csv('Resources/tackle_w3.csv', sep=',', index=False)

In [55]:
w3_T_df = pd.read_csv('Resources/tackle_w3.csv')
w3_T_df.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,52412,6-5,326,Andrew Thomas,2.021093e+09,903.0,19.0,NYG,1.63,4.24,...,NaN,NaN,0.0,0.0,0.0,0.0,43361.0,PA,0.0,3
1,41532,6-5,310,James Hurst,2.021093e+09,1026.0,21.0,NO,1.59,4.21,...,NaN,NaN,0.0,0.0,0.0,0.0,43435.0,PA,0.0,3
2,46084,6-8,325,Kolton Miller,2.021093e+09,2927.0,41.0,LV,1.86,4.20,...,NaN,NaN,0.0,0.0,0.0,0.0,47934.0,PP,0.0,3
3,43586,6-5,322,George Fant,2.021093e+09,1003.0,26.0,NYJ,2.71,4.08,...,NaN,NaN,1.0,0.0,0.0,0.0,47016.0,PT,0.0,3
4,52426,6-6,310,Austin Jackson,2.021093e+09,3549.0,93.0,MIA,5.09,4.08,...,NaN,NaN,0.0,0.0,0.0,0.0,43358.0,PP,0.0,3