In [2]:
import csv
import os
import pandas as pd
import numpy as np

In [4]:
players_data_to_load = "Resources/players.csv"
week4_data_to_load = "Resources/week4.csv"
plays_data_to_load = "Resources/plays.csv"
pff_data_to_load = "Resources/pffScoutingData.csv"
games_data_to_load = "Resources/games.csv"

In [5]:
players_df = pd.read_csv(players_data_to_load)
players_df

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName
0,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady
1,28963,6-5,240,1982-03-02,"Miami, O.",QB,Ben Roethlisberger
2,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters
3,29851,6-2,225,1983-12-02,California,QB,Aaron Rodgers
4,30078,6-2,228,1982-11-24,Harvard,QB,Ryan Fitzpatrick
...,...,...,...,...,...,...,...
1674,53991,6-1,320,NaN,NaN,DT,Forrest Merrill
1675,53994,6-5,300,NaN,NaN,C,Ryan McCollum
1676,53999,6-4,312,NaN,NaN,DT,Jack Heflin
1677,54006,6-6,330,NaN,NaN,T,Jake Curhan
1678,54038,6-6,245,NaN,NaN,QB,Feleipe Franks

In [6]:
week4_df = pd.read_csv(week4_data_to_load)
week4_df

,gameId,playId,nflId,frameId,time,jerseyNumber,team,playDirection,x,y,s,a,dis,o,dir,event
0,2021093000,169,38696.0,1,2021-10-01T00:29:42.800,11.0,JAX,right,54.66,44.66,0.00,0.00,0.00,107.61,134.74,None
1,2021093000,169,38696.0,2,2021-10-01T00:29:42.900,11.0,JAX,right,54.66,44.66,0.00,0.00,0.00,107.61,130.79,None
2,2021093000,169,38696.0,3,2021-10-01T00:29:43.000,11.0,JAX,right,54.66,44.67,0.00,0.00,0.00,107.61,122.78,None
3,2021093000,169,38696.0,4,2021-10-01T00:29:43.100,11.0,JAX,right,54.66,44.66,0.00,0.00,0.00,107.61,134.78,None
4,2021093000,169,38696.0,5,2021-10-01T00:29:43.200,11.0,JAX,right,54.66,44.66,0.00,0.00,0.00,107.61,130.76,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1074601,2021100400,4161,NaN,46,2021-10-05T03:45:55.200,NaN,football,right,20.03,20.49,8.14,0.63,0.81,NaN,NaN,autoevent_passforward
1074602,2021100400,4161,NaN,47,2021-10-05T03:45:55.300,NaN,football,right,20.54,20.01,8.73,0.49,0.70,NaN,NaN,None
1074603,2021100400,4161,NaN,48,2021-10-05T03:45:55.400,NaN,football,right,25.33,16.50,26.07,1.13,5.94,NaN,NaN,None
1074604,2021100400,4161,NaN,49,2021-10-05T03:45:55.500,NaN,football,right,27.40,14.92,25.89,2.45,2.60,NaN,NaN,None
1074605,2021100400,4161,NaN,50,2021-10-05T03:45:55.600,NaN,football,right,29.44,13.36,25.59,3.58,2.57,NaN,NaN,None

In [7]:
week4_players = players_df.merge(week4_df, how='left')
week4_players

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
0,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021100e+09,202.0,1.0,...,TB,left,100.22,27.32,0.02,0.02,0.01,295.30,322.70,None
1,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021100e+09,202.0,2.0,...,TB,left,100.23,27.32,0.02,0.02,0.01,301.21,327.05,None
2,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021100e+09,202.0,3.0,...,TB,left,100.22,27.34,0.02,0.02,0.01,309.17,329.13,None
3,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021100e+09,202.0,4.0,...,TB,left,100.25,27.34,0.01,0.02,0.02,317.74,346.35,None
4,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021100e+09,202.0,5.0,...,TB,left,100.29,27.34,0.01,0.02,0.05,316.97,26.09,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1028384,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021100e+09,3338.0,33.0,...,SEA,right,51.39,22.00,3.77,3.08,0.42,42.46,323.52,None
1028385,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021100e+09,3338.0,34.0,...,SEA,right,51.20,22.34,3.75,2.89,0.39,46.08,329.47,None
1028386,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021100e+09,3338.0,35.0,...,SEA,right,51.09,22.73,3.79,3.07,0.41,30.78,338.78,None
1028387,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021100e+09,3338.0,36.0,...,SEA,right,50.98,23.10,3.77,2.95,0.39,39.98,344.51,None
1028388,54038,6-6,245,NaN,NaN,QB,Feleipe Franks,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Centers

In [9]:
week4_players_C = week4_players[week4_players['officialPosition'] == 'C']
week4_players_C.head()

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
15556,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021100e+09,149.0,1.0,...,SF,left,81.93,23.97,0.00,0.00,0.00,287.22,66.13,None
15557,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021100e+09,149.0,2.0,...,SF,left,81.93,23.97,0.00,0.03,0.00,286.51,232.09,None
15558,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021100e+09,149.0,3.0,...,SF,left,81.93,23.96,0.04,0.31,0.01,286.51,191.44,None
15559,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021100e+09,149.0,4.0,...,SF,left,81.93,23.95,0.14,0.73,0.02,285.50,169.85,None
15560,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021100e+09,149.0,5.0,...,SF,left,81.94,23.92,0.27,0.93,0.03,285.50,169.59,None

In [10]:
week4_players_C = week4_players_C[week4_players_C['event'] != 'None']
week4_players_C

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
15561,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021100e+09,149.0,6.0,...,SF,left,81.95,23.88,0.41,0.87,0.04,286.22,161.71,autoevent_ballsnap
15562,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021100e+09,149.0,7.0,...,SF,left,81.99,23.84,0.53,0.98,0.05,286.22,151.50,ball_snap
15585,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021100e+09,149.0,30.0,...,SF,left,85.51,24.01,1.33,1.98,0.13,291.74,73.75,autoevent_passforward
15587,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021100e+09,149.0,32.0,...,SF,left,85.72,24.10,0.96,1.77,0.10,300.10,67.43,pass_forward
15596,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021100e+09,198.0,6.0,...,SF,left,67.83,23.58,0.20,0.99,0.02,254.47,62.25,autoevent_ballsnap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997345,53516,6-3,310,NaN,NaN,C,Kendrick Green,2.021100e+09,3889.0,30.0,...,PIT,right,38.65,23.22,1.28,1.89,0.11,159.26,198.76,autoevent_passforward
997346,53516,6-3,310,NaN,NaN,C,Kendrick Green,2.021100e+09,3889.0,31.0,...,PIT,right,38.62,23.13,0.99,2.08,0.10,164.96,195.07,pass_forward
1006027,53543,6-3,300,NaN,NaN,C,Drew Dalman,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1021181,53619,6-3,330,NaN,NaN,C,Trey Hill,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1028229,53994,6-5,300,NaN,NaN,C,Ryan McCollum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
week4_players_C = week4_players_C.sort_values('a', ascending = False)
week4_players_C

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
267802,42476,6-4,309,1991-11-09,Florida,C,Max Garcia,2.021100e+09,541.0,39.0,...,ARI,right,35.90,26.86,1.03,4.05,0.11,97.66,267.65,autoevent_passforward
318381,43307,6-4,309,1993-05-30,Alabama,C,Ryan Kelly,2.021100e+09,1629.0,31.0,...,IND,right,27.90,30.96,2.00,3.91,0.19,109.54,205.83,autoevent_passforward
857447,52486,6-4,290,1997-11-17,Temple,C,Matt Hennessy,2.021100e+09,208.0,6.0,...,ATL,left,49.49,23.85,0.80,3.85,0.07,233.35,161.60,ball_snap
923853,52894,6-4,315,1998-03-23,Missouri,C,Trystan Colon,2.021100e+09,3829.0,44.0,...,BAL,right,114.22,33.15,3.92,3.84,0.39,278.66,15.22,pass_forward
267803,42476,6-4,309,1991-11-09,Florida,C,Max Garcia,2.021100e+09,541.0,40.0,...,ARI,right,35.79,26.81,1.17,3.80,0.12,102.71,240.48,pass_forward
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729350,47861,6-6,310,1996-09-03,Wisconsin,C,Michael Deiter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
886905,52564,6-3,310,1998-07-25,San Diego State,C,Keith Ismael,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006027,53543,6-3,300,NaN,NaN,C,Drew Dalman,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1021181,53619,6-3,330,NaN,NaN,C,Trey Hill,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1028229,53994,6-5,300,NaN,NaN,C,Ryan McCollum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
week4_players_C = week4_players_C.dropna()

In [13]:
cleaned_C= week4_players_C[['nflId', 'height', 'weight', 'displayName', 'gameId', 'playId', 'frameId', 'team', 's', 'a', 'dis', 'event']]
cleaned_C

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,dis,event
267802,42476,6-4,309,Max Garcia,2.021100e+09,541.0,39.0,ARI,1.03,4.05,0.11,autoevent_passforward
318381,43307,6-4,309,Ryan Kelly,2.021100e+09,1629.0,31.0,IND,2.00,3.91,0.19,autoevent_passforward
857447,52486,6-4,290,Matt Hennessy,2.021100e+09,208.0,6.0,ATL,0.80,3.85,0.07,ball_snap
923853,52894,6-4,315,Trystan Colon,2.021100e+09,3829.0,44.0,BAL,3.92,3.84,0.39,pass_forward
267803,42476,6-4,309,Max Garcia,2.021100e+09,541.0,40.0,ARI,1.17,3.80,0.12,pass_forward
...,...,...,...,...,...,...,...,...,...,...,...,...
400851,43695,6-3,313,Matt Skura,2.021100e+09,3947.0,6.0,NYG,0.00,0.00,0.01,autoevent_ballsnap
685721,47801,6-3,305,Garrett Bradbury,2.021100e+09,4103.0,6.0,MIN,0.00,0.00,0.02,ball_snap
400852,43695,6-3,313,Matt Skura,2.021100e+09,3947.0,7.0,NYG,0.00,0.00,0.00,ball_snap
268582,42476,6-4,309,Max Garcia,2.021100e+09,2342.0,1.0,ARI,0.00,0.00,0.00,man_in_motion
684790,47801,6-3,305,Garrett Bradbury,2.021100e+09,1807.0,6.0,MIN,0.00,0.00,0.00,ball_snap

## Guards

In [14]:
week4_players_G = week4_players[week4_players['officialPosition'] == 'G']
week4_players_G

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
27379,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021100e+09,156.0,1.0,...,TEN,right,51.86,31.64,0.00,0.00,0.00,110.71,24.68,None
27380,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021100e+09,156.0,2.0,...,TEN,right,51.86,31.65,0.00,0.00,0.00,109.60,24.14,None
27381,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021100e+09,156.0,3.0,...,TEN,right,51.86,31.65,0.03,0.41,0.01,108.28,12.61,None
27382,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021100e+09,156.0,4.0,...,TEN,right,51.86,31.67,0.15,1.03,0.02,107.08,19.32,None
27383,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021100e+09,156.0,5.0,...,TEN,right,51.88,31.71,0.42,1.91,0.04,106.25,18.27,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025253,53655,6-6,325,NaN,NaN,G,Trey Smith,2.021100e+09,4190.0,41.0,...,KC,right,66.22,30.94,2.53,1.60,0.26,125.16,171.46,None
1025254,53655,6-6,325,NaN,NaN,G,Trey Smith,2.021100e+09,4190.0,42.0,...,KC,right,66.25,30.70,2.40,1.85,0.25,121.92,174.83,None
1025255,53655,6-6,325,NaN,NaN,G,Trey Smith,2.021100e+09,4190.0,43.0,...,KC,right,66.26,30.46,2.24,2.12,0.23,117.95,178.97,None
1026284,53861,6-5,330,NaN,NaN,G,Robert Jones,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1026956,53954,6-5,319,NaN,NaN,G,Tommy Kraemer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
week4_players_G = week4_players_G[week4_players_G['event'] != 'None']
week4_players_G

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
27384,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021100e+09,156.0,6.0,...,TEN,right,51.89,31.78,0.74,2.25,0.07,104.83,15.62,ball_snap
27394,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021100e+09,156.0,16.0,...,TEN,right,51.75,33.97,2.97,0.52,0.32,52.44,349.03,play_action
27436,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021100e+09,156.0,58.0,...,TEN,right,50.57,44.42,1.34,0.19,0.14,156.68,150.86,run
27447,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021100e+09,203.0,6.0,...,TEN,right,63.00,25.58,0.41,1.16,0.04,123.95,88.27,ball_snap
27449,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021100e+09,203.0,8.0,...,TEN,right,63.11,25.58,0.60,0.58,0.06,123.95,88.43,autoevent_ballsnap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025218,53655,6-6,325,NaN,NaN,G,Trey Smith,2.021100e+09,4190.0,6.0,...,KC,right,64.92,28.04,0.10,1.03,0.01,107.52,24.24,ball_snap
1025226,53655,6-6,325,NaN,NaN,G,Trey Smith,2.021100e+09,4190.0,14.0,...,KC,right,65.13,29.27,2.66,1.16,0.28,66.10,4.94,play_action
1025250,53655,6-6,325,NaN,NaN,G,Trey Smith,2.021100e+09,4190.0,38.0,...,KC,right,66.06,31.72,2.70,1.02,0.29,129.32,161.31,pass_forward
1026284,53861,6-5,330,NaN,NaN,G,Robert Jones,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1026956,53954,6-5,319,NaN,NaN,G,Tommy Kraemer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
week4_players_G = week4_players_G.sort_values('a', ascending = False)

In [17]:
week4_players_G = week4_players_G.dropna()

In [18]:
cleaned_G = week4_players_G[['nflId', 'height', 'weight', 'displayName', 'gameId', 'playId', 'frameId', 'team', 's', 'a', 'dis', 'event']]
cleaned_G

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,dis,event
302112,43045,6-4,330,Quinton Spain,2.021093e+09,1836.0,12.0,CIN,2.63,5.32,0.25,man_in_motion
746749,47906,6-4,310,Ben Powers,2.021100e+09,1961.0,32.0,BAL,1.25,5.11,0.14,autoevent_passforward
872133,52517,6-4,330,John Simpson,2.021100e+09,644.0,20.0,LV,3.48,4.57,0.35,play_action
134078,40124,6-5,310,David Quessenberry,2.021100e+09,4824.0,41.0,TEN,1.43,3.96,0.16,qb_sack
132296,40124,6-5,310,David Quessenberry,2.021100e+09,203.0,50.0,TEN,1.54,3.87,0.17,qb_sack
...,...,...,...,...,...,...,...,...,...,...,...,...
180372,41324,6-6,301,Michael Schofield,2.021100e+09,2659.0,6.0,LAC,0.00,0.00,0.01,ball_snap
375524,43453,6-6,320,Halapoulivaati Vaitai,2.021100e+09,3773.0,6.0,DET,0.00,0.00,0.01,ball_snap
375573,43453,6-6,320,Halapoulivaati Vaitai,2.021100e+09,3795.0,6.0,DET,0.00,0.00,0.00,ball_snap
375643,43453,6-6,320,Halapoulivaati Vaitai,2.021100e+09,3860.0,6.0,DET,0.00,0.00,0.01,ball_snap
857302,52483,6-4,305,Jonah Jackson,2.021100e+09,3982.0,6.0,DET,0.00,0.00,0.00,ball_snap

## Tackles

In [19]:
week4_players_T = week4_players[week4_players['officialPosition'] == 'T']
week4_players_T

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
2960,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021100e+09,97.0,1.0,...,CHI,left,73.62,26.47,0.00,0.00,0.01,272.28,196.97,None
2961,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021100e+09,97.0,2.0,...,CHI,left,73.62,26.47,0.00,0.00,0.00,272.28,196.36,None
2962,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021100e+09,97.0,3.0,...,CHI,left,73.62,26.47,0.00,0.00,0.01,273.10,193.91,None
2963,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021100e+09,97.0,4.0,...,CHI,left,73.63,26.47,0.00,0.00,0.01,271.62,188.01,None
2964,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021100e+09,97.0,5.0,...,CHI,left,73.65,26.46,0.00,0.00,0.02,270.28,178.31,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1028383,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021100e+09,3338.0,32.0,...,SEA,right,51.61,21.65,3.70,2.87,0.39,56.19,314.44,None
1028384,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021100e+09,3338.0,33.0,...,SEA,right,51.39,22.00,3.77,3.08,0.42,42.46,323.52,None
1028385,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021100e+09,3338.0,34.0,...,SEA,right,51.20,22.34,3.75,2.89,0.39,46.08,329.47,None
1028386,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021100e+09,3338.0,35.0,...,SEA,right,51.09,22.73,3.79,3.07,0.41,30.78,338.78,None
1028387,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021100e+09,3338.0,36.0,...,SEA,right,50.98,23.10,3.77,2.95,0.39,39.98,344.51,None

In [20]:
week4_players_T = week4_players_T[week4_players_T['event'] != 'None']
week4_players_T

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
2965,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021100e+09,97.0,6.0,...,CHI,left,73.66,26.45,0.02,0.51,0.02,268.33,124.23,ball_snap
2975,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021100e+09,97.0,16.0,...,CHI,left,75.50,25.56,3.11,0.07,0.32,291.86,114.85,play_action
2988,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021100e+09,97.0,29.0,...,CHI,left,77.22,25.18,1.12,1.63,0.11,282.15,343.72,pass_forward
2989,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021100e+09,97.0,30.0,...,CHI,left,77.18,25.30,1.27,1.16,0.12,286.62,340.63,autoevent_passforward
2993,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021100e+09,97.0,34.0,...,CHI,left,76.87,25.86,1.64,0.49,0.17,335.59,328.04,pass_arrived
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1028346,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021100e+09,3268.0,41.0,...,SEA,right,57.90,27.49,0.37,2.13,0.04,15.03,249.99,autoevent_passforward
1028347,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021100e+09,3268.0,42.0,...,SEA,right,57.88,27.53,0.52,2.80,0.05,8.91,336.33,pass_forward
1028357,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021100e+09,3338.0,6.0,...,SEA,right,58.52,20.84,0.00,0.00,0.01,77.48,279.77,autoevent_ballsnap
1028358,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021100e+09,3338.0,7.0,...,SEA,right,58.51,20.83,0.01,0.42,0.01,86.85,235.57,ball_snap
1028382,54006,6-6,330,NaN,NaN,T,Jake Curhan,2.021100e+09,3338.0,31.0,...,SEA,right,51.88,21.36,3.73,2.81,0.41,55.44,307.77,pass_forward

In [21]:
week4_players_T = week4_players_T.sort_values('a', ascending = False)

In [22]:
week4_players_T = week4_players_T.dropna()

In [23]:
cleaned_T = week4_players_T[['nflId', 'height', 'weight', 'displayName', 'gameId', 'playId', 'frameId', 'team', 's', 'a', 'dis', 'event']]
cleaned_T

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,dis,event
6679,30869,6-7,330,Andrew Whitworth,2.021100e+09,3567.0,10.0,LA,1.53,5.20,0.13,autoevent_ballsnap
225417,42367,6-5,307,D.J. Humphries,2.021100e+09,2078.0,34.0,ARI,0.95,4.78,0.10,pass_arrived
455881,44876,6-5,325,Taylor Moton,2.021100e+09,2299.0,35.0,CAR,0.77,4.51,0.07,pass_forward
559159,46092,6-2,310,Isaiah Wynn,2.021100e+09,3134.0,7.0,NE,0.99,4.35,0.07,autoevent_ballsnap
550386,46084,6-8,325,Kolton Miller,2.021100e+09,1384.0,32.0,LV,1.23,4.33,0.12,autoevent_passforward
...,...,...,...,...,...,...,...,...,...,...,...,...
311985,43297,6-6,308,Jack Conklin,2.021100e+09,2393.0,6.0,CLE,0.00,0.00,0.00,ball_snap
775380,48181,6-7,314,Yosuah Nijman,2.021100e+09,401.0,6.0,GB,0.00,0.00,0.00,ball_snap
311923,43297,6-6,308,Jack Conklin,2.021100e+09,2252.0,6.0,CLE,0.00,0.00,0.01,ball_snap
311760,43297,6-6,308,Jack Conklin,2.021100e+09,2052.0,6.0,CLE,0.00,0.00,0.02,ball_snap
225591,42367,6-5,307,D.J. Humphries,2.021100e+09,2342.0,1.0,ARI,0.00,0.00,0.00,man_in_motion

## Plays, PFF, & Games data added

In [24]:
plays_df = pd.read_csv(plays_data_to_load)
plays_df

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,defensiveTeam,yardlineSide,yardlineNumber,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,2021090900,97,(13:33) (Shotgun) T.Brady pass incomplete deep...,1,3,2,TB,DAL,TB,33,...,NaN,43.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
1,2021090900,137,(13:18) (Shotgun) D.Prescott pass deep left to...,1,1,10,DAL,TB,DAL,2,...,NaN,108.0,EMPTY,"1 RB, 2 TE, 2 WR",6.0,"4 DL, 4 LB, 3 DB",TRADITIONAL,0,Cover-3,Zone
2,2021090900,187,(12:23) (Shotgun) D.Prescott pass short middle...,1,2,6,DAL,TB,DAL,34,...,NaN,76.0,SHOTGUN,"0 RB, 2 TE, 3 WR",6.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,0,Cover-3,Zone
3,2021090900,282,(9:56) D.Prescott pass incomplete deep left to...,1,1,10,DAL,TB,TB,39,...,NaN,49.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",6.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1,Cover-3,Zone
4,2021090900,349,(9:46) (Shotgun) D.Prescott pass incomplete sh...,1,3,15,DAL,TB,TB,44,...,NaN,54.0,SHOTGUN,"1 RB, 1 TE, 3 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,0,Cover-3,Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8552,2021110100,4310,(1:56) (Shotgun) P.Mahomes sacked at NYG 16 fo...,4,3,8,KC,NYG,NYG,8,...,NaN,18.0,SHOTGUN,"1 RB, 1 TE, 3 WR",4.0,"1 DL, 3 LB, 7 DB",SCRAMBLE,0,Bracket,Other
8553,2021110100,4363,(1:07) (Shotgun) D.Jones pass short right to E...,4,1,10,NYG,KC,NYG,25,...,NaN,35.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"4 DL, 1 LB, 6 DB",SCRAMBLE,0,Cover-2,Zone
8554,2021110100,4392,"(1:01) (No Huddle, Shotgun) D.Jones sacked at ...",4,2,7,NYG,KC,NYG,28,...,NaN,38.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Cover-2,Zone
8555,2021110100,4411,"(:39) (No Huddle, Shotgun) D.Jones pass incomp...",4,3,15,NYG,KC,NYG,20,...,NaN,30.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Cover-2,Zone
8556,2021110100,4433,(:35) (Shotgun) D.Jones sacked at NYG 14 for -...,4,4,15,NYG,KC,NYG,20,...,NaN,30.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Quarters,Zone

In [25]:
pff_df = pd.read_csv(pff_data_to_load)
pff_df

,gameId,playId,nflId,pff_role,pff_positionLinedUp,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,2021090900,97,25511,Pass,QB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021090900,97,35481,Pass Route,TE-L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021090900,97,35634,Pass Route,LWR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021090900,97,39985,Pass Route,HB-R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021090900,97,40151,Pass Block,C,NaN,NaN,NaN,0.0,0.0,0.0,0.0,44955.0,SW,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188249,2021110100,4433,52507,Pass Block,LT,NaN,NaN,NaN,0.0,0.0,1.0,0.0,43338.0,PP,0.0
188250,2021110100,4433,52546,Coverage,SCBoR,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188251,2021110100,4433,52573,Pass Route,SLoWR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188252,2021110100,4433,52585,Pass Rush,LEO,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188253,2021110100,4433,53449,Pass Route,LWR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
games_df = pd.read_csv(games_data_to_load)
games_df

,gameId,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,2021090900,2021,1,09/09/2021,20:20:00,TB,DAL
1,2021091200,2021,1,09/12/2021,13:00:00,ATL,PHI
2,2021091201,2021,1,09/12/2021,13:00:00,BUF,PIT
3,2021091202,2021,1,09/12/2021,13:00:00,CAR,NYJ
4,2021091203,2021,1,09/12/2021,13:00:00,CIN,MIN
...,...,...,...,...,...,...,...
117,2021103109,2021,8,10/31/2021,16:05:00,SEA,JAX
118,2021103110,2021,8,10/31/2021,16:25:00,DEN,WAS
119,2021103111,2021,8,10/31/2021,16:25:00,NO,TB
120,2021103112,2021,8,10/31/2021,20:20:00,MIN,DAL
121,2021110100,2021,8,11/01/2021,20:15:00,KC,NYG

# Merging all data & Cleaning

## Center

In [28]:
w4_C = cleaned_C.merge(plays_df, how="left")
w4_C.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,42476,6-4,309,Max Garcia,2.021100e+09,541.0,39.0,ARI,1.03,4.05,...,NaN,40.0,SHOTGUN,"1 RB, 2 TE, 2 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,1,Cover-6,Zone
1,43307,6-4,309,Ryan Kelly,2.021100e+09,1629.0,31.0,IND,2.00,3.91,...,NaN,34.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"2 DL, 3 LB, 6 DB",TRADITIONAL,0,Cover-1,Man
2,52486,6-4,290,Matt Hennessy,2.021100e+09,208.0,6.0,ATL,0.80,3.85,...,NaN,49.0,SHOTGUN,"1 RB, 2 TE, 2 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,1,Cover-2,Zone
3,52894,6-4,315,Trystan Colon,2.021100e+09,3829.0,44.0,BAL,3.92,3.84,...,NaN,108.0,JUMBO,"6 OL, 2 RB, 2 TE, 0 WR",10.0,"3 DL, 5 LB, 3 DB",TRADITIONAL,1,Red Zone,Other
4,42476,6-4,309,Max Garcia,2.021100e+09,541.0,40.0,ARI,1.17,3.80,...,NaN,40.0,SHOTGUN,"1 RB, 2 TE, 2 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,1,Cover-6,Zone

In [29]:
w4_C.drop(columns=[['possessionTeam','pff_passCoverage','pff_passCoverageType']], inplace=True, errors='ignore')

In [33]:
w4_C = w4_C.merge(pff_df, how='left')
w4_C.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,42476,6-4,309,Max Garcia,2.021100e+09,541.0,39.0,ARI,1.03,4.05,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,41239.0,PT,0.0
1,43307,6-4,309,Ryan Kelly,2.021100e+09,1629.0,31.0,IND,2.00,3.91,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,45274.0,SW,0.0
2,52486,6-4,290,Matt Hennessy,2.021100e+09,208.0,6.0,ATL,0.80,3.85,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,46232.0,PA,0.0
3,52894,6-4,315,Trystan Colon,2.021100e+09,3829.0,44.0,BAL,3.92,3.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,42476,6-4,309,Max Garcia,2.021100e+09,541.0,40.0,ARI,1.17,3.80,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,41239.0,PT,0.0

In [34]:
w4_C = w4_C.merge(games_df, how='left')
w4_C.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,42476,6-4,309,Max Garcia,2.021100e+09,541.0,39.0,ARI,1.03,4.05,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,41239.0,PT,0.0
1,43307,6-4,309,Ryan Kelly,2.021100e+09,1629.0,31.0,IND,2.00,3.91,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,45274.0,SW,0.0
2,52486,6-4,290,Matt Hennessy,2.021100e+09,208.0,6.0,ATL,0.80,3.85,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,46232.0,PA,0.0
3,52894,6-4,315,Trystan Colon,2.021100e+09,3829.0,44.0,BAL,3.92,3.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,42476,6-4,309,Max Garcia,2.021100e+09,541.0,40.0,ARI,1.17,3.80,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,41239.0,PT,0.0

In [35]:
w4_C.drop(columns=['homeTeamAbbr', 'visitorTeamAbbr','gameDate', 'gameTimeEastern', 'season'], inplace=True, errors='ignore')
w4_C

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,42476,6-4,309,Max Garcia,2.021100e+09,541.0,39.0,ARI,1.03,4.05,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,41239.0,PT,0.0
1,43307,6-4,309,Ryan Kelly,2.021100e+09,1629.0,31.0,IND,2.00,3.91,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,45274.0,SW,0.0
2,52486,6-4,290,Matt Hennessy,2.021100e+09,208.0,6.0,ATL,0.80,3.85,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,46232.0,PA,0.0
3,52894,6-4,315,Trystan Colon,2.021100e+09,3829.0,44.0,BAL,3.92,3.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,42476,6-4,309,Max Garcia,2.021100e+09,541.0,40.0,ARI,1.17,3.80,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,41239.0,PT,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3421,43695,6-3,313,Matt Skura,2.021100e+09,3947.0,6.0,NYG,0.00,0.00,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,48599.0,PT,0.0
3422,47801,6-3,305,Garrett Bradbury,2.021100e+09,4103.0,6.0,MIN,0.00,0.00,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,52496.0,PP,0.0
3423,43695,6-3,313,Matt Skura,2.021100e+09,3947.0,7.0,NYG,0.00,0.00,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,48599.0,PT,0.0
3424,42476,6-4,309,Max Garcia,2.021100e+09,2342.0,1.0,ARI,0.00,0.00,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,41239.0,PT,0.0
3425,47801,6-3,305,Garrett Bradbury,2.021100e+09,1807.0,6.0,MIN,0.00,0.00,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NB,0.0

In [36]:
w4_C.to_csv('Resources/center_w4.csv', sep=',', index=False)

In [37]:
w4_C_df = pd.read_csv('Resources/center_w4.csv')
w4_C_df.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,42476,6-4,309,Max Garcia,2.021100e+09,541.0,39.0,ARI,1.03,4.05,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,41239.0,PT,0.0
1,43307,6-4,309,Ryan Kelly,2.021100e+09,1629.0,31.0,IND,2.00,3.91,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,45274.0,SW,0.0
2,52486,6-4,290,Matt Hennessy,2.021100e+09,208.0,6.0,ATL,0.80,3.85,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,46232.0,PA,0.0
3,52894,6-4,315,Trystan Colon,2.021100e+09,3829.0,44.0,BAL,3.92,3.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,42476,6-4,309,Max Garcia,2.021100e+09,541.0,40.0,ARI,1.17,3.80,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,41239.0,PT,0.0

## Guard

In [38]:
w4_G = cleaned_G.merge(plays_df, how="left")
w4_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,43045,6-4,330,Quinton Spain,2.021093e+09,1836.0,12.0,CIN,2.63,5.32,...,NaN,32.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",8.0,"3 DL, 4 LB, 4 DB",DESIGNED_ROLLOUT_LEFT,1,Cover-1,Man
1,47906,6-4,310,Ben Powers,2.021100e+09,1961.0,32.0,BAL,1.25,5.11,...,NaN,23.0,EMPTY,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,0,Cover-0,Man
2,52517,6-4,330,John Simpson,2.021100e+09,644.0,20.0,LV,3.48,4.57,...,NaN,87.0,SINGLEBACK,"1 RB, 1 TE, 3 WR",6.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,1,Cover-3,Zone
3,40124,6-5,310,David Quessenberry,2.021100e+09,4824.0,41.0,TEN,1.43,3.96,...,NaN,31.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,0,Quarters,Zone
4,40124,6-5,310,David Quessenberry,2.021100e+09,203.0,50.0,TEN,1.54,3.87,...,NaN,64.0,I_FORM,"2 RB, 1 TE, 2 WR",8.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1,Cover-1,Man

In [39]:
w4_G.drop(columns=[['possessionTeam','pff_passCoverage','pff_passCoverageType']], inplace=True, errors='ignore')
w4_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,43045,6-4,330,Quinton Spain,2.021093e+09,1836.0,12.0,CIN,2.63,5.32,...,NaN,32.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",8.0,"3 DL, 4 LB, 4 DB",DESIGNED_ROLLOUT_LEFT,1,Cover-1,Man
1,47906,6-4,310,Ben Powers,2.021100e+09,1961.0,32.0,BAL,1.25,5.11,...,NaN,23.0,EMPTY,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,0,Cover-0,Man
2,52517,6-4,330,John Simpson,2.021100e+09,644.0,20.0,LV,3.48,4.57,...,NaN,87.0,SINGLEBACK,"1 RB, 1 TE, 3 WR",6.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,1,Cover-3,Zone
3,40124,6-5,310,David Quessenberry,2.021100e+09,4824.0,41.0,TEN,1.43,3.96,...,NaN,31.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,0,Quarters,Zone
4,40124,6-5,310,David Quessenberry,2.021100e+09,203.0,50.0,TEN,1.54,3.87,...,NaN,64.0,I_FORM,"2 RB, 1 TE, 2 WR",8.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1,Cover-1,Man

In [40]:
w4_G = w4_G.merge(pff_df, how='left')
w4_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,43045,6-4,330,Quinton Spain,2.021093e+09,1836.0,12.0,CIN,2.63,5.32,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,42375.0,PA,0.0
1,47906,6-4,310,Ben Powers,2.021100e+09,1961.0,32.0,BAL,1.25,5.11,...,NaN,NaN,NaN,0.0,1.0,0.0,0.0,41464.0,PP,0.0
2,52517,6-4,330,John Simpson,2.021100e+09,644.0,20.0,LV,3.48,4.57,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,35485.0,PA,0.0
3,40124,6-5,310,David Quessenberry,2.021100e+09,4824.0,41.0,TEN,1.43,3.96,...,NaN,NaN,NaN,0.0,0.0,0.0,1.0,53053.0,PP,0.0
4,40124,6-5,310,David Quessenberry,2.021100e+09,203.0,50.0,TEN,1.54,3.87,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,46204.0,PP,0.0

In [41]:
w4_G = w4_G.merge(games_df, how='left')
w4_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,43045,6-4,330,Quinton Spain,2.021093e+09,1836.0,12.0,CIN,2.63,5.32,...,0.0,42375.0,PA,0.0,2021,4,09/30/2021,20:20:00,CIN,JAX
1,47906,6-4,310,Ben Powers,2.021100e+09,1961.0,32.0,BAL,1.25,5.11,...,0.0,41464.0,PP,0.0,2021,4,10/03/2021,16:25:00,DEN,BAL
2,52517,6-4,330,John Simpson,2.021100e+09,644.0,20.0,LV,3.48,4.57,...,0.0,35485.0,PA,0.0,2021,4,10/04/2021,20:15:00,LAC,LV
3,40124,6-5,310,David Quessenberry,2.021100e+09,4824.0,41.0,TEN,1.43,3.96,...,1.0,53053.0,PP,0.0,2021,4,10/03/2021,13:00:00,NYJ,TEN
4,40124,6-5,310,David Quessenberry,2.021100e+09,203.0,50.0,TEN,1.54,3.87,...,0.0,46204.0,PP,0.0,2021,4,10/03/2021,13:00:00,NYJ,TEN

In [42]:
w4_G.drop(columns=['homeTeamAbbr', 'visitorTeamAbbr','gameDate', 'gameTimeEastern', 'season'], inplace=True, errors='ignore')
w4_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,43045,6-4,330,Quinton Spain,2.021093e+09,1836.0,12.0,CIN,2.63,5.32,...,NaN,NaN,0.0,0.0,0.0,0.0,42375.0,PA,0.0,4
1,47906,6-4,310,Ben Powers,2.021100e+09,1961.0,32.0,BAL,1.25,5.11,...,NaN,NaN,0.0,1.0,0.0,0.0,41464.0,PP,0.0,4
2,52517,6-4,330,John Simpson,2.021100e+09,644.0,20.0,LV,3.48,4.57,...,NaN,NaN,0.0,0.0,0.0,0.0,35485.0,PA,0.0,4
3,40124,6-5,310,David Quessenberry,2.021100e+09,4824.0,41.0,TEN,1.43,3.96,...,NaN,NaN,0.0,0.0,0.0,1.0,53053.0,PP,0.0,4
4,40124,6-5,310,David Quessenberry,2.021100e+09,203.0,50.0,TEN,1.54,3.87,...,NaN,NaN,0.0,0.0,1.0,0.0,46204.0,PP,0.0,4

In [43]:
w4_G.to_csv('Resources/guard_w4.csv', sep=',', index=False)

In [44]:
w4_G_df = pd.read_csv('Resources/guard_w4.csv')
w4_G_df.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,43045,6-4,330,Quinton Spain,2.021093e+09,1836.0,12.0,CIN,2.63,5.32,...,NaN,NaN,0.0,0.0,0.0,0.0,42375.0,PA,0.0,4
1,47906,6-4,310,Ben Powers,2.021100e+09,1961.0,32.0,BAL,1.25,5.11,...,NaN,NaN,0.0,1.0,0.0,0.0,41464.0,PP,0.0,4
2,52517,6-4,330,John Simpson,2.021100e+09,644.0,20.0,LV,3.48,4.57,...,NaN,NaN,0.0,0.0,0.0,0.0,35485.0,PA,0.0,4
3,40124,6-5,310,David Quessenberry,2.021100e+09,4824.0,41.0,TEN,1.43,3.96,...,NaN,NaN,0.0,0.0,0.0,1.0,53053.0,PP,0.0,4
4,40124,6-5,310,David Quessenberry,2.021100e+09,203.0,50.0,TEN,1.54,3.87,...,NaN,NaN,0.0,0.0,1.0,0.0,46204.0,PP,0.0,4

## Tackle

In [45]:
w4_T = cleaned_T.merge(plays_df, how="left")
w4_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,30869,6-7,330,Andrew Whitworth,2.021100e+09,3567.0,10.0,LA,1.53,5.20,...,NaN,75.0,EMPTY,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,0,Cover-3,Zone
1,42367,6-5,307,D.J. Humphries,2.021100e+09,2078.0,34.0,ARI,0.95,4.78,...,NaN,83.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,0,Cover-3,Zone
2,44876,6-5,325,Taylor Moton,2.021100e+09,2299.0,35.0,CAR,0.77,4.51,...,NaN,74.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
3,46092,6-2,310,Isaiah Wynn,2.021100e+09,3134.0,7.0,NE,0.99,4.35,...,NaN,67.0,EMPTY,"1 RB, 2 TE, 2 WR",6.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,0,Cover-2,Zone
4,46084,6-8,325,Kolton Miller,2.021100e+09,1384.0,32.0,LV,1.23,4.33,...,NaN,30.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"1 DL, 4 LB, 6 DB",TRADITIONAL,0,2-Man,Man

In [46]:
w4_T.drop(columns=['possessionTeam','pff_passCoverage','pff_passCoverageType'], inplace=True, errors='ignore')
w4_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId2,foulName3,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction
0,30869,6-7,330,Andrew Whitworth,2.021100e+09,3567.0,10.0,LA,1.53,5.20,...,NaN,NaN,NaN,75.0,EMPTY,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,0
1,42367,6-5,307,D.J. Humphries,2.021100e+09,2078.0,34.0,ARI,0.95,4.78,...,NaN,NaN,NaN,83.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,0
2,44876,6-5,325,Taylor Moton,2.021100e+09,2299.0,35.0,CAR,0.77,4.51,...,NaN,NaN,NaN,74.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0
3,46092,6-2,310,Isaiah Wynn,2.021100e+09,3134.0,7.0,NE,0.99,4.35,...,NaN,NaN,NaN,67.0,EMPTY,"1 RB, 2 TE, 2 WR",6.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,0
4,46084,6-8,325,Kolton Miller,2.021100e+09,1384.0,32.0,LV,1.23,4.33,...,NaN,NaN,NaN,30.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"1 DL, 4 LB, 6 DB",TRADITIONAL,0

In [47]:
w4_T = w4_T.merge(pff_df, how='left')
w4_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,30869,6-7,330,Andrew Whitworth,2.021100e+09,3567.0,10.0,LA,1.53,5.20,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,41403.0,PT,0.0
1,42367,6-5,307,D.J. Humphries,2.021100e+09,2078.0,34.0,ARI,0.95,4.78,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,46229.0,PP,0.0
2,44876,6-5,325,Taylor Moton,2.021100e+09,2299.0,35.0,CAR,0.77,4.51,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,53513.0,PP,0.0
3,46092,6-2,310,Isaiah Wynn,2.021100e+09,3134.0,7.0,NE,0.99,4.35,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,47890.0,PP,0.0
4,46084,6-8,325,Kolton Miller,2.021100e+09,1384.0,32.0,LV,1.23,4.33,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,43377.0,PP,0.0

In [48]:
w4_T = w4_T.merge(games_df, how='left')
w4_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,30869,6-7,330,Andrew Whitworth,2.021100e+09,3567.0,10.0,LA,1.53,5.20,...,0.0,41403.0,PT,0.0,2021,4,10/03/2021,16:05:00,LA,ARI
1,42367,6-5,307,D.J. Humphries,2.021100e+09,2078.0,34.0,ARI,0.95,4.78,...,0.0,46229.0,PP,0.0,2021,4,10/03/2021,16:05:00,LA,ARI
2,44876,6-5,325,Taylor Moton,2.021100e+09,2299.0,35.0,CAR,0.77,4.51,...,0.0,53513.0,PP,0.0,2021,4,10/03/2021,13:00:00,DAL,CAR
3,46092,6-2,310,Isaiah Wynn,2.021100e+09,3134.0,7.0,NE,0.99,4.35,...,0.0,47890.0,PP,0.0,2021,4,10/03/2021,20:20:00,NE,TB
4,46084,6-8,325,Kolton Miller,2.021100e+09,1384.0,32.0,LV,1.23,4.33,...,0.0,43377.0,PP,0.0,2021,4,10/04/2021,20:15:00,LAC,LV

In [49]:
w4_T.drop(columns=['homeTeamAbbr', 'visitorTeamAbbr','gameDate', 'gameTimeEastern', 'season'], inplace=True, errors='ignore')
w4_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,30869,6-7,330,Andrew Whitworth,2.021100e+09,3567.0,10.0,LA,1.53,5.20,...,NaN,NaN,0.0,0.0,0.0,0.0,41403.0,PT,0.0,4
1,42367,6-5,307,D.J. Humphries,2.021100e+09,2078.0,34.0,ARI,0.95,4.78,...,NaN,NaN,0.0,0.0,0.0,0.0,46229.0,PP,0.0,4
2,44876,6-5,325,Taylor Moton,2.021100e+09,2299.0,35.0,CAR,0.77,4.51,...,NaN,NaN,0.0,0.0,0.0,0.0,53513.0,PP,0.0,4
3,46092,6-2,310,Isaiah Wynn,2.021100e+09,3134.0,7.0,NE,0.99,4.35,...,NaN,NaN,0.0,0.0,0.0,0.0,47890.0,PP,0.0,4
4,46084,6-8,325,Kolton Miller,2.021100e+09,1384.0,32.0,LV,1.23,4.33,...,NaN,NaN,0.0,0.0,0.0,0.0,43377.0,PP,0.0,4

In [50]:
w4_T.to_csv('Resources/tackle_w4.csv', sep=',', index=False)

In [51]:
w4_T_df = pd.read_csv('Resources/tackle_w4.csv')
w4_T_df.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,30869,6-7,330,Andrew Whitworth,2.021100e+09,3567.0,10.0,LA,1.53,5.20,...,NaN,NaN,0.0,0.0,0.0,0.0,41403.0,PT,0.0,4
1,42367,6-5,307,D.J. Humphries,2.021100e+09,2078.0,34.0,ARI,0.95,4.78,...,NaN,NaN,0.0,0.0,0.0,0.0,46229.0,PP,0.0,4
2,44876,6-5,325,Taylor Moton,2.021100e+09,2299.0,35.0,CAR,0.77,4.51,...,NaN,NaN,0.0,0.0,0.0,0.0,53513.0,PP,0.0,4
3,46092,6-2,310,Isaiah Wynn,2.021100e+09,3134.0,7.0,NE,0.99,4.35,...,NaN,NaN,0.0,0.0,0.0,0.0,47890.0,PP,0.0,4
4,46084,6-8,325,Kolton Miller,2.021100e+09,1384.0,32.0,LV,1.23,4.33,...,NaN,NaN,0.0,0.0,0.0,0.0,43377.0,PP,0.0,4