In [1]:
import csv
import os
import pandas as pd
import numpy as np

In [2]:
players_data_to_load = "players.csv"
week2_data_to_load = "week2.csv"
plays_data_to_load = "plays.csv"
pff_data_to_load = "pffScoutingData.csv"
games_data_to_load = "games.csv"

In [3]:
players_df = pd.read_csv(players_data_to_load)
players_df

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName
0,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady
1,28963,6-5,240,1982-03-02,"Miami, O.",QB,Ben Roethlisberger
2,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters
3,29851,6-2,225,1983-12-02,California,QB,Aaron Rodgers
4,30078,6-2,228,1982-11-24,Harvard,QB,Ryan Fitzpatrick
...,...,...,...,...,...,...,...
1674,53991,6-1,320,NaN,NaN,DT,Forrest Merrill
1675,53994,6-5,300,NaN,NaN,C,Ryan McCollum
1676,53999,6-4,312,NaN,NaN,DT,Jack Heflin
1677,54006,6-6,330,NaN,NaN,T,Jake Curhan
1678,54038,6-6,245,NaN,NaN,QB,Feleipe Franks

In [4]:
week2_df = pd.read_csv(week2_data_to_load)
week2_df

,gameId,playId,nflId,frameId,time,jerseyNumber,team,playDirection,x,y,s,a,dis,o,dir,event
0,2021091600,65,40031.0,1,2021-09-17T00:23:09.600,23.0,NYG,right,46.32,22.36,0.93,0.83,0.09,271.71,79.32,None
1,2021091600,65,40031.0,2,2021-09-17T00:23:09.700,23.0,NYG,right,46.43,22.39,1.07,1.05,0.11,275.92,72.33,None
2,2021091600,65,40031.0,3,2021-09-17T00:23:09.800,23.0,NYG,right,46.54,22.44,1.21,1.11,0.12,278.85,67.03,None
3,2021091600,65,40031.0,4,2021-09-17T00:23:09.900,23.0,NYG,right,46.65,22.49,1.32,1.14,0.13,282.45,62.63,None
4,2021091600,65,40031.0,5,2021-09-17T00:23:10.000,23.0,NYG,right,46.77,22.56,1.49,1.42,0.14,285.54,59.26,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1042769,2021092000,3759,NaN,52,2021-09-21T03:07:54.900,NaN,football,right,69.52,33.13,6.62,3.07,0.65,NaN,NaN,autoevent_passforward
1042770,2021092000,3759,NaN,53,2021-09-21T03:07:55.000,NaN,football,right,70.09,33.56,7.12,2.61,0.71,NaN,NaN,None
1042771,2021092000,3759,NaN,54,2021-09-21T03:07:55.100,NaN,football,right,75.23,35.47,22.95,0.86,5.48,NaN,NaN,None
1042772,2021092000,3759,NaN,55,2021-09-21T03:07:55.200,NaN,football,right,77.35,36.43,22.87,1.26,2.33,NaN,NaN,None
1042773,2021092000,3759,NaN,56,2021-09-21T03:07:55.300,NaN,football,right,79.42,37.39,22.79,1.59,2.29,NaN,NaN,None

In [5]:
week2_players = players_df.merge(week2_df, how='left')
week2_players

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
0,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021092e+09,54.0,1.0,...,TB,right,33.36,27.02,0.0,0.0,0.01,117.37,29.50,None
1,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021092e+09,54.0,2.0,...,TB,right,33.35,27.01,0.0,0.0,0.01,119.40,14.57,None
2,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021092e+09,54.0,3.0,...,TB,right,33.35,27.01,0.0,0.0,0.00,119.40,279.51,None
3,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021092e+09,54.0,4.0,...,TB,right,33.35,27.01,0.0,0.0,0.00,119.40,259.14,None
4,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021092e+09,54.0,5.0,...,TB,right,33.34,27.01,0.0,0.0,0.00,119.40,251.38,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997954,53991,6-1,320,NaN,NaN,DT,Forrest Merrill,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997955,53994,6-5,300,NaN,NaN,C,Ryan McCollum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997956,53999,6-4,312,NaN,NaN,DT,Jack Heflin,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997957,54006,6-6,330,NaN,NaN,T,Jake Curhan,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997958,54038,6-6,245,NaN,NaN,QB,Feleipe Franks,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Centers

In [6]:
week2_players_C = week2_players[week2_players['officialPosition'] == 'C']
week2_players_C

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
14011,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021092e+09,98.0,1.0,...,SF,left,89.47,23.54,0.05,0.27,0.01,259.11,142.18,None
14012,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021092e+09,98.0,2.0,...,SF,left,89.48,23.54,0.10,0.38,0.01,259.99,98.06,None
14013,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021092e+09,98.0,3.0,...,SF,left,89.50,23.54,0.18,0.44,0.02,261.19,94.75,None
14014,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021092e+09,98.0,4.0,...,SF,left,89.53,23.54,0.30,0.56,0.04,263.01,91.98,None
14015,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021092e+09,98.0,5.0,...,SF,left,89.58,23.55,0.43,0.81,0.05,264.69,88.74,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
974730,53516,6-3,310,NaN,NaN,C,Kendrick Green,2.021092e+09,3667.0,34.0,...,PIT,left,53.76,25.47,1.17,1.61,0.12,320.73,107.70,None
974731,53516,6-3,310,NaN,NaN,C,Kendrick Green,2.021092e+09,3667.0,35.0,...,PIT,left,53.86,25.42,1.07,1.64,0.12,317.74,118.29,None
979897,53543,6-3,300,NaN,NaN,C,Drew Dalman,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
989923,53619,6-3,330,NaN,NaN,C,Trey Hill,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997955,53994,6-5,300,NaN,NaN,C,Ryan McCollum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
week2_players_C = week2_players_C[week2_players_C['event'] != 'None']
week2_players_C

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
14016,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021092e+09,98.0,6.0,...,SF,left,89.64,23.56,0.55,0.72,0.06,267.60,83.34,autoevent_ballsnap
14017,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021092e+09,98.0,7.0,...,SF,left,89.72,23.58,0.74,1.02,0.08,271.56,78.21,ball_snap
14040,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021092e+09,98.0,30.0,...,SF,left,92.15,24.16,0.55,0.68,0.05,305.15,100.99,autoevent_passforward
14041,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021092e+09,98.0,31.0,...,SF,left,92.20,24.16,0.43,0.87,0.04,303.90,98.23,pass_forward
14051,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021092e+09,360.0,6.0,...,SF,left,91.63,29.71,0.48,1.09,0.05,272.79,88.53,autoevent_ballsnap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
974726,53516,6-3,310,NaN,NaN,C,Kendrick Green,2.021092e+09,3667.0,30.0,...,PIT,left,53.19,25.55,1.64,1.39,0.17,333.35,87.47,pass_forward
974727,53516,6-3,310,NaN,NaN,C,Kendrick Green,2.021092e+09,3667.0,31.0,...,PIT,left,53.35,25.55,1.57,1.44,0.16,330.94,93.32,autoevent_passforward
979897,53543,6-3,300,NaN,NaN,C,Drew Dalman,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
989923,53619,6-3,330,NaN,NaN,C,Trey Hill,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997955,53994,6-5,300,NaN,NaN,C,Ryan McCollum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
week2_players_C = week2_players_C.sort_values('a', ascending = False)
week2_players_C

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
82492,38629,6-3,308,1989-07-02,Georgia,C,Ben Jones,2.021092e+09,3516.0,37.0,...,TEN,left,62.49,28.38,0.59,5.02,0.08,98.37,107.25,pass_forward
671978,47801,6-3,305,1995-06-20,North Carolina State,C,Garrett Bradbury,2.021092e+09,3433.0,32.0,...,MIN,left,106.46,22.78,2.29,4.32,0.22,343.96,42.97,autoevent_passforward
14235,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021092e+09,1134.0,32.0,...,SF,right,39.76,27.14,1.23,3.77,0.14,145.58,268.71,autoevent_passforward
634854,46284,6-5,317,1994-11-24,Alabama,C,Bradley Bozeman,2.021092e+09,3676.0,47.0,...,BAL,left,16.02,44.09,4.76,3.75,0.49,323.17,6.06,autoevent_passinterrupted
14236,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021092e+09,1134.0,33.0,...,SF,right,39.68,27.14,0.72,3.67,0.08,138.02,278.60,pass_forward
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
772722,48512,6-4,300,1997-02-14,Penn State,C,Ryan Bates,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
872680,52564,6-3,310,1998-07-25,San Diego State,C,Keith Ismael,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
979897,53543,6-3,300,NaN,NaN,C,Drew Dalman,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
989923,53619,6-3,330,NaN,NaN,C,Trey Hill,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997955,53994,6-5,300,NaN,NaN,C,Ryan McCollum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
week2_players_C = week2_players_C.dropna()

In [11]:
cleaned_C= week2_players_C[['nflId', 'height', 'weight', 'displayName', 'gameId', 'playId', 'frameId', 'team', 's', 'a', 'dis', 'event']]
cleaned_C

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,dis,event
82492,38629,6-3,308,Ben Jones,2.021092e+09,3516.0,37.0,TEN,0.59,5.02,0.08,pass_forward
671978,47801,6-3,305,Garrett Bradbury,2.021092e+09,3433.0,32.0,MIN,2.29,4.32,0.22,autoevent_passforward
14235,34472,6-4,311,Alex Mack,2.021092e+09,1134.0,32.0,SF,1.23,3.77,0.14,autoevent_passforward
634854,46284,6-5,317,Bradley Bozeman,2.021092e+09,3676.0,47.0,BAL,4.76,3.75,0.49,autoevent_passinterrupted
14236,34472,6-4,311,Alex Mack,2.021092e+09,1134.0,33.0,SF,0.72,3.67,0.08,pass_forward
...,...,...,...,...,...,...,...,...,...,...,...,...
545698,46089,6-5,311,Frank Ragnow,2.021092e+09,2959.0,6.0,DET,0.00,0.00,0.01,ball_snap
545699,46089,6-5,311,Frank Ragnow,2.021092e+09,2959.0,7.0,DET,0.00,0.00,0.01,autoevent_ballsnap
187372,41390,6-3,301,Corey Linsley,2.021092e+09,3066.0,6.0,LAC,0.00,0.00,0.01,ball_snap
849861,52491,6-4,315,Lloyd Cushenberry,2.021092e+09,2120.0,7.0,DEN,0.00,0.00,0.00,autoevent_ballsnap
122103,40070,6-4,307,J.C. Tretter,2.021092e+09,164.0,6.0,CLE,0.00,0.00,0.01,ball_snap

## Guards

In [12]:
week2_players_G = week2_players[week2_players['officialPosition'] == 'G']
week2_players_G

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
26414,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021092e+09,204.0,1.0,...,TEN,left,93.18,28.09,0.00,0.00,0.01,257.82,241.02,None
26415,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021092e+09,204.0,2.0,...,TEN,left,93.18,28.09,0.00,0.00,0.00,257.82,242.11,None
26416,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021092e+09,204.0,3.0,...,TEN,left,93.18,28.09,0.00,0.00,0.00,257.82,237.28,None
26417,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021092e+09,204.0,4.0,...,TEN,left,93.18,28.08,0.01,0.15,0.01,257.82,169.77,None
26418,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021092e+09,204.0,5.0,...,TEN,left,93.19,28.07,0.06,0.55,0.01,257.82,154.06,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996782,53861,6-5,330,NaN,NaN,G,Robert Jones,2.021092e+09,4203.0,57.0,...,MIA,right,88.32,29.47,3.11,0.16,0.33,58.25,45.18,None
996783,53861,6-5,330,NaN,NaN,G,Robert Jones,2.021092e+09,4203.0,58.0,...,MIA,right,88.56,29.71,3.19,0.38,0.34,59.21,44.96,None
996784,53861,6-5,330,NaN,NaN,G,Robert Jones,2.021092e+09,4203.0,59.0,...,MIA,right,88.80,29.94,3.24,0.59,0.34,59.21,45.18,None
996785,53861,6-5,330,NaN,NaN,G,Robert Jones,2.021092e+09,4203.0,60.0,...,MIA,right,89.04,30.20,3.30,0.76,0.35,56.12,44.70,None
997107,53954,6-5,319,NaN,NaN,G,Tommy Kraemer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
week2_players_G = week2_players_G[week2_players_G['event'] != 'None']
week2_players_G

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
26419,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021092e+09,204.0,6.0,...,TEN,left,93.20,28.06,0.17,0.88,0.02,257.82,148.12,autoevent_ballsnap
26420,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021092e+09,204.0,7.0,...,TEN,left,93.22,28.04,0.31,1.05,0.03,257.82,147.05,ball_snap
26442,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021092e+09,204.0,29.0,...,TEN,left,95.68,27.88,1.16,1.68,0.12,218.82,93.03,autoevent_passforward
26444,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021092e+09,204.0,31.0,...,TEN,left,95.85,27.83,0.80,1.81,0.08,220.92,115.40,pass_forward
26453,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021092e+09,391.0,6.0,...,TEN,left,96.53,28.05,0.13,0.93,0.01,311.26,251.09,autoevent_ballsnap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996720,53861,6-5,330,NaN,NaN,G,Robert Jones,2.021092e+09,4175.0,33.0,...,MIA,right,86.16,23.65,0.43,1.76,0.04,70.21,298.20,pass_forward
996725,53861,6-5,330,NaN,NaN,G,Robert Jones,2.021092e+09,4175.0,38.0,...,MIA,right,86.46,23.76,1.20,1.92,0.11,68.18,83.28,pass_arrived
996731,53861,6-5,330,NaN,NaN,G,Robert Jones,2.021092e+09,4203.0,6.0,...,MIA,right,89.40,25.64,0.22,0.53,0.03,95.16,299.49,ball_snap
996780,53861,6-5,330,NaN,NaN,G,Robert Jones,2.021092e+09,4203.0,55.0,...,MIA,right,87.86,29.00,2.77,0.10,0.29,55.96,44.77,pass_forward
997107,53954,6-5,319,NaN,NaN,G,Tommy Kraemer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
week2_players_G = week2_players_G.sort_values('a', ascending = False)

In [15]:
week2_players_G = week2_players_G.dropna()

In [16]:
cleaned_G = week2_players_G[['nflId', 'height', 'weight', 'displayName', 'gameId', 'playId', 'frameId', 'team', 's', 'a', 'dis', 'event']]
cleaned_G

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,dis,event
845287,52483,6-4,305,Jonah Jackson,2.021092e+09,3546.0,36.0,DET,0.78,4.67,0.08,pass_forward
845286,52483,6-4,305,Jonah Jackson,2.021092e+09,3546.0,35.0,DET,1.34,4.50,0.13,autoevent_passforward
130620,40124,6-5,310,David Quessenberry,2.021092e+09,1746.0,35.0,TEN,0.70,4.45,0.08,pass_forward
130619,40124,6-5,310,David Quessenberry,2.021092e+09,1746.0,34.0,TEN,1.25,4.44,0.13,autoevent_passforward
154165,41242,6-4,315,Zack Martin,2.021092e+09,322.0,36.0,DAL,0.78,4.33,0.08,pass_forward
...,...,...,...,...,...,...,...,...,...,...,...,...
216401,42352,6-6,329,Ereck Flowers,2.021092e+09,111.0,6.0,WAS,0.00,0.00,0.00,ball_snap
298960,43045,6-4,330,Quinton Spain,2.021092e+09,1987.0,6.0,CIN,0.00,0.00,0.00,ball_snap
298929,43045,6-4,330,Quinton Spain,2.021092e+09,1609.0,7.0,CIN,0.00,0.00,0.00,autoevent_ballsnap
298928,43045,6-4,330,Quinton Spain,2.021092e+09,1609.0,6.0,CIN,0.00,0.00,0.01,ball_snap
202149,41939,6-6,325,Andrew Norwell,2.021092e+09,1058.0,6.0,JAX,0.00,0.00,0.00,ball_snap

## Tackles

In [17]:
week2_players_T = week2_players[week2_players['officialPosition'] == 'T']
week2_players_T

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
2664,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021092e+09,59.0,1.0,...,CHI,left,86.67,23.49,0.0,0.0,0.00,199.71,99.82,None
2665,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021092e+09,59.0,2.0,...,CHI,left,86.67,23.49,0.0,0.0,0.00,208.29,103.95,None
2666,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021092e+09,59.0,3.0,...,CHI,left,86.67,23.48,0.0,0.0,0.01,237.85,128.15,None
2667,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021092e+09,59.0,4.0,...,CHI,left,86.67,23.47,0.0,0.0,0.01,253.37,157.67,None
2668,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021092e+09,59.0,5.0,...,CHI,left,86.67,23.46,0.0,0.1,0.01,253.37,167.59,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986368,53584,6-5,315,NaN,NaN,T,Jaylon Moore,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
986986,53590,6-8,315,NaN,NaN,T,Tommy Doyle,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
992445,53635,6-7,305,NaN,NaN,T,Landon Young,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996786,53868,6-6,315,NaN,NaN,T,Alaric Jackson,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997957,54006,6-6,330,NaN,NaN,T,Jake Curhan,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
week2_players_T = week2_players_T[week2_players_T['event'] != 'None']
week2_players_T

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
2669,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021092e+09,59.0,6.0,...,CHI,left,86.67,23.43,0.12,1.45,0.03,241.99,178.88,ball_snap
2670,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021092e+09,59.0,7.0,...,CHI,left,86.67,23.39,0.40,2.23,0.04,248.99,176.46,autoevent_ballsnap
2682,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021092e+09,59.0,19.0,...,CHI,left,87.02,20.63,2.53,1.73,0.26,235.46,166.20,play_action
2728,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021092e+09,59.0,65.0,...,CHI,left,91.42,23.57,3.35,1.52,0.35,340.09,352.86,pass_forward
2729,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021092e+09,59.0,66.0,...,CHI,left,91.38,23.90,3.22,1.66,0.33,337.63,352.85,autoevent_passforward
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986368,53584,6-5,315,NaN,NaN,T,Jaylon Moore,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
986986,53590,6-8,315,NaN,NaN,T,Tommy Doyle,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
992445,53635,6-7,305,NaN,NaN,T,Landon Young,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996786,53868,6-6,315,NaN,NaN,T,Alaric Jackson,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997957,54006,6-6,330,NaN,NaN,T,Jake Curhan,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
week2_players_T = week2_players_T.sort_values('a', ascending = False)

In [20]:
week2_players_T = week2_players_T.dropna()

In [21]:
cleaned_T = week2_players_T[['nflId', 'height', 'weight', 'displayName', 'gameId', 'playId', 'frameId', 'team', 's', 'a', 'dis', 'event']]
cleaned_T

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,dis,event
234578,42377,6-6,338,Donovan Smith,2.021092e+09,1840.0,15.0,TB,1.68,4.75,0.15,play_action
454852,44876,6-5,325,Taylor Moton,2.021092e+09,3355.0,32.0,CAR,1.40,4.64,0.15,autoevent_passforward
454853,44876,6-5,325,Taylor Moton,2.021092e+09,3355.0,33.0,CAR,1.09,4.55,0.12,pass_forward
19621,35443,6-5,320,Trent Williams,2.021092e+09,1215.0,34.0,SF,2.44,4.55,0.25,autoevent_passforward
19620,35443,6-5,320,Trent Williams,2.021092e+09,1215.0,33.0,SF,2.82,4.52,0.29,pass_forward
...,...,...,...,...,...,...,...,...,...,...,...,...
234569,42377,6-6,338,Donovan Smith,2.021092e+09,1840.0,6.0,TB,0.00,0.00,0.02,ball_snap
234460,42377,6-6,338,Donovan Smith,2.021092e+09,1408.0,3.0,TB,0.00,0.00,0.00,ball_snap
792711,52421,6-5,322,Tristan Wirfs,2.021092e+09,3365.0,6.0,TB,0.00,0.00,0.01,ball_snap
234398,42377,6-6,338,Donovan Smith,2.021092e+09,1362.0,6.0,TB,0.00,0.00,0.01,ball_snap
438444,44846,6-6,320,Cam Robinson,2.021092e+09,1058.0,7.0,JAX,0.00,0.00,0.00,autoevent_ballsnap

## Plays, PFF, & Games data added

In [22]:
plays_df = pd.read_csv(plays_data_to_load)
plays_df

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,defensiveTeam,yardlineSide,yardlineNumber,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,2021090900,97,(13:33) (Shotgun) T.Brady pass incomplete deep...,1,3,2,TB,DAL,TB,33,...,NaN,43.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
1,2021090900,137,(13:18) (Shotgun) D.Prescott pass deep left to...,1,1,10,DAL,TB,DAL,2,...,NaN,108.0,EMPTY,"1 RB, 2 TE, 2 WR",6.0,"4 DL, 4 LB, 3 DB",TRADITIONAL,0,Cover-3,Zone
2,2021090900,187,(12:23) (Shotgun) D.Prescott pass short middle...,1,2,6,DAL,TB,DAL,34,...,NaN,76.0,SHOTGUN,"0 RB, 2 TE, 3 WR",6.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,0,Cover-3,Zone
3,2021090900,282,(9:56) D.Prescott pass incomplete deep left to...,1,1,10,DAL,TB,TB,39,...,NaN,49.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",6.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1,Cover-3,Zone
4,2021090900,349,(9:46) (Shotgun) D.Prescott pass incomplete sh...,1,3,15,DAL,TB,TB,44,...,NaN,54.0,SHOTGUN,"1 RB, 1 TE, 3 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,0,Cover-3,Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8552,2021110100,4310,(1:56) (Shotgun) P.Mahomes sacked at NYG 16 fo...,4,3,8,KC,NYG,NYG,8,...,NaN,18.0,SHOTGUN,"1 RB, 1 TE, 3 WR",4.0,"1 DL, 3 LB, 7 DB",SCRAMBLE,0,Bracket,Other
8553,2021110100,4363,(1:07) (Shotgun) D.Jones pass short right to E...,4,1,10,NYG,KC,NYG,25,...,NaN,35.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"4 DL, 1 LB, 6 DB",SCRAMBLE,0,Cover-2,Zone
8554,2021110100,4392,"(1:01) (No Huddle, Shotgun) D.Jones sacked at ...",4,2,7,NYG,KC,NYG,28,...,NaN,38.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Cover-2,Zone
8555,2021110100,4411,"(:39) (No Huddle, Shotgun) D.Jones pass incomp...",4,3,15,NYG,KC,NYG,20,...,NaN,30.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Cover-2,Zone
8556,2021110100,4433,(:35) (Shotgun) D.Jones sacked at NYG 14 for -...,4,4,15,NYG,KC,NYG,20,...,NaN,30.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Quarters,Zone

In [23]:
pff_df = pd.read_csv(pff_data_to_load)
pff_df

,gameId,playId,nflId,pff_role,pff_positionLinedUp,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,2021090900,97,25511,Pass,QB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021090900,97,35481,Pass Route,TE-L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021090900,97,35634,Pass Route,LWR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021090900,97,39985,Pass Route,HB-R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021090900,97,40151,Pass Block,C,NaN,NaN,NaN,0.0,0.0,0.0,0.0,44955.0,SW,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188249,2021110100,4433,52507,Pass Block,LT,NaN,NaN,NaN,0.0,0.0,1.0,0.0,43338.0,PP,0.0
188250,2021110100,4433,52546,Coverage,SCBoR,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188251,2021110100,4433,52573,Pass Route,SLoWR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188252,2021110100,4433,52585,Pass Rush,LEO,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188253,2021110100,4433,53449,Pass Route,LWR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
games_df = pd.read_csv(games_data_to_load)
games_df

,gameId,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,2021090900,2021,1,09/09/2021,20:20:00,TB,DAL
1,2021091200,2021,1,09/12/2021,13:00:00,ATL,PHI
2,2021091201,2021,1,09/12/2021,13:00:00,BUF,PIT
3,2021091202,2021,1,09/12/2021,13:00:00,CAR,NYJ
4,2021091203,2021,1,09/12/2021,13:00:00,CIN,MIN
...,...,...,...,...,...,...,...
117,2021103109,2021,8,10/31/2021,16:05:00,SEA,JAX
118,2021103110,2021,8,10/31/2021,16:25:00,DEN,WAS
119,2021103111,2021,8,10/31/2021,16:25:00,NO,TB
120,2021103112,2021,8,10/31/2021,20:20:00,MIN,DAL
121,2021110100,2021,8,11/01/2021,20:15:00,KC,NYG

# Merging all data & Cleaning

## Center

In [27]:
w2_C = cleaned_C.merge(plays_df, how="left")
w2_C.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,38629,6-3,308,Ben Jones,2.021092e+09,3516.0,37.0,TEN,0.59,5.02,...,NaN,55.0,EMPTY,"1 RB, 1 TE, 3 WR",4.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,0,Quarters,Zone
1,47801,6-3,305,Garrett Bradbury,2.021092e+09,3433.0,32.0,MIN,2.29,4.32,...,NaN,101.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
2,34472,6-4,311,Alex Mack,2.021092e+09,1134.0,32.0,SF,1.23,3.77,...,NaN,47.0,SINGLEBACK,"2 RB, 1 TE, 2 WR",7.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1,Cover-6,Zone
3,46284,6-5,317,Bradley Bozeman,2.021092e+09,3676.0,47.0,BAL,4.76,3.75,...,NaN,12.0,SHOTGUN,"2 RB, 1 TE, 2 WR",7.0,"4 DL, 3 LB, 4 DB",NaN,0,Cover-3,Zone
4,34472,6-4,311,Alex Mack,2.021092e+09,1134.0,33.0,SF,0.72,3.67,...,NaN,47.0,SINGLEBACK,"2 RB, 1 TE, 2 WR",7.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1,Cover-6,Zone

In [28]:
w2_C.drop(columns=[['possessionTeam','pff_passCoverage','pff_passCoverageType']], inplace=True, errors='ignore')

In [30]:
w2_C = w2_C.merge(pff_df, how='left')
w2_C.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,38629,6-3,308,Ben Jones,2.021092e+09,3516.0,37.0,TEN,0.59,5.02,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,41786.0,PP,0.0
1,47801,6-3,305,Garrett Bradbury,2.021092e+09,3433.0,32.0,MIN,2.29,4.32,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,35522.0,SW,0.0
2,34472,6-4,311,Alex Mack,2.021092e+09,1134.0,32.0,SF,1.23,3.77,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,43378.0,PA,0.0
3,46284,6-5,317,Bradley Bozeman,2.021092e+09,3676.0,47.0,BAL,4.76,3.75,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,41348.0,PR,0.0
4,34472,6-4,311,Alex Mack,2.021092e+09,1134.0,33.0,SF,0.72,3.67,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,43378.0,PA,0.0

In [31]:
w2_C = w2_C.merge(games_df, how='left')
w2_C.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,38629,6-3,308,Ben Jones,2.021092e+09,3516.0,37.0,TEN,0.59,5.02,...,0.0,41786.0,PP,0.0,2021,2,09/19/2021,16:25:00,SEA,TEN
1,47801,6-3,305,Garrett Bradbury,2.021092e+09,3433.0,32.0,MIN,2.29,4.32,...,0.0,35522.0,SW,0.0,2021,2,09/19/2021,16:05:00,ARI,MIN
2,34472,6-4,311,Alex Mack,2.021092e+09,1134.0,32.0,SF,1.23,3.77,...,0.0,43378.0,PA,0.0,2021,2,09/19/2021,13:00:00,PHI,SF
3,46284,6-5,317,Bradley Bozeman,2.021092e+09,3676.0,47.0,BAL,4.76,3.75,...,0.0,41348.0,PR,0.0,2021,2,09/19/2021,20:20:00,BAL,KC
4,34472,6-4,311,Alex Mack,2.021092e+09,1134.0,33.0,SF,0.72,3.67,...,0.0,43378.0,PA,0.0,2021,2,09/19/2021,13:00:00,PHI,SF

In [32]:
w2_C.drop(columns=['homeTeamAbbr', 'visitorTeamAbbr','gameDate', 'gameTimeEastern', 'season'], inplace=True, errors='ignore')
w2_C

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,38629,6-3,308,Ben Jones,2.021092e+09,3516.0,37.0,TEN,0.59,5.02,...,NaN,NaN,0.0,0.0,1.0,0.0,41786.0,PP,0.0,2
1,47801,6-3,305,Garrett Bradbury,2.021092e+09,3433.0,32.0,MIN,2.29,4.32,...,NaN,NaN,0.0,0.0,1.0,0.0,35522.0,SW,0.0,2
2,34472,6-4,311,Alex Mack,2.021092e+09,1134.0,32.0,SF,1.23,3.77,...,NaN,NaN,0.0,0.0,0.0,0.0,43378.0,PA,0.0,2
3,46284,6-5,317,Bradley Bozeman,2.021092e+09,3676.0,47.0,BAL,4.76,3.75,...,NaN,NaN,0.0,0.0,0.0,0.0,41348.0,PR,0.0,2
4,34472,6-4,311,Alex Mack,2.021092e+09,1134.0,33.0,SF,0.72,3.67,...,NaN,NaN,0.0,0.0,0.0,0.0,43378.0,PA,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3078,46089,6-5,311,Frank Ragnow,2.021092e+09,2959.0,6.0,DET,0.00,0.00,...,NaN,NaN,0.0,0.0,0.0,0.0,47933.0,SW,0.0,2
3079,46089,6-5,311,Frank Ragnow,2.021092e+09,2959.0,7.0,DET,0.00,0.00,...,NaN,NaN,0.0,0.0,0.0,0.0,47933.0,SW,0.0,2
3080,41390,6-3,301,Corey Linsley,2.021092e+09,3066.0,6.0,LAC,0.00,0.00,...,NaN,NaN,0.0,0.0,0.0,0.0,41363.0,PP,0.0,2
3081,52491,6-4,315,Lloyd Cushenberry,2.021092e+09,2120.0,7.0,DEN,0.00,0.00,...,NaN,NaN,0.0,0.0,0.0,0.0,42375.0,PT,0.0,2
3082,40070,6-4,307,J.C. Tretter,2.021092e+09,164.0,6.0,CLE,0.00,0.00,...,NaN,NaN,0.0,0.0,0.0,0.0,38556.0,PP,0.0,2

In [33]:
w2_C.to_csv('Resources/center_w2.csv', sep=',', index=False)

In [34]:
w2_C_df = pd.read_csv('Resources/center_w2.csv')
w2_C_df.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,38629,6-3,308,Ben Jones,2.021092e+09,3516.0,37.0,TEN,0.59,5.02,...,NaN,NaN,0.0,0.0,1.0,0.0,41786.0,PP,0.0,2
1,47801,6-3,305,Garrett Bradbury,2.021092e+09,3433.0,32.0,MIN,2.29,4.32,...,NaN,NaN,0.0,0.0,1.0,0.0,35522.0,SW,0.0,2
2,34472,6-4,311,Alex Mack,2.021092e+09,1134.0,32.0,SF,1.23,3.77,...,NaN,NaN,0.0,0.0,0.0,0.0,43378.0,PA,0.0,2
3,46284,6-5,317,Bradley Bozeman,2.021092e+09,3676.0,47.0,BAL,4.76,3.75,...,NaN,NaN,0.0,0.0,0.0,0.0,41348.0,PR,0.0,2
4,34472,6-4,311,Alex Mack,2.021092e+09,1134.0,33.0,SF,0.72,3.67,...,NaN,NaN,0.0,0.0,0.0,0.0,43378.0,PA,0.0,2

## Guard

In [35]:
w2_G = cleaned_G.merge(plays_df, how="left")
w2_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,52483,6-4,305,Jonah Jackson,2.021092e+09,3546.0,36.0,DET,0.78,4.67,...,NaN,19.0,SHOTGUN,"1 RB, 1 TE, 3 WR",4.0,"2 DL, 3 LB, 6 DB",TRADITIONAL,0,Cover-6,Zone
1,52483,6-4,305,Jonah Jackson,2.021092e+09,3546.0,35.0,DET,1.34,4.50,...,NaN,19.0,SHOTGUN,"1 RB, 1 TE, 3 WR",4.0,"2 DL, 3 LB, 6 DB",TRADITIONAL,0,Cover-6,Zone
2,40124,6-5,310,David Quessenberry,2.021092e+09,1746.0,35.0,TEN,0.70,4.45,...,NaN,104.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,0,Red Zone,Other
3,40124,6-5,310,David Quessenberry,2.021092e+09,1746.0,34.0,TEN,1.25,4.44,...,NaN,104.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,0,Red Zone,Other
4,41242,6-4,315,Zack Martin,2.021092e+09,322.0,36.0,DAL,0.78,4.33,...,NaN,46.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,0,Cover-3,Zone

In [36]:
w2_G.drop(columns=[['possessionTeam','pff_passCoverage','pff_passCoverageType']], inplace=True, errors='ignore')
w2_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,52483,6-4,305,Jonah Jackson,2.021092e+09,3546.0,36.0,DET,0.78,4.67,...,NaN,19.0,SHOTGUN,"1 RB, 1 TE, 3 WR",4.0,"2 DL, 3 LB, 6 DB",TRADITIONAL,0,Cover-6,Zone
1,52483,6-4,305,Jonah Jackson,2.021092e+09,3546.0,35.0,DET,1.34,4.50,...,NaN,19.0,SHOTGUN,"1 RB, 1 TE, 3 WR",4.0,"2 DL, 3 LB, 6 DB",TRADITIONAL,0,Cover-6,Zone
2,40124,6-5,310,David Quessenberry,2.021092e+09,1746.0,35.0,TEN,0.70,4.45,...,NaN,104.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,0,Red Zone,Other
3,40124,6-5,310,David Quessenberry,2.021092e+09,1746.0,34.0,TEN,1.25,4.44,...,NaN,104.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,0,Red Zone,Other
4,41242,6-4,315,Zack Martin,2.021092e+09,322.0,36.0,DAL,0.78,4.33,...,NaN,46.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,0,Cover-3,Zone

In [38]:
w2_G = w2_G.merge(pff_df, how='left')
w2_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,52483,6-4,305,Jonah Jackson,2.021092e+09,3546.0,36.0,DET,0.78,4.67,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,43426.0,PP,0.0
1,52483,6-4,305,Jonah Jackson,2.021092e+09,3546.0,35.0,DET,1.34,4.50,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,43426.0,PP,0.0
2,40124,6-5,310,David Quessenberry,2.021092e+09,1746.0,35.0,TEN,0.70,4.45,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,52456.0,PP,0.0
3,40124,6-5,310,David Quessenberry,2.021092e+09,1746.0,34.0,TEN,1.25,4.44,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,52456.0,PP,0.0
4,41242,6-4,315,Zack Martin,2.021092e+09,322.0,36.0,DAL,0.78,4.33,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,42559.0,PT,0.0

In [40]:
w2_G = w2_G.merge(games_df, how='left')
w2_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,52483,6-4,305,Jonah Jackson,2.021092e+09,3546.0,36.0,DET,0.78,4.67,...,0.0,43426.0,PP,0.0,2021,2,09/20/2021,20:15:00,GB,DET
1,52483,6-4,305,Jonah Jackson,2.021092e+09,3546.0,35.0,DET,1.34,4.50,...,0.0,43426.0,PP,0.0,2021,2,09/20/2021,20:15:00,GB,DET
2,40124,6-5,310,David Quessenberry,2.021092e+09,1746.0,35.0,TEN,0.70,4.45,...,0.0,52456.0,PP,0.0,2021,2,09/19/2021,16:25:00,SEA,TEN
3,40124,6-5,310,David Quessenberry,2.021092e+09,1746.0,34.0,TEN,1.25,4.44,...,0.0,52456.0,PP,0.0,2021,2,09/19/2021,16:25:00,SEA,TEN
4,41242,6-4,315,Zack Martin,2.021092e+09,322.0,36.0,DAL,0.78,4.33,...,0.0,42559.0,PT,0.0,2021,2,09/19/2021,16:25:00,LAC,DAL

In [41]:
w2_G.drop(columns=['homeTeamAbbr', 'visitorTeamAbbr','gameDate', 'gameTimeEastern', 'season'], inplace=True, errors='ignore')
w2_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,52483,6-4,305,Jonah Jackson,2.021092e+09,3546.0,36.0,DET,0.78,4.67,...,NaN,NaN,0.0,0.0,0.0,0.0,43426.0,PP,0.0,2
1,52483,6-4,305,Jonah Jackson,2.021092e+09,3546.0,35.0,DET,1.34,4.50,...,NaN,NaN,0.0,0.0,0.0,0.0,43426.0,PP,0.0,2
2,40124,6-5,310,David Quessenberry,2.021092e+09,1746.0,35.0,TEN,0.70,4.45,...,NaN,NaN,0.0,0.0,0.0,0.0,52456.0,PP,0.0,2
3,40124,6-5,310,David Quessenberry,2.021092e+09,1746.0,34.0,TEN,1.25,4.44,...,NaN,NaN,0.0,0.0,0.0,0.0,52456.0,PP,0.0,2
4,41242,6-4,315,Zack Martin,2.021092e+09,322.0,36.0,DAL,0.78,4.33,...,NaN,NaN,0.0,0.0,0.0,0.0,42559.0,PT,0.0,2

In [44]:
w2_G.to_csv('Resources/guard_w2.csv', sep=',', index=False)

In [46]:
w2_G_df = pd.read_csv('Resources/guard_w2.csv')
w2_G_df.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,52483,6-4,305,Jonah Jackson,2.021092e+09,3546.0,36.0,DET,0.78,4.67,...,NaN,NaN,0.0,0.0,0.0,0.0,43426.0,PP,0.0,2
1,52483,6-4,305,Jonah Jackson,2.021092e+09,3546.0,35.0,DET,1.34,4.50,...,NaN,NaN,0.0,0.0,0.0,0.0,43426.0,PP,0.0,2
2,40124,6-5,310,David Quessenberry,2.021092e+09,1746.0,35.0,TEN,0.70,4.45,...,NaN,NaN,0.0,0.0,0.0,0.0,52456.0,PP,0.0,2
3,40124,6-5,310,David Quessenberry,2.021092e+09,1746.0,34.0,TEN,1.25,4.44,...,NaN,NaN,0.0,0.0,0.0,0.0,52456.0,PP,0.0,2
4,41242,6-4,315,Zack Martin,2.021092e+09,322.0,36.0,DAL,0.78,4.33,...,NaN,NaN,0.0,0.0,0.0,0.0,42559.0,PT,0.0,2

## Tackle

In [47]:
w2_T = cleaned_T.merge(plays_df, how="left")
w2_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,42377,6-6,338,Donovan Smith,2.021092e+09,1840.0,15.0,TB,1.68,4.75,...,NaN,46.0,SINGLEBACK,"1 RB, 3 TE, 1 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,1,Cover-2,Zone
1,44876,6-5,325,Taylor Moton,2.021092e+09,3355.0,32.0,CAR,1.40,4.64,...,NaN,48.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",7.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-3,Zone
2,44876,6-5,325,Taylor Moton,2.021092e+09,3355.0,33.0,CAR,1.09,4.55,...,NaN,48.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",7.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-3,Zone
3,35443,6-5,320,Trent Williams,2.021092e+09,1215.0,34.0,SF,2.44,4.55,...,NaN,40.0,I_FORM,"2 RB, 2 TE, 1 WR",7.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1,Cover-3,Zone
4,35443,6-5,320,Trent Williams,2.021092e+09,1215.0,33.0,SF,2.82,4.52,...,NaN,40.0,I_FORM,"2 RB, 2 TE, 1 WR",7.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1,Cover-3,Zone

In [48]:
w2_T.drop(columns=['possessionTeam','pff_passCoverage','pff_passCoverageType'], inplace=True, errors='ignore')
w2_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId2,foulName3,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction
0,42377,6-6,338,Donovan Smith,2.021092e+09,1840.0,15.0,TB,1.68,4.75,...,NaN,NaN,NaN,46.0,SINGLEBACK,"1 RB, 3 TE, 1 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,1
1,44876,6-5,325,Taylor Moton,2.021092e+09,3355.0,32.0,CAR,1.40,4.64,...,NaN,NaN,NaN,48.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",7.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0
2,44876,6-5,325,Taylor Moton,2.021092e+09,3355.0,33.0,CAR,1.09,4.55,...,NaN,NaN,NaN,48.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",7.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0
3,35443,6-5,320,Trent Williams,2.021092e+09,1215.0,34.0,SF,2.44,4.55,...,NaN,NaN,NaN,40.0,I_FORM,"2 RB, 2 TE, 1 WR",7.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1
4,35443,6-5,320,Trent Williams,2.021092e+09,1215.0,33.0,SF,2.82,4.52,...,NaN,NaN,NaN,40.0,I_FORM,"2 RB, 2 TE, 1 WR",7.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1

In [49]:
w2_T = w2_T.merge(pff_df, how='left')
w2_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,42377,6-6,338,Donovan Smith,2.021092e+09,1840.0,15.0,TB,1.68,4.75,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,42480.0,PP,0.0
1,44876,6-5,325,Taylor Moton,2.021092e+09,3355.0,32.0,CAR,1.40,4.64,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,37097.0,PP,0.0
2,44876,6-5,325,Taylor Moton,2.021092e+09,3355.0,33.0,CAR,1.09,4.55,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,37097.0,PP,0.0
3,35443,6-5,320,Trent Williams,2.021092e+09,1215.0,34.0,SF,2.44,4.55,...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,38542.0,PT,0.0
4,35443,6-5,320,Trent Williams,2.021092e+09,1215.0,33.0,SF,2.82,4.52,...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,38542.0,PT,0.0

In [50]:
w2_T = w2_T.merge(games_df, how='left')
w2_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,42377,6-6,338,Donovan Smith,2.021092e+09,1840.0,15.0,TB,1.68,4.75,...,0.0,42480.0,PP,0.0,2021,2,09/19/2021,16:05:00,TB,ATL
1,44876,6-5,325,Taylor Moton,2.021092e+09,3355.0,32.0,CAR,1.40,4.64,...,0.0,37097.0,PP,0.0,2021,2,09/19/2021,13:00:00,CAR,NO
2,44876,6-5,325,Taylor Moton,2.021092e+09,3355.0,33.0,CAR,1.09,4.55,...,0.0,37097.0,PP,0.0,2021,2,09/19/2021,13:00:00,CAR,NO
3,35443,6-5,320,Trent Williams,2.021092e+09,1215.0,34.0,SF,2.44,4.55,...,0.0,38542.0,PT,0.0,2021,2,09/19/2021,13:00:00,PHI,SF
4,35443,6-5,320,Trent Williams,2.021092e+09,1215.0,33.0,SF,2.82,4.52,...,0.0,38542.0,PT,0.0,2021,2,09/19/2021,13:00:00,PHI,SF

In [51]:
w2_T.drop(columns=['homeTeamAbbr', 'visitorTeamAbbr','gameDate', 'gameTimeEastern', 'season'], inplace=True, errors='ignore')
w2_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,42377,6-6,338,Donovan Smith,2.021092e+09,1840.0,15.0,TB,1.68,4.75,...,NaN,NaN,0.0,0.0,0.0,0.0,42480.0,PP,0.0,2
1,44876,6-5,325,Taylor Moton,2.021092e+09,3355.0,32.0,CAR,1.40,4.64,...,NaN,NaN,0.0,0.0,0.0,0.0,37097.0,PP,0.0,2
2,44876,6-5,325,Taylor Moton,2.021092e+09,3355.0,33.0,CAR,1.09,4.55,...,NaN,NaN,0.0,0.0,0.0,0.0,37097.0,PP,0.0,2
3,35443,6-5,320,Trent Williams,2.021092e+09,1215.0,34.0,SF,2.44,4.55,...,NaN,NaN,1.0,0.0,0.0,0.0,38542.0,PT,0.0,2
4,35443,6-5,320,Trent Williams,2.021092e+09,1215.0,33.0,SF,2.82,4.52,...,NaN,NaN,1.0,0.0,0.0,0.0,38542.0,PT,0.0,2

In [52]:
w2_T.to_csv('Resources/tackle_w2.csv', sep=',', index=False)

In [54]:
w2_T_df = pd.read_csv('Resources/tackle_w2.csv')
w2_T_df.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,42377,6-6,338,Donovan Smith,2.021092e+09,1840.0,15.0,TB,1.68,4.75,...,NaN,NaN,0.0,0.0,0.0,0.0,42480.0,PP,0.0,2
1,44876,6-5,325,Taylor Moton,2.021092e+09,3355.0,32.0,CAR,1.40,4.64,...,NaN,NaN,0.0,0.0,0.0,0.0,37097.0,PP,0.0,2
2,44876,6-5,325,Taylor Moton,2.021092e+09,3355.0,33.0,CAR,1.09,4.55,...,NaN,NaN,0.0,0.0,0.0,0.0,37097.0,PP,0.0,2
3,35443,6-5,320,Trent Williams,2.021092e+09,1215.0,34.0,SF,2.44,4.55,...,NaN,NaN,1.0,0.0,0.0,0.0,38542.0,PT,0.0,2
4,35443,6-5,320,Trent Williams,2.021092e+09,1215.0,33.0,SF,2.82,4.52,...,NaN,NaN,1.0,0.0,0.0,0.0,38542.0,PT,0.0,2