In [1]:
import csv
import os
import pandas as pd
import numpy as np

In [6]:
players_data_to_load = "Resources/players.csv"
week5_data_to_load = "Resources/week5.csv"
plays_data_to_load = "Resources/plays.csv"
pff_data_to_load = "Resources/pffScoutingData.csv"
games_data_to_load = "Resources/games.csv"

In [7]:
players_df = pd.read_csv(players_data_to_load)
players_df

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName
0,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady
1,28963,6-5,240,1982-03-02,"Miami, O.",QB,Ben Roethlisberger
2,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters
3,29851,6-2,225,1983-12-02,California,QB,Aaron Rodgers
4,30078,6-2,228,1982-11-24,Harvard,QB,Ryan Fitzpatrick
...,...,...,...,...,...,...,...
1674,53991,6-1,320,NaN,NaN,DT,Forrest Merrill
1675,53994,6-5,300,NaN,NaN,C,Ryan McCollum
1676,53999,6-4,312,NaN,NaN,DT,Jack Heflin
1677,54006,6-6,330,NaN,NaN,T,Jake Curhan
1678,54038,6-6,245,NaN,NaN,QB,Feleipe Franks

In [8]:
week5_df = pd.read_csv(week5_data_to_load)
week5_df

,gameId,playId,nflId,frameId,time,jerseyNumber,team,playDirection,x,y,s,a,dis,o,dir,event
0,2021100700,95,30869.0,1,2021-10-08T00:23:33.900,77.0,LA,right,22.93,33.04,0.02,0.02,0.00,102.26,129.51,None
1,2021100700,95,30869.0,2,2021-10-08T00:23:34.000,77.0,LA,right,22.93,33.04,0.01,0.02,0.00,101.64,128.68,None
2,2021100700,95,30869.0,3,2021-10-08T00:23:34.100,77.0,LA,right,22.92,33.05,0.01,0.01,0.01,100.73,127.26,None
3,2021100700,95,30869.0,4,2021-10-08T00:23:34.200,77.0,LA,right,22.92,33.05,0.01,0.01,0.01,100.73,130.90,None
4,2021100700,95,30869.0,5,2021-10-08T00:23:34.300,77.0,LA,right,22.91,33.05,0.01,0.01,0.01,99.55,134.16,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1097808,2021101100,4401,NaN,34,2021-10-12T03:30:06.400,NaN,football,right,100.80,19.42,21.36,0.17,3.80,NaN,NaN,None
1097809,2021101100,4401,NaN,35,2021-10-12T03:30:06.500,NaN,football,right,102.61,18.29,21.29,1.13,2.13,NaN,NaN,None
1097810,2021101100,4401,NaN,36,2021-10-12T03:30:06.600,NaN,football,right,104.41,17.17,21.13,2.06,2.12,NaN,NaN,None
1097811,2021101100,4401,NaN,37,2021-10-12T03:30:06.700,NaN,football,right,106.20,16.06,20.88,2.94,2.10,NaN,NaN,None
1097812,2021101100,4401,NaN,38,2021-10-12T03:30:06.800,NaN,football,right,107.96,14.97,20.55,3.71,2.07,NaN,NaN,None

In [9]:
week5_players = players_df.merge(week5_df, how='left')
week5_players

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
0,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021101e+09,394.0,1.0,...,TB,right,25.86,24.10,0.0,0.00,0.00,103.71,20.35,None
1,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021101e+09,394.0,2.0,...,TB,right,25.87,24.10,0.0,0.00,0.00,103.71,22.54,None
2,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021101e+09,394.0,3.0,...,TB,right,25.87,24.10,0.0,0.00,0.00,103.71,23.32,None
3,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021101e+09,394.0,4.0,...,TB,right,25.87,24.10,0.0,0.00,0.00,103.71,21.60,None
4,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady,2.021101e+09,394.0,5.0,...,TB,right,25.86,24.10,0.0,0.00,0.00,103.71,19.89,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1050595,53991,6-1,320,NaN,NaN,DT,Forrest Merrill,2.021101e+09,1180.0,48.0,...,LAC,left,92.46,26.39,1.6,1.04,0.17,37.26,327.61,None
1050596,53994,6-5,300,NaN,NaN,C,Ryan McCollum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1050597,53999,6-4,312,NaN,NaN,DT,Jack Heflin,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1050598,54006,6-6,330,NaN,NaN,T,Jake Curhan,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1050599,54038,6-6,245,NaN,NaN,QB,Feleipe Franks,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Centers

In [10]:
week5_players_C = week5_players[week5_players['officialPosition'] == 'C']
week5_players_C.head()

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
15015,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021101e+09,54.0,1.0,...,SF,left,85.48,23.78,0.02,0.15,0.00,264.90,149.89,None
15016,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021101e+09,54.0,2.0,...,SF,left,85.49,23.77,0.11,0.44,0.01,265.57,154.91,None
15017,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021101e+09,54.0,3.0,...,SF,left,85.50,23.76,0.18,0.49,0.02,266.17,144.22,None
15018,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021101e+09,54.0,4.0,...,SF,left,85.53,23.75,0.27,0.62,0.03,266.82,121.00,None
15019,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021101e+09,54.0,5.0,...,SF,left,85.58,23.73,0.46,0.96,0.05,267.64,114.98,None

In [11]:
week5_players_C = week5_players_C[week5_players_C['event'] != 'None']
week5_players_C

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
15020,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021101e+09,54.0,6.0,...,SF,left,85.62,23.70,0.58,0.94,0.06,267.64,116.51,ball_snap
15045,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021101e+09,54.0,31.0,...,SF,left,88.55,21.22,1.30,1.52,0.13,148.63,166.43,run
15051,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021101e+09,85.0,1.0,...,SF,left,71.36,29.63,0.00,0.00,0.01,270.43,250.40,man_in_motion
15056,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021101e+09,85.0,6.0,...,SF,left,71.45,29.61,0.54,1.81,0.05,267.42,106.91,ball_snap
15069,34472,6-4,311,1985-11-19,California,C,Alex Mack,2.021101e+09,85.0,19.0,...,SF,left,73.13,28.00,1.84,1.58,0.19,216.77,142.75,play_action
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1017865,53516,6-3,310,NaN,NaN,C,Kendrick Green,2.021101e+09,3197.0,7.0,...,PIT,left,90.15,24.01,0.33,1.12,0.03,267.80,112.37,ball_snap
1017886,53516,6-3,310,NaN,NaN,C,Kendrick Green,2.021101e+09,3197.0,28.0,...,PIT,left,94.64,24.90,2.32,1.88,0.23,339.22,71.20,pass_forward
1025964,53543,6-3,300,NaN,NaN,C,Drew Dalman,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1038105,53619,6-3,330,NaN,NaN,C,Trey Hill,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1050596,53994,6-5,300,NaN,NaN,C,Ryan McCollum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
week5_players_C = week5_players_C.sort_values('a', ascending = False)
week5_players_C

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
869684,52486,6-4,290,1997-11-17,Temple,C,Matt Hennessy,2.021101e+09,2576.0,7.0,...,ATL,right,35.48,23.61,0.72,5.33,0.05,72.15,345.63,ball_snap
82148,38629,6-3,308,1989-07-02,Georgia,C,Ben Jones,2.021101e+09,1732.0,6.0,...,TEN,right,93.59,23.98,1.04,4.30,0.08,140.11,248.83,autoevent_ballsnap
871435,52491,6-4,315,1997-11-22,Louisiana State,C,Lloyd Cushenberry,2.021101e+09,1188.0,38.0,...,DEN,left,76.49,25.97,0.46,3.60,0.05,331.61,327.48,autoevent_passforward
149885,41069,6-2,300,1989-06-05,Iowa,C,James Ferentz,2.021101e+09,3525.0,36.0,...,NE,right,50.51,31.60,1.38,3.50,0.13,212.10,249.21,autoevent_passforward
149015,41069,6-2,300,1989-06-05,Iowa,C,James Ferentz,2.021101e+09,1110.0,29.0,...,NE,right,102.98,23.74,0.92,3.40,0.10,34.68,162.57,autoevent_passforward
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
951061,53063,6-3,270,1997-10-28,Texas State,C,Aaron Brewer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1004327,53491,6-5,312,NaN,NaN,C,Josh Myers,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1025964,53543,6-3,300,NaN,NaN,C,Drew Dalman,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1038105,53619,6-3,330,NaN,NaN,C,Trey Hill,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1050596,53994,6-5,300,NaN,NaN,C,Ryan McCollum,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
week5_players_C = week5_players_C.dropna()

In [14]:
cleaned_C= week5_players_C[['nflId', 'height', 'weight', 'displayName', 'gameId', 'playId', 'frameId', 'team', 's', 'a', 'dis', 'event']]
cleaned_C

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,dis,event
869684,52486,6-4,290,Matt Hennessy,2.021101e+09,2576.0,7.0,ATL,0.72,5.33,0.05,ball_snap
82148,38629,6-3,308,Ben Jones,2.021101e+09,1732.0,6.0,TEN,1.04,4.30,0.08,autoevent_ballsnap
871435,52491,6-4,315,Lloyd Cushenberry,2.021101e+09,1188.0,38.0,DEN,0.46,3.60,0.05,autoevent_passforward
149885,41069,6-2,300,James Ferentz,2.021101e+09,3525.0,36.0,NE,1.38,3.50,0.13,autoevent_passforward
149015,41069,6-2,300,James Ferentz,2.021101e+09,1110.0,29.0,NE,0.92,3.40,0.10,autoevent_passforward
...,...,...,...,...,...,...,...,...,...,...,...,...
507464,45012,6-4,312,Chase Roullier,2.021101e+09,1840.0,6.0,WAS,0.00,0.00,0.01,ball_snap
872773,52491,6-4,315,Lloyd Cushenberry,2.021101e+09,3876.0,6.0,DEN,0.00,0.00,0.02,ball_snap
872774,52491,6-4,315,Lloyd Cushenberry,2.021101e+09,3876.0,7.0,DEN,0.00,0.00,0.02,autoevent_ballsnap
648221,46284,6-5,317,Bradley Bozeman,2.021101e+09,4401.0,6.0,BAL,0.00,0.00,0.02,ball_snap
507541,45012,6-4,312,Chase Roullier,2.021101e+09,2261.0,1.0,WAS,0.00,0.00,0.00,man_in_motion

## Guards

In [15]:
week5_players_G = week5_players[week5_players['officialPosition'] == 'G']
week5_players_G

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
28520,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021101e+09,314.0,1.0,...,TEN,left,83.97,28.18,0.02,0.02,0.01,303.10,196.73,None
28521,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021101e+09,314.0,2.0,...,TEN,left,83.96,28.18,0.02,0.02,0.01,304.00,203.77,None
28522,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021101e+09,314.0,3.0,...,TEN,left,83.96,28.17,0.02,0.02,0.01,304.00,204.59,None
28523,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021101e+09,314.0,4.0,...,TEN,left,83.95,28.16,0.02,0.16,0.01,302.21,216.09,None
28524,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021101e+09,314.0,5.0,...,TEN,left,83.95,28.16,0.06,0.40,0.01,300.50,218.53,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1045369,53655,6-6,325,NaN,NaN,G,Trey Smith,2.021101e+09,4371.0,27.0,...,KC,left,38.81,24.44,1.59,2.14,0.17,348.44,123.68,None
1045370,53655,6-6,325,NaN,NaN,G,Trey Smith,2.021101e+09,4371.0,28.0,...,KC,left,38.94,24.36,1.37,2.06,0.15,347.22,123.66,None
1045371,53655,6-6,325,NaN,NaN,G,Trey Smith,2.021101e+09,4371.0,29.0,...,KC,left,39.04,24.29,1.13,1.97,0.12,349.80,123.82,None
1047282,53861,6-5,330,NaN,NaN,G,Robert Jones,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1049532,53954,6-5,319,NaN,NaN,G,Tommy Kraemer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
week5_players_G = week5_players_G[week5_players_G['event'] != 'None']
week5_players_G

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
28525,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021101e+09,314.0,6.0,...,TEN,left,83.92,28.14,0.23,1.10,0.03,299.37,229.40,ball_snap
28540,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021101e+09,314.0,21.0,...,TEN,left,83.65,27.90,0.96,0.99,0.09,273.91,73.02,play_action
28547,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021101e+09,314.0,28.0,...,TEN,left,84.65,28.39,2.03,0.69,0.21,307.06,68.45,pass_forward
28558,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021101e+09,391.0,6.0,...,TEN,left,75.54,22.26,0.35,1.31,0.04,307.96,10.70,autoevent_ballsnap
28559,35472,6-5,325,1988-06-06,Indiana,G,Rodger Saffold,2.021101e+09,391.0,7.0,...,TEN,left,75.54,22.33,0.60,1.50,0.06,307.35,5.19,ball_snap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1045348,53655,6-6,325,NaN,NaN,G,Trey Smith,2.021101e+09,4371.0,6.0,...,KC,left,36.60,24.96,0.07,0.80,0.01,261.41,344.15,ball_snap
1045366,53655,6-6,325,NaN,NaN,G,Trey Smith,2.021101e+09,4371.0,24.0,...,KC,left,38.34,24.74,2.25,0.85,0.22,350.30,122.28,pass_forward
1045367,53655,6-6,325,NaN,NaN,G,Trey Smith,2.021101e+09,4371.0,25.0,...,KC,left,38.52,24.63,2.12,1.21,0.21,351.17,123.70,autoevent_passforward
1047282,53861,6-5,330,NaN,NaN,G,Robert Jones,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1049532,53954,6-5,319,NaN,NaN,G,Tommy Kraemer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
week5_players_G = week5_players_G.sort_values('a', ascending = False)

In [18]:
week5_players_G = week5_players_G.dropna()

In [19]:
cleaned_G = week5_players_G[['nflId', 'height', 'weight', 'displayName', 'gameId', 'playId', 'frameId', 'team', 's', 'a', 'dis', 'event']]
cleaned_G

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,dis,event
853557,52466,6-6,310,Ezra Cleveland,2.021101e+09,1420.0,10.0,MIN,0.92,4.78,0.07,ball_snap
96209,39684,6-3,305,Greg Van Roten,2.021101e+09,2402.0,42.0,NYJ,1.65,4.41,0.17,pass_forward
359192,43384,6-6,310,Graham Glasgow,2.021101e+09,2974.0,32.0,DEN,0.96,4.26,0.09,first_contact
800015,48485,6-5,310,Blake Hance,2.021101e+09,3183.0,24.0,CLE,1.34,4.22,0.14,pass_forward
254306,42404,6-4,307,Ali Marpet,2.021101e+09,3419.0,38.0,TB,0.75,4.09,0.07,autoevent_passforward
...,...,...,...,...,...,...,...,...,...,...,...,...
840659,52447,6-5,322,Robert Hunt,2.021101e+09,295.0,6.0,MIA,0.00,0.00,0.01,autoevent_ballsnap
214430,41939,6-6,325,Andrew Norwell,2.021101e+09,585.0,6.0,JAX,0.00,0.00,0.00,autoevent_ballsnap
840853,52447,6-5,322,Robert Hunt,2.021101e+09,715.0,6.0,MIA,0.00,0.00,0.01,autoevent_ballsnap
840854,52447,6-5,322,Robert Hunt,2.021101e+09,715.0,7.0,MIA,0.00,0.00,0.02,ball_snap
563709,46102,6-4,305,Austin Corbett,2.021101e+09,799.0,6.0,LA,0.00,0.00,0.00,autoevent_ballsnap

## Tackles

In [20]:
week5_players_T = week5_players[week5_players['officialPosition'] == 'T']
week5_players_T

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
2289,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021101e+09,282.0,1.0,...,CHI,right,28.55,32.92,0.00,0.00,0.0,73.33,182.84,None
2290,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021101e+09,282.0,2.0,...,CHI,right,28.54,32.92,0.00,0.00,0.0,73.33,183.28,None
2291,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021101e+09,282.0,3.0,...,CHI,right,28.55,32.92,0.00,0.00,0.0,73.33,177.36,None
2292,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021101e+09,282.0,4.0,...,CHI,right,28.55,32.92,0.00,0.00,0.0,72.56,177.10,None
2293,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021101e+09,282.0,5.0,...,CHI,right,28.54,32.92,0.01,0.12,0.0,73.16,292.48,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1034593,53584,6-5,315,NaN,NaN,T,Jaylon Moore,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1034876,53590,6-8,315,NaN,NaN,T,Tommy Doyle,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1042010,53635,6-7,305,NaN,NaN,T,Landon Young,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1047283,53868,6-6,315,NaN,NaN,T,Alaric Jackson,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1050598,54006,6-6,330,NaN,NaN,T,Jake Curhan,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
week5_players_T = week5_players_T[week5_players_T['event'] != 'None']
week5_players_T

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName,gameId,playId,frameId,...,team,playDirection,x,y,s,a,dis,o,dir,event
2294,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021101e+09,282.0,6.0,...,CHI,right,28.54,32.93,0.07,0.48,0.01,73.94,304.13,ball_snap
2323,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021101e+09,282.0,35.0,...,CHI,right,24.06,33.03,1.63,0.93,0.17,84.83,258.28,pass_forward
2324,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021101e+09,282.0,36.0,...,CHI,right,23.87,33.01,1.71,0.80,0.19,66.87,261.20,autoevent_passforward
2334,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021101e+09,835.0,6.0,...,CHI,right,24.27,26.86,0.18,0.92,0.02,87.81,301.04,ball_snap
2352,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters,2.021101e+09,835.0,24.0,...,CHI,right,20.43,27.30,2.15,3.35,0.22,34.79,219.96,pass_forward
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1034593,53584,6-5,315,NaN,NaN,T,Jaylon Moore,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1034876,53590,6-8,315,NaN,NaN,T,Tommy Doyle,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1042010,53635,6-7,305,NaN,NaN,T,Landon Young,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1047283,53868,6-6,315,NaN,NaN,T,Alaric Jackson,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1050598,54006,6-6,330,NaN,NaN,T,Jake Curhan,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
week5_players_T = week5_players_T.sort_values('a', ascending = False)

In [23]:
week5_players_T = week5_players_T.dropna()

In [24]:
cleaned_T = week5_players_T[['nflId', 'height', 'weight', 'displayName', 'gameId', 'playId', 'frameId', 'team', 's', 'a', 'dis', 'event']]
cleaned_T

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,dis,event
400359,43640,6-6,313,Rashod Hill,2.021101e+09,495.0,15.0,MIN,3.79,6.33,0.35,play_action
398224,43586,6-5,322,George Fant,2.021101e+09,2452.0,7.0,NYJ,1.04,5.37,0.08,ball_snap
918275,52603,6-5,290,Justin Herron,2.021101e+09,3549.0,37.0,NE,0.90,5.26,0.10,autoevent_passforward
918276,52603,6-5,290,Justin Herron,2.021101e+09,3549.0,38.0,NE,0.60,5.21,0.06,pass_forward
150733,41222,6-9,320,Alejandro Villanueva,2.021101e+09,2239.0,60.0,BAL,1.32,5.10,0.15,run
...,...,...,...,...,...,...,...,...,...,...,...,...
151245,41222,6-9,320,Alejandro Villanueva,2.021101e+09,3247.0,6.0,BAL,0.00,0.00,0.00,ball_snap
150866,41222,6-9,320,Alejandro Villanueva,2.021101e+09,2365.0,6.0,BAL,0.00,0.00,0.01,ball_snap
150816,41222,6-9,320,Alejandro Villanueva,2.021101e+09,2343.0,6.0,BAL,0.00,0.00,0.01,ball_snap
150773,41222,6-9,320,Alejandro Villanueva,2.021101e+09,2308.0,6.0,BAL,0.00,0.00,0.01,ball_snap
379233,43447,6-5,324,Brandon Shell,2.021101e+09,2617.0,6.0,SEA,0.00,0.00,0.00,ball_snap

## Plays, PFF, & Games data added

In [25]:
plays_df = pd.read_csv(plays_data_to_load)
plays_df

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,defensiveTeam,yardlineSide,yardlineNumber,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,2021090900,97,(13:33) (Shotgun) T.Brady pass incomplete deep...,1,3,2,TB,DAL,TB,33,...,NaN,43.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
1,2021090900,137,(13:18) (Shotgun) D.Prescott pass deep left to...,1,1,10,DAL,TB,DAL,2,...,NaN,108.0,EMPTY,"1 RB, 2 TE, 2 WR",6.0,"4 DL, 4 LB, 3 DB",TRADITIONAL,0,Cover-3,Zone
2,2021090900,187,(12:23) (Shotgun) D.Prescott pass short middle...,1,2,6,DAL,TB,DAL,34,...,NaN,76.0,SHOTGUN,"0 RB, 2 TE, 3 WR",6.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,0,Cover-3,Zone
3,2021090900,282,(9:56) D.Prescott pass incomplete deep left to...,1,1,10,DAL,TB,TB,39,...,NaN,49.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",6.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1,Cover-3,Zone
4,2021090900,349,(9:46) (Shotgun) D.Prescott pass incomplete sh...,1,3,15,DAL,TB,TB,44,...,NaN,54.0,SHOTGUN,"1 RB, 1 TE, 3 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,0,Cover-3,Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8552,2021110100,4310,(1:56) (Shotgun) P.Mahomes sacked at NYG 16 fo...,4,3,8,KC,NYG,NYG,8,...,NaN,18.0,SHOTGUN,"1 RB, 1 TE, 3 WR",4.0,"1 DL, 3 LB, 7 DB",SCRAMBLE,0,Bracket,Other
8553,2021110100,4363,(1:07) (Shotgun) D.Jones pass short right to E...,4,1,10,NYG,KC,NYG,25,...,NaN,35.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"4 DL, 1 LB, 6 DB",SCRAMBLE,0,Cover-2,Zone
8554,2021110100,4392,"(1:01) (No Huddle, Shotgun) D.Jones sacked at ...",4,2,7,NYG,KC,NYG,28,...,NaN,38.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Cover-2,Zone
8555,2021110100,4411,"(:39) (No Huddle, Shotgun) D.Jones pass incomp...",4,3,15,NYG,KC,NYG,20,...,NaN,30.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Cover-2,Zone
8556,2021110100,4433,(:35) (Shotgun) D.Jones sacked at NYG 14 for -...,4,4,15,NYG,KC,NYG,20,...,NaN,30.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Quarters,Zone

In [26]:
pff_df = pd.read_csv(pff_data_to_load)
pff_df

,gameId,playId,nflId,pff_role,pff_positionLinedUp,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,2021090900,97,25511,Pass,QB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021090900,97,35481,Pass Route,TE-L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021090900,97,35634,Pass Route,LWR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021090900,97,39985,Pass Route,HB-R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021090900,97,40151,Pass Block,C,NaN,NaN,NaN,0.0,0.0,0.0,0.0,44955.0,SW,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188249,2021110100,4433,52507,Pass Block,LT,NaN,NaN,NaN,0.0,0.0,1.0,0.0,43338.0,PP,0.0
188250,2021110100,4433,52546,Coverage,SCBoR,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188251,2021110100,4433,52573,Pass Route,SLoWR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188252,2021110100,4433,52585,Pass Rush,LEO,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188253,2021110100,4433,53449,Pass Route,LWR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
games_df = pd.read_csv(games_data_to_load)
games_df

,gameId,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,2021090900,2021,1,09/09/2021,20:20:00,TB,DAL
1,2021091200,2021,1,09/12/2021,13:00:00,ATL,PHI
2,2021091201,2021,1,09/12/2021,13:00:00,BUF,PIT
3,2021091202,2021,1,09/12/2021,13:00:00,CAR,NYJ
4,2021091203,2021,1,09/12/2021,13:00:00,CIN,MIN
...,...,...,...,...,...,...,...
117,2021103109,2021,8,10/31/2021,16:05:00,SEA,JAX
118,2021103110,2021,8,10/31/2021,16:25:00,DEN,WAS
119,2021103111,2021,8,10/31/2021,16:25:00,NO,TB
120,2021103112,2021,8,10/31/2021,20:20:00,MIN,DAL
121,2021110100,2021,8,11/01/2021,20:15:00,KC,NYG

# Merging all data & Cleaning

## Center

In [28]:
w5_C = cleaned_C.merge(plays_df, how="left")
w5_C.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,52486,6-4,290,Matt Hennessy,2.021101e+09,2576.0,7.0,ATL,0.72,5.33,...,NaN,36.0,I_FORM,"2 RB, 1 TE, 2 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,1,Cover-1,Man
1,38629,6-3,308,Ben Jones,2.021101e+09,1732.0,6.0,TEN,1.04,4.30,...,NaN,94.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
2,52491,6-4,315,Lloyd Cushenberry,2.021101e+09,1188.0,38.0,DEN,0.46,3.60,...,NaN,70.0,SHOTGUN,"1 RB, 2 TE, 2 WR",6.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,0,Cover-3,Zone
3,41069,6-2,300,James Ferentz,2.021101e+09,3525.0,36.0,NE,1.38,3.50,...,NaN,58.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-6,Zone
4,41069,6-2,300,James Ferentz,2.021101e+09,1110.0,29.0,NE,0.92,3.40,...,NaN,101.0,I_FORM,"1 RB, 2 TE, 2 WR",8.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1,Cover-1,Man

In [29]:
w5_C.drop(columns=[['possessionTeam','pff_passCoverage','pff_passCoverageType']], inplace=True, errors='ignore')

In [30]:
w5_C = w5_C.merge(pff_df, how='left')
w5_C.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,52486,6-4,290,Matt Hennessy,2.021101e+09,2576.0,7.0,ATL,0.72,5.33,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,46249.0,PA,0.0
1,38629,6-3,308,Ben Jones,2.021101e+09,1732.0,6.0,TEN,1.04,4.30,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,42375.0,PP,0.0
2,52491,6-4,315,Lloyd Cushenberry,2.021101e+09,1188.0,38.0,DEN,0.46,3.60,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,47975.0,PP,0.0
3,41069,6-2,300,James Ferentz,2.021101e+09,3525.0,36.0,NE,1.38,3.50,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,44863.0,PP,0.0
4,41069,6-2,300,James Ferentz,2.021101e+09,1110.0,29.0,NE,0.92,3.40,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,44863.0,PA,0.0

In [31]:
w5_C = w5_C.merge(games_df, how='left')
w5_C.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,52486,6-4,290,Matt Hennessy,2.021101e+09,2576.0,7.0,ATL,0.72,5.33,...,0.0,46249.0,PA,0.0,2021,5,10/10/2021,09:30:00,ATL,NYJ
1,38629,6-3,308,Ben Jones,2.021101e+09,1732.0,6.0,TEN,1.04,4.30,...,0.0,42375.0,PP,0.0,2021,5,10/10/2021,13:00:00,JAX,TEN
2,52491,6-4,315,Lloyd Cushenberry,2.021101e+09,1188.0,38.0,DEN,0.46,3.60,...,0.0,47975.0,PP,0.0,2021,5,10/10/2021,13:00:00,PIT,DEN
3,41069,6-2,300,James Ferentz,2.021101e+09,3525.0,36.0,NE,1.38,3.50,...,0.0,44863.0,PP,0.0,2021,5,10/10/2021,13:00:00,HOU,NE
4,41069,6-2,300,James Ferentz,2.021101e+09,1110.0,29.0,NE,0.92,3.40,...,0.0,44863.0,PA,0.0,2021,5,10/10/2021,13:00:00,HOU,NE

In [32]:
w5_C.drop(columns=['homeTeamAbbr', 'visitorTeamAbbr','gameDate', 'gameTimeEastern', 'season'], inplace=True, errors='ignore')
w5_C

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,52486,6-4,290,Matt Hennessy,2.021101e+09,2576.0,7.0,ATL,0.72,5.33,...,NaN,NaN,0.0,0.0,0.0,0.0,46249.0,PA,0.0,5
1,38629,6-3,308,Ben Jones,2.021101e+09,1732.0,6.0,TEN,1.04,4.30,...,NaN,NaN,0.0,0.0,0.0,0.0,42375.0,PP,0.0,5
2,52491,6-4,315,Lloyd Cushenberry,2.021101e+09,1188.0,38.0,DEN,0.46,3.60,...,NaN,NaN,0.0,0.0,0.0,0.0,47975.0,PP,0.0,5
3,41069,6-2,300,James Ferentz,2.021101e+09,3525.0,36.0,NE,1.38,3.50,...,NaN,NaN,0.0,0.0,1.0,0.0,44863.0,PP,0.0,5
4,41069,6-2,300,James Ferentz,2.021101e+09,1110.0,29.0,NE,0.92,3.40,...,NaN,NaN,0.0,0.0,0.0,0.0,44863.0,PA,0.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3268,45012,6-4,312,Chase Roullier,2.021101e+09,1840.0,6.0,WAS,0.00,0.00,...,NaN,NaN,0.0,0.0,0.0,0.0,52665.0,PP,0.0,5
3269,52491,6-4,315,Lloyd Cushenberry,2.021101e+09,3876.0,6.0,DEN,0.00,0.00,...,NaN,NaN,0.0,0.0,0.0,0.0,37104.0,PT,0.0,5
3270,52491,6-4,315,Lloyd Cushenberry,2.021101e+09,3876.0,7.0,DEN,0.00,0.00,...,NaN,NaN,0.0,0.0,0.0,0.0,37104.0,PT,0.0,5
3271,46284,6-5,317,Bradley Bozeman,2.021101e+09,4401.0,6.0,BAL,0.00,0.00,...,NaN,NaN,0.0,0.0,0.0,0.0,45009.0,PP,0.0,5
3272,45012,6-4,312,Chase Roullier,2.021101e+09,2261.0,1.0,WAS,0.00,0.00,...,NaN,NaN,0.0,0.0,0.0,0.0,48544.0,PP,0.0,5

In [34]:
w5_C.to_csv('Resources/center_w5.csv', sep=',', index=False)

In [35]:
w5_C_df = pd.read_csv('Resources/center_w5.csv')
w5_C_df.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,52486,6-4,290,Matt Hennessy,2.021101e+09,2576.0,7.0,ATL,0.72,5.33,...,NaN,NaN,0.0,0.0,0.0,0.0,46249.0,PA,0.0,5
1,38629,6-3,308,Ben Jones,2.021101e+09,1732.0,6.0,TEN,1.04,4.30,...,NaN,NaN,0.0,0.0,0.0,0.0,42375.0,PP,0.0,5
2,52491,6-4,315,Lloyd Cushenberry,2.021101e+09,1188.0,38.0,DEN,0.46,3.60,...,NaN,NaN,0.0,0.0,0.0,0.0,47975.0,PP,0.0,5
3,41069,6-2,300,James Ferentz,2.021101e+09,3525.0,36.0,NE,1.38,3.50,...,NaN,NaN,0.0,0.0,1.0,0.0,44863.0,PP,0.0,5
4,41069,6-2,300,James Ferentz,2.021101e+09,1110.0,29.0,NE,0.92,3.40,...,NaN,NaN,0.0,0.0,0.0,0.0,44863.0,PA,0.0,5

## Guard

In [36]:
w5_G = cleaned_G.merge(plays_df, how="left")
w5_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,52466,6-6,310,Ezra Cleveland,2.021101e+09,1420.0,10.0,MIN,0.92,4.78,...,NaN,42.0,SINGLEBACK,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,1,Cover-2,Zone
1,39684,6-3,305,Greg Van Roten,2.021101e+09,2402.0,42.0,NYJ,1.65,4.41,...,NaN,74.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,1,Cover-3,Zone
2,43384,6-6,310,Graham Glasgow,2.021101e+09,2974.0,32.0,DEN,0.96,4.26,...,NaN,107.0,SHOTGUN,"1 RB, 1 TE, 3 WR",7.0,"3 DL, 4 LB, 4 DB",NaN,0,Cover-1,Man
3,48485,6-5,310,Blake Hance,2.021101e+09,3183.0,24.0,CLE,1.34,4.22,...,NaN,32.0,SINGLEBACK,"1 RB, 3 TE, 1 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,0,Cover-6,Zone
4,42404,6-4,307,Ali Marpet,2.021101e+09,3419.0,38.0,TB,0.75,4.09,...,NaN,69.0,I_FORM,"1 RB, 2 TE, 2 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,1,Cover-3,Zone

In [37]:
w5_G.drop(columns=[['possessionTeam','pff_passCoverage','pff_passCoverageType']], inplace=True, errors='ignore')
w5_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,52466,6-6,310,Ezra Cleveland,2.021101e+09,1420.0,10.0,MIN,0.92,4.78,...,NaN,42.0,SINGLEBACK,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,1,Cover-2,Zone
1,39684,6-3,305,Greg Van Roten,2.021101e+09,2402.0,42.0,NYJ,1.65,4.41,...,NaN,74.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,1,Cover-3,Zone
2,43384,6-6,310,Graham Glasgow,2.021101e+09,2974.0,32.0,DEN,0.96,4.26,...,NaN,107.0,SHOTGUN,"1 RB, 1 TE, 3 WR",7.0,"3 DL, 4 LB, 4 DB",NaN,0,Cover-1,Man
3,48485,6-5,310,Blake Hance,2.021101e+09,3183.0,24.0,CLE,1.34,4.22,...,NaN,32.0,SINGLEBACK,"1 RB, 3 TE, 1 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,0,Cover-6,Zone
4,42404,6-4,307,Ali Marpet,2.021101e+09,3419.0,38.0,TB,0.75,4.09,...,NaN,69.0,I_FORM,"1 RB, 2 TE, 2 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,1,Cover-3,Zone

In [38]:
w5_G = w5_G.merge(pff_df, how='left')
w5_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,52466,6-6,310,Ezra Cleveland,2.021101e+09,1420.0,10.0,MIN,0.92,4.78,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,52605.0,PT,0.0
1,39684,6-3,305,Greg Van Roten,2.021101e+09,2402.0,42.0,NYJ,1.65,4.41,...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,42480.0,PA,0.0
2,43384,6-6,310,Graham Glasgow,2.021101e+09,2974.0,32.0,DEN,0.96,4.26,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,44886.0,PP,0.0
3,48485,6-5,310,Blake Hance,2.021101e+09,3183.0,24.0,CLE,1.34,4.22,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,43292.0,PP,0.0
4,42404,6-4,307,Ali Marpet,2.021101e+09,3419.0,38.0,TB,0.75,4.09,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,46307.0,PA,0.0

In [39]:
w5_G = w5_G.merge(games_df, how='left')
w5_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,52466,6-6,310,Ezra Cleveland,2.021101e+09,1420.0,10.0,MIN,0.92,4.78,...,0.0,52605.0,PT,0.0,2021,5,10/10/2021,13:00:00,MIN,DET
1,39684,6-3,305,Greg Van Roten,2.021101e+09,2402.0,42.0,NYJ,1.65,4.41,...,0.0,42480.0,PA,0.0,2021,5,10/10/2021,09:30:00,ATL,NYJ
2,43384,6-6,310,Graham Glasgow,2.021101e+09,2974.0,32.0,DEN,0.96,4.26,...,0.0,44886.0,PP,0.0,2021,5,10/10/2021,13:00:00,PIT,DEN
3,48485,6-5,310,Blake Hance,2.021101e+09,3183.0,24.0,CLE,1.34,4.22,...,0.0,43292.0,PP,0.0,2021,5,10/10/2021,16:05:00,LAC,CLE
4,42404,6-4,307,Ali Marpet,2.021101e+09,3419.0,38.0,TB,0.75,4.09,...,0.0,46307.0,PA,0.0,2021,5,10/10/2021,13:00:00,TB,MIA

In [40]:
w5_G.drop(columns=['homeTeamAbbr', 'visitorTeamAbbr','gameDate', 'gameTimeEastern', 'season'], inplace=True, errors='ignore')
w5_G.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,52466,6-6,310,Ezra Cleveland,2.021101e+09,1420.0,10.0,MIN,0.92,4.78,...,NaN,NaN,0.0,0.0,0.0,0.0,52605.0,PT,0.0,5
1,39684,6-3,305,Greg Van Roten,2.021101e+09,2402.0,42.0,NYJ,1.65,4.41,...,NaN,NaN,1.0,0.0,0.0,0.0,42480.0,PA,0.0,5
2,43384,6-6,310,Graham Glasgow,2.021101e+09,2974.0,32.0,DEN,0.96,4.26,...,NaN,NaN,0.0,0.0,0.0,0.0,44886.0,PP,0.0,5
3,48485,6-5,310,Blake Hance,2.021101e+09,3183.0,24.0,CLE,1.34,4.22,...,NaN,NaN,0.0,0.0,0.0,0.0,43292.0,PP,0.0,5
4,42404,6-4,307,Ali Marpet,2.021101e+09,3419.0,38.0,TB,0.75,4.09,...,NaN,NaN,0.0,0.0,0.0,0.0,46307.0,PA,0.0,5

In [42]:
w5_G.to_csv('Resources/guard_w5.csv', sep=',', index=False)

In [43]:
w5_G_df = pd.read_csv('Resources/guard_w5.csv')
w5_G_df.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,52466,6-6,310,Ezra Cleveland,2.021101e+09,1420.0,10.0,MIN,0.92,4.78,...,NaN,NaN,0.0,0.0,0.0,0.0,52605.0,PT,0.0,5
1,39684,6-3,305,Greg Van Roten,2.021101e+09,2402.0,42.0,NYJ,1.65,4.41,...,NaN,NaN,1.0,0.0,0.0,0.0,42480.0,PA,0.0,5
2,43384,6-6,310,Graham Glasgow,2.021101e+09,2974.0,32.0,DEN,0.96,4.26,...,NaN,NaN,0.0,0.0,0.0,0.0,44886.0,PP,0.0,5
3,48485,6-5,310,Blake Hance,2.021101e+09,3183.0,24.0,CLE,1.34,4.22,...,NaN,NaN,0.0,0.0,0.0,0.0,43292.0,PP,0.0,5
4,42404,6-4,307,Ali Marpet,2.021101e+09,3419.0,38.0,TB,0.75,4.09,...,NaN,NaN,0.0,0.0,0.0,0.0,46307.0,PA,0.0,5

## Tackle

In [44]:
w5_T = cleaned_T.merge(plays_df, how="left")
w5_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,43640,6-6,313,Rashod Hill,2.021101e+09,495.0,15.0,MIN,3.79,6.33,...,NaN,86.0,SINGLEBACK,"2 RB, 0 TE, 3 WR",6.0,"2 DL, 4 LB, 5 DB",DESIGNED_ROLLOUT_LEFT,1,Cover-3,Zone
1,43586,6-5,322,George Fant,2.021101e+09,2452.0,7.0,NYJ,1.04,5.37,...,NaN,59.0,I_FORM,"1 RB, 1 TE, 3 WR",7.0,"2 DL, 4 LB, 5 DB",DESIGNED_ROLLOUT_RIGHT,1,Cover-1,Man
2,52603,6-5,290,Justin Herron,2.021101e+09,3549.0,37.0,NE,0.90,5.26,...,NaN,68.0,I_FORM,"2 RB, 1 TE, 2 WR",8.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1,Cover-3,Zone
3,52603,6-5,290,Justin Herron,2.021101e+09,3549.0,38.0,NE,0.60,5.21,...,NaN,68.0,I_FORM,"2 RB, 1 TE, 2 WR",8.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1,Cover-3,Zone
4,41222,6-9,320,Alejandro Villanueva,2.021101e+09,2239.0,60.0,BAL,1.32,5.10,...,NaN,77.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",SCRAMBLE,0,Cover-3,Zone

In [45]:
w5_T.drop(columns=['possessionTeam','pff_passCoverage','pff_passCoverageType'], inplace=True, errors='ignore')
w5_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,foulNFLId2,foulName3,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction
0,43640,6-6,313,Rashod Hill,2.021101e+09,495.0,15.0,MIN,3.79,6.33,...,NaN,NaN,NaN,86.0,SINGLEBACK,"2 RB, 0 TE, 3 WR",6.0,"2 DL, 4 LB, 5 DB",DESIGNED_ROLLOUT_LEFT,1
1,43586,6-5,322,George Fant,2.021101e+09,2452.0,7.0,NYJ,1.04,5.37,...,NaN,NaN,NaN,59.0,I_FORM,"1 RB, 1 TE, 3 WR",7.0,"2 DL, 4 LB, 5 DB",DESIGNED_ROLLOUT_RIGHT,1
2,52603,6-5,290,Justin Herron,2.021101e+09,3549.0,37.0,NE,0.90,5.26,...,NaN,NaN,NaN,68.0,I_FORM,"2 RB, 1 TE, 2 WR",8.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1
3,52603,6-5,290,Justin Herron,2.021101e+09,3549.0,38.0,NE,0.60,5.21,...,NaN,NaN,NaN,68.0,I_FORM,"2 RB, 1 TE, 2 WR",8.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1
4,41222,6-9,320,Alejandro Villanueva,2.021101e+09,2239.0,60.0,BAL,1.32,5.10,...,NaN,NaN,NaN,77.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",SCRAMBLE,0

In [46]:
w5_T = w5_T.merge(pff_df, how='left')
w5_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hit,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
0,43640,6-6,313,Rashod Hill,2.021101e+09,495.0,15.0,MIN,3.79,6.33,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,40171.0,PA,0.0
1,43586,6-5,322,George Fant,2.021101e+09,2452.0,7.0,NYJ,1.04,5.37,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,46269.0,PA,0.0
2,52603,6-5,290,Justin Herron,2.021101e+09,3549.0,37.0,NE,0.90,5.26,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,52498.0,PP,0.0
3,52603,6-5,290,Justin Herron,2.021101e+09,3549.0,38.0,NE,0.60,5.21,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,52498.0,PP,0.0
4,41222,6-9,320,Alejandro Villanueva,2.021101e+09,2239.0,60.0,BAL,1.32,5.10,...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,45287.0,PP,0.0

In [47]:
w5_T = w5_T.merge(games_df, how='left')
w5_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,43640,6-6,313,Rashod Hill,2.021101e+09,495.0,15.0,MIN,3.79,6.33,...,0.0,40171.0,PA,0.0,2021,5,10/10/2021,13:00:00,MIN,DET
1,43586,6-5,322,George Fant,2.021101e+09,2452.0,7.0,NYJ,1.04,5.37,...,0.0,46269.0,PA,0.0,2021,5,10/10/2021,09:30:00,ATL,NYJ
2,52603,6-5,290,Justin Herron,2.021101e+09,3549.0,37.0,NE,0.90,5.26,...,0.0,52498.0,PP,0.0,2021,5,10/10/2021,13:00:00,HOU,NE
3,52603,6-5,290,Justin Herron,2.021101e+09,3549.0,38.0,NE,0.60,5.21,...,0.0,52498.0,PP,0.0,2021,5,10/10/2021,13:00:00,HOU,NE
4,41222,6-9,320,Alejandro Villanueva,2.021101e+09,2239.0,60.0,BAL,1.32,5.10,...,0.0,45287.0,PP,0.0,2021,5,10/11/2021,20:15:00,BAL,IND

In [48]:
w5_T.drop(columns=['homeTeamAbbr', 'visitorTeamAbbr','gameDate', 'gameTimeEastern', 'season'], inplace=True, errors='ignore')
w5_T.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,43640,6-6,313,Rashod Hill,2.021101e+09,495.0,15.0,MIN,3.79,6.33,...,NaN,NaN,0.0,0.0,0.0,0.0,40171.0,PA,0.0,5
1,43586,6-5,322,George Fant,2.021101e+09,2452.0,7.0,NYJ,1.04,5.37,...,NaN,NaN,0.0,0.0,0.0,0.0,46269.0,PA,0.0,5
2,52603,6-5,290,Justin Herron,2.021101e+09,3549.0,37.0,NE,0.90,5.26,...,NaN,NaN,0.0,0.0,0.0,0.0,52498.0,PP,0.0,5
3,52603,6-5,290,Justin Herron,2.021101e+09,3549.0,38.0,NE,0.60,5.21,...,NaN,NaN,0.0,0.0,0.0,0.0,52498.0,PP,0.0,5
4,41222,6-9,320,Alejandro Villanueva,2.021101e+09,2239.0,60.0,BAL,1.32,5.10,...,NaN,NaN,1.0,0.0,0.0,0.0,45287.0,PP,0.0,5

In [49]:
w5_T.to_csv('Resources/tackle_w5.csv', sep=',', index=False)

In [50]:
w5_T_df = pd.read_csv('Resources/tackle_w5.csv')
w5_T_df.head()

,nflId,height,weight,displayName,gameId,playId,frameId,team,s,a,...,pff_hurry,pff_sack,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock,week
0,43640,6-6,313,Rashod Hill,2.021101e+09,495.0,15.0,MIN,3.79,6.33,...,NaN,NaN,0.0,0.0,0.0,0.0,40171.0,PA,0.0,5
1,43586,6-5,322,George Fant,2.021101e+09,2452.0,7.0,NYJ,1.04,5.37,...,NaN,NaN,0.0,0.0,0.0,0.0,46269.0,PA,0.0,5
2,52603,6-5,290,Justin Herron,2.021101e+09,3549.0,37.0,NE,0.90,5.26,...,NaN,NaN,0.0,0.0,0.0,0.0,52498.0,PP,0.0,5
3,52603,6-5,290,Justin Herron,2.021101e+09,3549.0,38.0,NE,0.60,5.21,...,NaN,NaN,0.0,0.0,0.0,0.0,52498.0,PP,0.0,5
4,41222,6-9,320,Alejandro Villanueva,2.021101e+09,2239.0,60.0,BAL,1.32,5.10,...,NaN,NaN,1.0,0.0,0.0,0.0,45287.0,PP,0.0,5